//========= MODERNBOX 2.0.1.0 ============//
//
// Made by Tuxxego
//
//=============================================================================//
using System;
using NCMS;
using NCMS.Utils;
using UnityEngine;
using ReflectionUtility;
using HarmonyLib;
using System.Collections;
using System.Collections.Generic;
using System.Threading;
using life;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static Config;
using System.Reflection;
using UnityEngine.Tilemaps;
using System.IO;
 
namespace M2
{
    class Traits
    {
        //Traits
        public static void init()
        { 
 

		 
		 ActorTrait Jet= new ActorTrait();
         Jet.id = "Jet";
         Jet.path_icon = "ui/Icons/Plane";
         Jet.type = TraitType.Negative;
         Jet.group_id = MBTraitGroup.ModernBox;
         Jet.can_be_cured = false;
         Jet.needs_to_be_explored = false;
         Jet.can_be_given = false;
         Jet.can_be_removed = false;
         Jet.only_active_on_era_flag = false;
         Jet.era_active_night = false;
         Jet.era_active_moon = false;
         Jet.birth = 0.0f;
         Jet.inherit = 0.0f;
         Jet.base_stats[S.fertility] = 0.0f;
         Jet.base_stats[S.max_children] = 0f;
         Jet.base_stats[S.max_age] = 0f;
         Jet.base_stats[S.attack_speed] = 0;
         Jet.base_stats[S.damage] = 0;
         Jet.base_stats[S.speed] = 0f;
         Jet.base_stats[S.health] = 0;
         Jet.base_stats[S.accuracy] = 0f;
         Jet.base_stats[S.range] = 0;
         Jet.base_stats[S.armor] = 0;
         Jet.base_stats[S.scale] = 0.0f;
         Jet.base_stats[S.dodge] = 0f;
         Jet.base_stats[S.targets] = 0f;
         Jet.base_stats[S.critical_chance] = 0.0f;
         Jet.base_stats[S.knockback] = 0f;
         Jet.base_stats[S.knockback_reduction] = 0f;
         Jet.base_stats[S.intelligence] = 0;
         Jet.base_stats[S.warfare] = 0;
         Jet.base_stats[S.diplomacy] = 0;
         Jet.base_stats[S.stewardship] = 0;
         Jet.base_stats[S.opinion] = 0f;
         Jet.base_stats[S.loyalty_traits] = 0f;
         Jet.base_stats[S.cities] = 0;
         Jet.base_stats[S.zone_range] = 0;
         AssetManager.traits.add(Jet);
         addTraitToLocalizedLibrary(Jet.id, "Fly through the sky...");
         PlayerConfig.unlockTrait("Jet");
		 
		 ActorTrait Vehicle= new ActorTrait();
         Vehicle.id = "Vehicle";
         Vehicle.path_icon = "ui/Icons/tabIconModernWarfare";
         Vehicle.type = TraitType.Negative;
         Vehicle.group_id = MBTraitGroup.ModernBox;
         Vehicle.can_be_cured = false;
         Vehicle.needs_to_be_explored = false;
         Vehicle.can_be_given = false;
         Vehicle.can_be_removed = false;
         Vehicle.only_active_on_era_flag = false;
         Vehicle.era_active_night = false;
         Vehicle.era_active_moon = false;
         Vehicle.birth = 0.0f;
         Vehicle.inherit = 0.0f;
         Vehicle.base_stats[S.fertility] = -100f;
         Vehicle.base_stats[S.max_children] = 0f;
         Vehicle.base_stats[S.max_age] = 0f;
         Vehicle.base_stats[S.attack_speed] = 0;
         Vehicle.base_stats[S.damage] = 0;
         Vehicle.base_stats[S.speed] = 0f;
         Vehicle.base_stats[S.health] = 0;
         Vehicle.base_stats[S.accuracy] = 0f;
         Vehicle.base_stats[S.range] = 0;
         Vehicle.base_stats[S.armor] = 0;
         Vehicle.base_stats[S.scale] = 0.0f;
         Vehicle.base_stats[S.dodge] = 0f;
         Vehicle.base_stats[S.targets] = 0f;
         Vehicle.base_stats[S.critical_chance] = 0.0f;
         Vehicle.base_stats[S.knockback] = 0f;
         Vehicle.base_stats[S.knockback_reduction] = 0f;
         Vehicle.base_stats[S.intelligence] = 0;
         Vehicle.base_stats[S.warfare] = 0;
         Vehicle.base_stats[S.diplomacy] = 0;
         Vehicle.base_stats[S.stewardship] = 0;
         Vehicle.base_stats[S.opinion] = 0f;
         Vehicle.base_stats[S.loyalty_traits] = 0f;
         Vehicle.base_stats[S.cities] = 0;
         Vehicle.base_stats[S.zone_range] = 0;
         AssetManager.traits.add(Vehicle);
         addTraitToLocalizedLibrary(Vehicle.id, "A vehicle from ModernBox.");
         PlayerConfig.unlockTrait("Vehicle");
		 
		 ActorTrait MIRVBoat= new ActorTrait();
         MIRVBoat.id = "MIRVBoat";
         MIRVBoat.path_icon = "ui/Icons/Boat";
         MIRVBoat.type = TraitType.Negative;
         MIRVBoat.group_id = MBTraitGroup.ModernBox;
         MIRVBoat.can_be_cured = false;
         MIRVBoat.needs_to_be_explored = false;
         MIRVBoat.can_be_given = false;
         MIRVBoat.can_be_removed = false;
         MIRVBoat.only_active_on_era_flag = false;
         MIRVBoat.era_active_night = false;
         MIRVBoat.era_active_moon = false;
         MIRVBoat.birth = 0.0f;
         MIRVBoat.inherit = 0.0f;
         MIRVBoat.base_stats[S.fertility] = 0.0f;
         MIRVBoat.base_stats[S.max_children] = 0f;
         MIRVBoat.base_stats[S.max_age] = 0f;
         MIRVBoat.base_stats[S.attack_speed] = 0;
         MIRVBoat.base_stats[S.damage] = 0;
         MIRVBoat.base_stats[S.speed] = 0f;
         MIRVBoat.base_stats[S.health] = 0;
         MIRVBoat.base_stats[S.accuracy] = 0f;
         MIRVBoat.base_stats[S.range] = 0;
         MIRVBoat.base_stats[S.armor] = 0;
         MIRVBoat.base_stats[S.scale] = 0.0f;
         MIRVBoat.base_stats[S.dodge] = 0f;
         MIRVBoat.base_stats[S.targets] = 0f;
         MIRVBoat.base_stats[S.critical_chance] = 0.0f;
         MIRVBoat.base_stats[S.knockback] = 0f;
         MIRVBoat.base_stats[S.knockback_reduction] = 0f;
         MIRVBoat.base_stats[S.intelligence] = 0;
         MIRVBoat.base_stats[S.warfare] = 0;
         MIRVBoat.base_stats[S.diplomacy] = 0;
         MIRVBoat.base_stats[S.stewardship] = 0;
         MIRVBoat.base_stats[S.opinion] = 0f;
         MIRVBoat.base_stats[S.loyalty_traits] = 0f;
         MIRVBoat.base_stats[S.cities] = 0;
         MIRVBoat.base_stats[S.zone_range] = 0;
         AssetManager.traits.add(MIRVBoat);
         addTraitToLocalizedLibrary(MIRVBoat.id, "He's a armored boy");
         PlayerConfig.unlockTrait("MIRVBoat");
 
 		 ActorTrait Helicopter= new ActorTrait();
         Helicopter.id = "Helicopter";
         Helicopter.path_icon = "ui/Icons/Heli";
         Helicopter.type = TraitType.Negative;
         Helicopter.group_id = MBTraitGroup.ModernBox;
         Helicopter.can_be_cured = false;
         Helicopter.needs_to_be_explored = false;
         Helicopter.can_be_given = false;
         Helicopter.can_be_removed = false;
         Helicopter.only_active_on_era_flag = false;
         Helicopter.era_active_night = false;
         Helicopter.era_active_moon = false;
         Helicopter.birth = 0.0f;
         Helicopter.inherit = 0.0f;
         Helicopter.base_stats[S.fertility] = 0.0f;
         Helicopter.base_stats[S.max_children] = 0f;
         Helicopter.base_stats[S.max_age] = 0f;
         Helicopter.base_stats[S.attack_speed] = 0;
         Helicopter.base_stats[S.damage] = 0;
         Helicopter.base_stats[S.speed] = 0f;
         Helicopter.base_stats[S.health] = 0;
         Helicopter.base_stats[S.accuracy] = 0f;
         Helicopter.base_stats[S.range] = 0;
         Helicopter.base_stats[S.armor] = 0;
         Helicopter.base_stats[S.scale] = 0.0f;
         Helicopter.base_stats[S.dodge] = 0f;
         Helicopter.base_stats[S.targets] = 0f;
         Helicopter.base_stats[S.critical_chance] = 0.0f;
         Helicopter.base_stats[S.knockback] = 0f;
         Helicopter.base_stats[S.knockback_reduction] = 0f;
         Helicopter.base_stats[S.intelligence] = 0;
         Helicopter.base_stats[S.warfare] = 0;
         Helicopter.base_stats[S.diplomacy] = 0;
         Helicopter.base_stats[S.stewardship] = 0;
         Helicopter.base_stats[S.opinion] = 0f;
         Helicopter.base_stats[S.loyalty_traits] = 0f;
         Helicopter.base_stats[S.cities] = 0;
         Helicopter.base_stats[S.zone_range] = 0;
         AssetManager.traits.add(Helicopter);
         addTraitToLocalizedLibrary(Helicopter.id, "HELICOPTER HELICOPTER BRRRRRRRRRRRR");
         PlayerConfig.unlockTrait("Helicopter");
		 
		 ActorTrait Tank= new ActorTrait();
         Tank.id = "Tank";
         Tank.path_icon = "ui/Icons/Tank";
         Tank.type = TraitType.Negative;
         Tank.group_id = MBTraitGroup.ModernBox;
         Tank.can_be_cured = false;
         Tank.needs_to_be_explored = false;
         Tank.can_be_given = false;
         Tank.can_be_removed = false;
         Tank.only_active_on_era_flag = false;
         Tank.era_active_night = false;
         Tank.era_active_moon = false;
         Tank.birth = 0.0f;
         Tank.inherit = 0.0f;
         Tank.base_stats[S.fertility] = 0.0f;
         Tank.base_stats[S.max_children] = 0f;
         Tank.base_stats[S.max_age] = 0f;
         Tank.base_stats[S.attack_speed] = 0;
         Tank.base_stats[S.damage] = 0;
         Tank.base_stats[S.speed] = 0f;
         Tank.base_stats[S.health] = 0;
         Tank.base_stats[S.accuracy] = 0f;
         Tank.base_stats[S.range] = 0;
         Tank.base_stats[S.armor] = 0;
         Tank.base_stats[S.scale] = 0.0f;
         Tank.base_stats[S.dodge] = 0f;
         Tank.base_stats[S.targets] = 0f;
         Tank.base_stats[S.critical_chance] = 0.0f;
         Tank.base_stats[S.knockback] = 0f;
         Tank.base_stats[S.knockback_reduction] = 0f;
         Tank.base_stats[S.intelligence] = 0;
         Tank.base_stats[S.warfare] = 0;
         Tank.base_stats[S.diplomacy] = 0;
         Tank.base_stats[S.stewardship] = 0;
         Tank.base_stats[S.opinion] = 0f;
         Tank.base_stats[S.loyalty_traits] = 0f;
         Tank.base_stats[S.cities] = 0;
         Tank.base_stats[S.zone_range] = 0;
         AssetManager.traits.add(Tank);
         addTraitToLocalizedLibrary(Tank.id, "Armoured Vehicle.");
         PlayerConfig.unlockTrait("Tank");

            ActorTrait Railgun = new ActorTrait();
            Railgun.id = "Railgun";
            Railgun.path_icon = "ui/Icons/Railgun";
            Railgun.type = TraitType.Negative;
            Railgun.group_id = MBTraitGroup.ModernBox;
            Railgun.can_be_cured = false;
            Railgun.needs_to_be_explored = false;
            Railgun.can_be_given = false;
            Railgun.can_be_removed = false;
            Railgun.only_active_on_era_flag = false;
            Railgun.era_active_night = false;
            Railgun.era_active_moon = false;
            Railgun.birth = 0.0f;
            Railgun.inherit = 0.0f;
            Railgun.base_stats[S.fertility] = 0.0f;
            Railgun.base_stats[S.max_children] = 0f;
            Railgun.base_stats[S.max_age] = 0f;
            Railgun.base_stats[S.attack_speed] = 0;
            Railgun.base_stats[S.damage] = 0;
            Railgun.base_stats[S.speed] = 0f;
            Railgun.base_stats[S.health] = 0;
            Railgun.base_stats[S.accuracy] = 0f;
            Railgun.base_stats[S.range] = 0;
            Railgun.base_stats[S.armor] = 0;
            Railgun.base_stats[S.scale] = 0.0f;
            Railgun.base_stats[S.dodge] = 0f;
            Railgun.base_stats[S.targets] = 0f;
            Railgun.base_stats[S.critical_chance] = 0.0f;
            Railgun.base_stats[S.knockback] = 0f;
            Railgun.base_stats[S.knockback_reduction] = 0f;
            Railgun.base_stats[S.intelligence] = 0;
            Railgun.base_stats[S.warfare] = 0;
            Railgun.base_stats[S.diplomacy] = 0;
            Railgun.base_stats[S.stewardship] = 0;
            Railgun.base_stats[S.opinion] = 0f;
            Railgun.base_stats[S.loyalty_traits] = 0f;
            Railgun.base_stats[S.cities] = 0;
            Railgun.base_stats[S.zone_range] = 0;
            AssetManager.traits.add(Railgun);
            addTraitToLocalizedLibrary(Railgun.id, "Armoured Vehicle.");
            PlayerConfig.unlockTrait("Railgun");

            ActorTrait Humvee= new ActorTrait();
         Humvee.id = "Humvee";
         Humvee.path_icon = "ui/Icons/Humvee";
         Humvee.type = TraitType.Negative;
         Humvee.group_id = MBTraitGroup.ModernBox;
         Humvee.can_be_cured = false;
         Humvee.needs_to_be_explored = false;
         Humvee.can_be_given = false;
         Humvee.can_be_removed = false;
         Humvee.only_active_on_era_flag = false;
         Humvee.era_active_night = false;
         Humvee.era_active_moon = false;
         Humvee.birth = 0.0f;
         Humvee.inherit = 0.0f;
         Humvee.base_stats[S.fertility] = 0.0f;
         Humvee.base_stats[S.max_children] = 0f;
         Humvee.base_stats[S.max_age] = 0f;
         Humvee.base_stats[S.attack_speed] = 0;
         Humvee.base_stats[S.damage] = 0;
         Humvee.base_stats[S.speed] = 0f;
         Humvee.base_stats[S.health] = 0;
         Humvee.base_stats[S.accuracy] = 0f;
         Humvee.base_stats[S.range] = 0;
         Humvee.base_stats[S.armor] = 0;
         Humvee.base_stats[S.scale] = 0.0f;
         Humvee.base_stats[S.dodge] = 0f;
         Humvee.base_stats[S.targets] = 0f;
         Humvee.base_stats[S.critical_chance] = 0.0f;
         Humvee.base_stats[S.knockback] = 0f;
         Humvee.base_stats[S.knockback_reduction] = 0f;
         Humvee.base_stats[S.intelligence] = 0;
         Humvee.base_stats[S.warfare] = 0;
         Humvee.base_stats[S.diplomacy] = 0;
         Humvee.base_stats[S.stewardship] = 0;
         Humvee.base_stats[S.opinion] = 0f;
         Humvee.base_stats[S.loyalty_traits] = 0f;
         Humvee.base_stats[S.cities] = 0;
         Humvee.base_stats[S.zone_range] = 0;
         AssetManager.traits.add(Humvee);
         addTraitToLocalizedLibrary(Humvee.id, "Awesome military vehicle.");
         PlayerConfig.unlockTrait("Humvee");
 
 		 ActorTrait Zeppelin= new ActorTrait();
         Zeppelin.id = "Zeppelin";
         Zeppelin.path_icon = "ui/Icons/Airship";
         Zeppelin.type = TraitType.Negative;
         Zeppelin.group_id = MBTraitGroup.ModernBox;
         Zeppelin.can_be_cured = false;
         Zeppelin.needs_to_be_explored = false;
         Zeppelin.can_be_given = false;
         Zeppelin.can_be_removed = false;
         Zeppelin.only_active_on_era_flag = false;
         Zeppelin.era_active_night = false;
         Zeppelin.era_active_moon = false;
         Zeppelin.birth = 0.0f;
         Zeppelin.inherit = 0.0f;
         Zeppelin.base_stats[S.fertility] = 0.0f;
         Zeppelin.base_stats[S.max_children] = 0f;
         Zeppelin.base_stats[S.max_age] = 0f;
         Zeppelin.base_stats[S.attack_speed] = 0;
         Zeppelin.base_stats[S.damage] = 0;
         Zeppelin.base_stats[S.speed] = 0f;
         Zeppelin.base_stats[S.health] = 0;
         Zeppelin.base_stats[S.accuracy] = 0f;
         Zeppelin.base_stats[S.range] = 0;
         Zeppelin.base_stats[S.armor] = 0;
         Zeppelin.base_stats[S.scale] = 0.0f;
         Zeppelin.base_stats[S.dodge] = 0f;
         Zeppelin.base_stats[S.targets] = 0f;
         Zeppelin.base_stats[S.critical_chance] = 0.0f;
         Zeppelin.base_stats[S.knockback] = 0f;
         Zeppelin.base_stats[S.knockback_reduction] = 0f;
         Zeppelin.base_stats[S.intelligence] = 0;
         Zeppelin.base_stats[S.warfare] = 0;
         Zeppelin.base_stats[S.diplomacy] = 0;
         Zeppelin.base_stats[S.stewardship] = 0;
         Zeppelin.base_stats[S.opinion] = 0f;
         Zeppelin.base_stats[S.loyalty_traits] = 0f;
         Zeppelin.base_stats[S.cities] = 0;
         Zeppelin.base_stats[S.zone_range] = 0;
         AssetManager.traits.add(Zeppelin);
         addTraitToLocalizedLibrary(Zeppelin.id, "Big airship.");
         PlayerConfig.unlockTrait("Zeppelin");
        }
        public static void addTraitToLocalizedLibrary(string id, string description)
        {
        string language = Reflection.GetField(LocalizedTextManager.instance.GetType(), LocalizedTextManager.instance, "language") as string;
        Dictionary<string, string> localizedText = Reflection.GetField(LocalizedTextManager.instance.GetType(), LocalizedTextManager.instance, "localizedText") as Dictionary<string, string>;
        localizedText.Add("trait_" + id, id);
        localizedText.Add("trait_" + id + "_info", description);
        }
    }
}
