//========= MODERNBOX 2.1.0.1 ============//
//
// Made by Tuxxego
//
//=============================================================================//
using System;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using NCMS;
using NCMS.Utils;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using ReflectionUtility;
using HarmonyLib;

namespace M2 {
class Aircraft : MonoBehaviour {

  public static void init() { loadAssets(); }

  private static void loadAssets() {



    var Heli = AssetManager.actor_library.clone("Heli", "_mob");
    // ActorAsset heli = new ActorAsset();
    // Heli.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    Heli.race = "human";
    Heli.kingdom = "ModernKingdom";
    Heli.base_stats[S.max_age] = 50f;
    Heli.base_stats[S.attack_speed] = 10000f;
    Heli.base_stats[S.accuracy] = 100f;
    Heli.base_stats[S.health] = 500f;
    Heli.base_stats[S.speed] = 200f;
    Heli.base_stats[S.scale] = 0.1f;
    Heli.base_stats[S.damage] = 10f;
    Heli.base_stats[S.knockback_reduction] = 300f;
    Heli.immune_to_injuries = true;
    Heli.inspect_stats = true;
    Heli.landCreature = true;
    Heli.inspect_home = true;
    Heli.has_skin = false;
    Heli.flying = true;
    Heli.can_edit_traits = true;
    // Heli.tech = "Helicopters";
    Heli.canReceiveTraits = true;
    Heli.very_high_flyer = true;
    Heli.defaultAttack = "machinegunery";
    Heli.isBoat = false;
    Heli.dieOnBlocks = false;
    Heli.ignoreBlocks = true;
    Heli.disablePunchAttackAnimation = true;
    Heli.moveFromBlock = false;
    Heli.inspect_children = false;
    Heli.inspect_experience = true;
    Heli.canBeCitizen = true;
    Heli.inspect_kills = true;
    Heli.hideOnMinimap = false;
    Heli.use_items = false;
    Heli.oceanCreature = true;
    Heli.take_items = false;
    Heli.nameLocale = "Heli";
    Heli.nameTemplate = "Jet_Names";
    // Heli.job = "attacker";
    Heli.job = "attacker";
    Heli.icon = "iconHeli";
    AssetManager.actor_library.CallMethod("addTrait", "Helicopter");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
    AssetManager.actor_library.CallMethod("loadShadow", Heli);
    Heli.animation_idle = "walk_0,walk_1,walk_2,walk_3";
    Heli.animation_walk = "walk_0,walk_1,walk_2,walk_3";
    Heli.animation_swim = "walk_0,walk_1,walk_2,walk_3";
    Heli.texture_path = "Heli";
    // Heli.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(Heli);
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
        AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.addColorSet("heliColor");
    Heli.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(Heli.nameLocale, Heli.nameLocale);

      var HeliELite = AssetManager.actor_library.clone("HeliELite", "_mob");
    // ActorAsset heli = new ActorAsset();
    // HeliELite.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
  HeliELite.race = "human";
  HeliELite.kingdom = "ModernKingdom";
  HeliELite.base_stats[S.max_age] = 50f;
  HeliELite.base_stats[S.attack_speed] = 500f;
  HeliELite.base_stats[S.accuracy] = 100f;
  HeliELite.base_stats[S.health] = 800f;
  HeliELite.base_stats[S.speed] = 200f;
  HeliELite.base_stats[S.scale] = 0.1f;
  HeliELite.base_stats[S.damage] = 10f;
  HeliELite.base_stats[S.knockback_reduction] = 300f;
  HeliELite.immune_to_injuries = true;
  HeliELite.inspect_stats = true;
  HeliELite.landCreature = true;
  HeliELite.inspect_home = true;
  HeliELite.has_skin = false;
  HeliELite.flying = true;
  HeliELite.can_edit_traits = true;
    // Heli.tech = "Helicopters";
  HeliELite.canReceiveTraits = true;
  HeliELite.very_high_flyer = true;
  HeliELite.defaultAttack = "heliRocket";
  HeliELite.isBoat = false;
  HeliELite.dieOnBlocks = false;
  HeliELite.ignoreBlocks = true;
  HeliELite.disablePunchAttackAnimation = true;
  HeliELite.moveFromBlock = false;
  HeliELite.inspect_children = false;
  HeliELite.inspect_experience = true;
  HeliELite.canBeCitizen = true;
  HeliELite.inspect_kills = true;
  HeliELite.hideOnMinimap = false;
  HeliELite.use_items = false;
  HeliELite.oceanCreature = true;
  HeliELite.take_items = false;
  HeliELite.nameLocale = "HeliELite";
  HeliELite.nameTemplate = "Jet_Names";
    // HeliELite.job = "attacker";
  HeliELite.job = "attacker";
  HeliELite.icon = "iconHeli";
    AssetManager.actor_library.CallMethod("addTrait", "Helicopter");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
    AssetManager.actor_library.CallMethod("loadShadow", HeliELite);
  HeliELite.animation_idle = "idle_0,idle_1,idle_2,idle_3";
  HeliELite.animation_walk = "walk_0,walk_1,walk_2,walk_3";
  HeliELite.texture_path = "HeliELite";
    // HeliELite.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(HeliELite);
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.addColorSet("heliColor");
  HeliELite.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(HeliELite.nameLocale, HeliELite.nameLocale);

    var Gunship = AssetManager.actor_library.clone("Gunship", "_mob");
    // ActorAsset heli = new ActorAsset();
    // Gunship.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    Gunship.race = "human";
    Gunship.kingdom = "ModernKingdom";
    Gunship.base_stats[S.max_age] = 50f;
    Gunship.base_stats[S.attack_speed] = 100f;
    Gunship.base_stats[S.accuracy] = 100f;
    Gunship.base_stats[S.health] = 100f;
    Gunship.base_stats[S.speed] = 200f;
    Gunship.base_stats[S.scale] = 0.2f;
    Gunship.base_stats[S.damage] = 40;
    Gunship.base_stats[S.knockback_reduction] = 0f;
    Gunship.immune_to_injuries = true;
    Gunship.inspect_stats = true;
    Gunship.landCreature = true;
    Gunship.inspect_home = true;
    Gunship.has_skin = false;
    Gunship.flying = true;
    Gunship.can_edit_traits = true;
    Gunship.deathAnimationAngle = false;
    // Gunship.tech = "Gunshipcopters";
    Gunship.canReceiveTraits = true;
    Gunship.very_high_flyer = true;
    Gunship.defaultAttack = "singleshot";
    Gunship.isBoat = false;
    Gunship.dieOnBlocks = false;
    Gunship.ignoreBlocks = true;
    Gunship.moveFromBlock = false;
    Gunship.inspect_children = false;
    Gunship.inspect_experience = true;
    Gunship.canBeCitizen = true;
    Gunship.inspect_kills = true;
    Gunship.hideOnMinimap = false;
        Gunship.disablePunchAttackAnimation = true;
    Gunship.use_items = false;
    Gunship.oceanCreature = true;
    Gunship.take_items = false;
    Gunship.nameLocale = "Gunship";
    Gunship.nameTemplate = "Jet_Names";
    // Gunship.job = "attacker";
    Gunship.job = "attacker";
    Gunship.icon = "iconGunship";
    // AssetManager.actor_library.CallMethod("addTrait", "Gunshipcopter");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("loadShadow", Gunship);
    Gunship.animation_idle = "walk_0,walk_1,walk_2,walk_3";
    Gunship.animation_walk = "walk_0,walk_1,walk_2,walk_3";
    Gunship.animation_swim = "walk_1,walk_2";
    Gunship.texture_path = "Gunship";
    // Gunship.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(Gunship);
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
    AssetManager.actor_library.addColorSet("heliColor");
    Gunship.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(Gunship.nameLocale, Gunship.nameLocale);

    		var balloonunit = AssetManager.actor_library.clone("balloonunit", "_mob");
    // ActorAsset heli = new ActorAsset();
    // balloonunit.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    balloonunit.race = "human";
    balloonunit.kingdom = "ModernKingdom";
    balloonunit.base_stats[S.max_age] = 50f;
    balloonunit.base_stats[S.attack_speed] = 1f;
    balloonunit.base_stats[S.accuracy] = 100f;
    balloonunit.base_stats[S.health] = 100f;
    balloonunit.base_stats[S.speed] = 200f;
    balloonunit.base_stats[S.scale] = 0.2f;
    balloonunit.base_stats[S.damage] = 40;
    balloonunit.base_stats[S.knockback_reduction] = 0f;
    balloonunit.immune_to_injuries = true;
    balloonunit.inspect_stats = true;
    balloonunit.landCreature = true;
    balloonunit.inspect_home = true;
    balloonunit.has_skin = false;
    balloonunit.flying = true;
    balloonunit.can_edit_traits = true;
    balloonunit.deathAnimationAngle = false;
    // balloonunit.tech = "balloonunitcopters";
    balloonunit.canReceiveTraits = true;
    balloonunit.very_high_flyer = true;
    balloonunit.defaultAttack = "incendiarybombing";
    balloonunit.isBoat = false;
    balloonunit.dieOnBlocks = false;
    balloonunit.ignoreBlocks = true;
    balloonunit.moveFromBlock = false;
    balloonunit.inspect_children = false;
    balloonunit.inspect_experience = true;
    balloonunit.canBeCitizen = true;
    balloonunit.inspect_kills = true;
    balloonunit.hideOnMinimap = false;
        balloonunit.disablePunchAttackAnimation = true;
    balloonunit.use_items = false;
    balloonunit.oceanCreature = true;
    balloonunit.take_items = false;
    balloonunit.nameLocale = "balloonunit";
    balloonunit.nameTemplate = "Jet_Names";
    // balloonunit.job = "attacker";
    balloonunit.job = "attacker";
    balloonunit.icon = "iconballoonunit";
    // AssetManager.actor_library.CallMethod("addTrait", "balloonunitcopter");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("loadShadow", balloonunit);
    balloonunit.animation_idle = "walk_0,walk_1,walk_2,walk_3";
    balloonunit.animation_walk = "walk_0,walk_1,walk_2,walk_3";
    balloonunit.texture_path = "balloonunit";
    // balloonunit.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(balloonunit);
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
    AssetManager.actor_library.addColorSet("heliColor");
    balloonunit.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(balloonunit.nameLocale, balloonunit.nameLocale);


    		var bigfaerydragon = AssetManager.actor_library.clone("bigfaerydragon", "_mob");
    // ActorAsset heli = new ActorAsset();
    // bigfaerydragon.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    bigfaerydragon.race = "human";
    bigfaerydragon.kingdom = "ModernKingdom";
    bigfaerydragon.base_stats[S.max_age] = 50f;
    bigfaerydragon.base_stats[S.attack_speed] = 100f;
    bigfaerydragon.base_stats[S.accuracy] = 100f;
    bigfaerydragon.base_stats[S.health] = 100f;
    bigfaerydragon.base_stats[S.speed] = 200f;
    bigfaerydragon.base_stats[S.scale] = 0.2f;
    bigfaerydragon.base_stats[S.damage] = 40;
    bigfaerydragon.base_stats[S.knockback_reduction] = 0f;
    bigfaerydragon.immune_to_injuries = true;
    bigfaerydragon.inspect_stats = true;
    bigfaerydragon.landCreature = true;
    bigfaerydragon.inspect_home = true;
    bigfaerydragon.has_skin = false;
    bigfaerydragon.flying = true;
    bigfaerydragon.can_edit_traits = true;
    bigfaerydragon.deathAnimationAngle = false;
    // bigfaerydragon.tech = "bigfaerydragoncopters";
    bigfaerydragon.canReceiveTraits = true;
    bigfaerydragon.very_high_flyer = true;
    bigfaerydragon.defaultAttack = "incendiarybombing";
    bigfaerydragon.isBoat = false;
    bigfaerydragon.dieOnBlocks = false;
    bigfaerydragon.ignoreBlocks = true;
    bigfaerydragon.moveFromBlock = false;
    bigfaerydragon.inspect_children = false;
    bigfaerydragon.inspect_experience = true;
    bigfaerydragon.canBeCitizen = true;
    bigfaerydragon.inspect_kills = true;
    bigfaerydragon.hideOnMinimap = false;
        bigfaerydragon.disablePunchAttackAnimation = true;
    bigfaerydragon.use_items = false;
    bigfaerydragon.oceanCreature = true;
    bigfaerydragon.take_items = false;
    bigfaerydragon.nameLocale = "bigfaerydragon";
    bigfaerydragon.nameTemplate = "Jet_Names";
    // bigfaerydragon.job = "attacker";
    bigfaerydragon.job = "attacker";
    bigfaerydragon.icon = "iconbigfaerydragon";
    // AssetManager.actor_library.CallMethod("addTrait", "bigfaerydragoncopter");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("loadShadow", bigfaerydragon);
    bigfaerydragon.animation_idle = "walk_0,walk_1,walk_2,walk_3,walk_4,walk_5";
    bigfaerydragon.animation_walk = "walk_0,walk_1,walk_2,walk_3,walk_4,walk_5";
    bigfaerydragon.texture_path = "bigfaerydragon";
    // bigfaerydragon.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(bigfaerydragon);
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
    AssetManager.actor_library.addColorSet("heliColor");
    bigfaerydragon.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(bigfaerydragon.nameLocale, bigfaerydragon.nameLocale);

    var eliteGunship = AssetManager.actor_library.clone("eliteGunship", "_mob");
    // ActorAsset heli = new ActorAsset();
    //eliteGunship.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
   eliteGunship.race = "human";
   eliteGunship.kingdom = "ModernKingdom";
   eliteGunship.base_stats[S.max_age] = 50f;
   eliteGunship.base_stats[S.attack_speed] = 100f;
   eliteGunship.base_stats[S.accuracy] = 100f;
   eliteGunship.base_stats[S.health] = 1000f;
   eliteGunship.base_stats[S.speed] = 200f;
   eliteGunship.base_stats[S.scale] = 0.2f;
   eliteGunship.base_stats[S.damage] = 100;
   eliteGunship.base_stats[S.knockback_reduction] = 300f;
   eliteGunship.immune_to_injuries = true;
   eliteGunship.inspect_stats = true;
   eliteGunship.landCreature = true;
   eliteGunship.inspect_home = true;
   eliteGunship.has_skin = false;
   eliteGunship.flying = true;
   eliteGunship.can_edit_traits = true;
    //eliteGunship.tech = "Gunshipcopters";
   eliteGunship.canReceiveTraits = true;
   eliteGunship.very_high_flyer = true;
   eliteGunship.defaultAttack = "singleshot";
   eliteGunship.isBoat = false;
   eliteGunship.dieOnBlocks = false;
   eliteGunship.ignoreBlocks = true;
   eliteGunship.moveFromBlock = false;
   eliteGunship.inspect_children = false;
   eliteGunship.inspect_experience = true;
   eliteGunship.canBeCitizen = true;
   eliteGunship.inspect_kills = true;
   eliteGunship.hideOnMinimap = false;
       eliteGunship.disablePunchAttackAnimation = true;
   eliteGunship.use_items = false;
   eliteGunship.oceanCreature = true;
   eliteGunship.take_items = false;
   eliteGunship.nameLocale = "eliteGunship";
   eliteGunship.nameTemplate = "Jet_Names";
    //eliteGunship.job = "attacker";
   eliteGunship.job = "attacker";
   eliteGunship.icon = "iconGunship";
    // AssetManager.actor_library.CallMethod("addTrait", "Gunshipcopter");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
    AssetManager.actor_library.CallMethod("loadShadow", eliteGunship);
   eliteGunship.animation_idle = "idle_0,idle_1,idle_2,idle_3";
   eliteGunship.animation_walk = "walk_0,walk_1,walk_2,walk_3";
   eliteGunship.texture_path = "eliteGunship";
    //eliteGunship.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(eliteGunship);
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.addColorSet("heliColor");
   eliteGunship.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(eliteGunship.nameLocale,eliteGunship.nameLocale);

    var Drone = AssetManager.actor_library.clone("Drone", "_mob");
    // ActorAsset heli = new ActorAsset();
    // Drone.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    Drone.race = "human";
    Drone.kingdom = "ModernKingdom";
    Drone.base_stats[S.max_age] = 5f;
    Drone.base_stats[S.attack_speed] = 1000f;
    Drone.base_stats[S.accuracy] = 100f;
    Drone.base_stats[S.health] = 15f;
    Drone.base_stats[S.speed] = 30f;
    Drone.base_stats[S.damage] = 6;
    Drone.base_stats[S.knockback_reduction] = 300f;
    Drone.immune_to_injuries = true;
    Drone.inspect_stats = true;
    Drone.landCreature = true;
    Drone.inspect_home = true;
    Drone.has_skin = false;
    Drone.flying = true;
    Drone.can_edit_traits = true;
    // Drone.tech = "Dronecopters";
    Drone.canReceiveTraits = true;
    Drone.very_high_flyer = true;
    Drone.defaultAttack = "singleshot";
    Drone.canFlip = false;
    Drone.disablePunchAttackAnimation = true;
    Drone.isBoat = false;
    // Drone.moveFromBlock = false;
    Drone.inspect_children = false;
    Drone.inspect_experience = true;
    Drone.canBeCitizen = true;
    Drone.inspect_kills = true;
    Drone.hideOnMinimap = false;
    Drone.use_items = false;
    Drone.oceanCreature = true;
    Drone.take_items = false;
    Drone.nameLocale = "Drone";
    Drone.nameTemplate = "Jet_Names";
    // Drone.job = "attacker";
    Drone.job = "attacker";
    Drone.icon = "iconDrone";
    // AssetManager.actor_library.CallMethod("addTrait", "Dronecopter");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
    AssetManager.actor_library.CallMethod("loadShadow", Drone);
    Drone.animation_idle = "walk_0,walk_1,walk_2,walk_3";
    Drone.animation_walk = "walk_0,walk_1,walk_2,walk_3";
    Drone.animation_swim = "walk_0,walk_1,walk_2,walk_3";
    Drone.texture_path = "Drone";
    // Drone.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(Drone);
    AssetManager.actor_library.addColorSet("heliColor");
    Drone.color = Toolbox.makeColor("#33724D");
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    Localization.addLocalization(Drone.nameLocale, Drone.nameLocale);

     var TIEfighter = AssetManager.actor_library.clone("TIEfighter", "_mob");
    // ActorAsset heli = new ActorAsset();
    // TIEfighter.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    TIEfighter.race = "human";
    TIEfighter.kingdom = "ModernKingdom";
    TIEfighter.base_stats[S.max_age] = 50f;
    TIEfighter.base_stats[S.attack_speed] = 1000f;
    TIEfighter.base_stats[S.accuracy] = 100f;
    TIEfighter.base_stats[S.health] = 300f;
    TIEfighter.base_stats[S.speed] = 80f;
    TIEfighter.base_stats[S.damage] = 100;
    TIEfighter.base_stats[S.scale] = 0.2f;
    TIEfighter.base_stats[S.knockback_reduction] = 300f;
    TIEfighter.immune_to_injuries = true;
    TIEfighter.inspect_stats = true;
    TIEfighter.landCreature = true;
    TIEfighter.inspect_home = true;
    TIEfighter.has_skin = false;
    TIEfighter.flying = true;
    TIEfighter.can_edit_traits = true;
    // TIEfighter.tech = "Dronecopters";
    TIEfighter.canReceiveTraits = true;
    TIEfighter.very_high_flyer = true;
    TIEfighter.defaultAttack = "singleshot";
    TIEfighter.disablePunchAttackAnimation = true;
    TIEfighter.isBoat = false;
    // TIEfighter.moveFromBlock = false;
    TIEfighter.inspect_children = false;
    TIEfighter.inspect_experience = true;
    TIEfighter.canBeCitizen = true;
    TIEfighter.inspect_kills = true;
    TIEfighter.hideOnMinimap = false;
    TIEfighter.use_items = false;
    TIEfighter.oceanCreature = true;
       TIEfighter.canFlip = true;
    TIEfighter.take_items = false;
    TIEfighter.nameLocale = "TIEfighter";
    TIEfighter.nameTemplate = "Jet_Names";
    // TIEfighter.job = "attacker";
    TIEfighter.job = "attacker";
    TIEfighter.icon = "iconDrone";
    // AssetManager.actor_library.CallMethod("addTrait", "Dronecopter");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("loadShadow", TIEfighter);
    TIEfighter.animation_idle = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7";
    TIEfighter.animation_walk = "walk_0,walk_1,walk_2";
    TIEfighter.texture_path = "TIEfighter";
    // TIEfighter.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(TIEfighter);
    AssetManager.actor_library.addColorSet("heliColor");
    TIEfighter.color = Toolbox.makeColor("#33724D");
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
    Localization.addLocalization(TIEfighter.nameLocale, TIEfighter.nameLocale);

    ColorSetAsset heliColor = new ColorSetAsset();
    heliColor.id = "heliColor";
    heliColor.shades_from = "#FFC984";
    heliColor.shades_to = "#543E2C";
    heliColor.is_default = true;
    AssetManager.skin_color_set_library.add(heliColor);

    var Zeppelin = AssetManager.actor_library.clone("Zeppelin", "_mob");
    // ActorAsset heli = new ActorAsset();
    // Zeppelin.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    Zeppelin.race = "human";
    Zeppelin.kingdom = "ModernKingdom";
    Zeppelin.base_stats[S.max_age] = 50f;
    Zeppelin.base_stats[S.attack_speed] = 0f;
    Zeppelin.base_stats[S.accuracy] = 100f;
    Zeppelin.base_stats[S.health] = 1000f;
    Zeppelin.base_stats[S.speed] = 50f;
    Zeppelin.base_stats[S.scale] = 0.2f;
    Zeppelin.base_stats[S.damage] = 30;
    Zeppelin.base_stats[S.knockback_reduction] = 300f;
    Zeppelin.immune_to_injuries = true;
    Zeppelin.inspect_stats = true;
    Zeppelin.landCreature = true;
    Zeppelin.inspect_home = true;
    Zeppelin.has_skin = false;
    Zeppelin.flying = true;
    Zeppelin.can_edit_traits = true;
    // Zeppelin.tech = "Zeppelincopters";
    Zeppelin.canReceiveTraits = true;
    Zeppelin.very_high_flyer = true;
    Zeppelin.disablePunchAttackAnimation = true;
    Zeppelin.hideOnMinimap = false;
    Zeppelin.defaultAttack = "bomberino";
    Zeppelin.isBoat = false;
    Zeppelin.dieOnBlocks = false;
    Zeppelin.ignoreBlocks = true;
    Zeppelin.moveFromBlock = false;
    Zeppelin.inspect_children = false;
    Zeppelin.inspect_experience = true;
    Zeppelin.canBeCitizen = true;
    Zeppelin.inspect_kills = true;
    Zeppelin.use_items = false;
    Zeppelin.oceanCreature = true;
    Zeppelin.take_items = false;
    Zeppelin.nameLocale = "Zeppelin";
    Zeppelin.nameTemplate = "Jet_Names";
    // Zeppelin.job = "attacker";
    Zeppelin.job = "attacker";
    Zeppelin.icon = "iconZeppelin";
    AssetManager.actor_library.CallMethod("addTrait", "Zeppelin");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("loadShadow", Zeppelin);
    Zeppelin.animation_idle = "walk_0";
    Zeppelin.animation_walk = "walk_0,walk_1,walk_2";
    Zeppelin.animation_swim = "walk_0,walk_1,walk_2";
    Zeppelin.texture_path = "Zeppelin";
    // Zeppelin.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.addColorSet("heliColor");
    Zeppelin.color = Toolbox.makeColor("#33724D");
    AssetManager.actor_library.add(Zeppelin);
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
    Localization.addLocalization(Zeppelin.nameLocale, Zeppelin.nameLocale);

       var EliteZeppelin = AssetManager.actor_library.clone("EliteZeppelin", "_mob");
    // ActorAsset heli = new ActorAsset();
    // EliteZeppelin.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    EliteZeppelin.race = "human";
    EliteZeppelin.kingdom = "ModernKingdom";
    EliteZeppelin.base_stats[S.max_age] = 50f;
    EliteZeppelin.base_stats[S.attack_speed] = 150f;
    EliteZeppelin.base_stats[S.accuracy] = 100f;
    EliteZeppelin.base_stats[S.health] = 3000f;
    EliteZeppelin.base_stats[S.speed] = 70f;
    EliteZeppelin.base_stats[S.scale] = 0.2f;
    EliteZeppelin.base_stats[S.damage] = 40;
    EliteZeppelin.base_stats[S.knockback_reduction] = 300f;
    EliteZeppelin.immune_to_injuries = true;
    EliteZeppelin.inspect_stats = true;
    EliteZeppelin.landCreature = true;
    EliteZeppelin.inspect_home = true;
    EliteZeppelin.has_skin = false;
    EliteZeppelin.flying = true;
    EliteZeppelin.can_edit_traits = true;
    // EliteZeppelin.tech = "Zeppelincopters";
    EliteZeppelin.canReceiveTraits = true;
    EliteZeppelin.very_high_flyer = true;
    EliteZeppelin.disablePunchAttackAnimation = true;
    EliteZeppelin.hideOnMinimap = false;
    EliteZeppelin.defaultAttack = "bomberino";
    EliteZeppelin.isBoat = false;
    EliteZeppelin.dieOnBlocks = false;
    EliteZeppelin.ignoreBlocks = true;
    EliteZeppelin.moveFromBlock = false;
    EliteZeppelin.inspect_children = false;
    EliteZeppelin.inspect_experience = true;
    EliteZeppelin.canBeCitizen = true;
    EliteZeppelin.inspect_kills = true;
    EliteZeppelin.use_items = false;
    EliteZeppelin.oceanCreature = true;
    EliteZeppelin.take_items = false;
    EliteZeppelin.nameLocale = "EliteZeppelin";
    EliteZeppelin.nameTemplate = "Jet_Names";
    // EliteZeppelin.job = "attacker";
    EliteZeppelin.job = "attacker";
    EliteZeppelin.icon = "iconZeppelin";
    AssetManager.actor_library.CallMethod("addTrait", "Zeppelin");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("loadShadow", EliteZeppelin);
    EliteZeppelin.animation_idle = "idle_0,idle_1,idle_2,idle_3";
    EliteZeppelin.animation_walk = "walk_0,walk_1,walk_2,walk_3";
    EliteZeppelin.texture_path = "EliteZeppelin";
    // EliteZeppelin.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.addColorSet("heliColor");
    EliteZeppelin.color = Toolbox.makeColor("#33724D");
    AssetManager.actor_library.add(EliteZeppelin);
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
    Localization.addLocalization(EliteZeppelin.nameLocale, EliteZeppelin.nameLocale);

    var MIRVBomber = AssetManager.actor_library.clone("MIRVBomber", "_mob");
    // ActorAsset heli = new ActorAsset();
    // MIRVBomber.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    MIRVBomber.race = "human";
    MIRVBomber.kingdom = "ModernKingdom";
    MIRVBomber.base_stats[S.max_age] = 50f;
    MIRVBomber.base_stats[S.attack_speed] = 100f;
    MIRVBomber.base_stats[S.accuracy] = 100f;
    MIRVBomber.base_stats[S.health] = 1000f;
    MIRVBomber.base_stats[S.speed] = 50f;
    MIRVBomber.base_stats[S.scale] = 0.2f;
    MIRVBomber.base_stats[S.damage] = 30f;
    MIRVBomber.base_stats[S.range] = 10f;
    MIRVBomber.base_stats[S.knockback_reduction] = 300f;
    MIRVBomber.immune_to_injuries = true;
    MIRVBomber.inspect_stats = true;
    MIRVBomber.landCreature = true;
    MIRVBomber.inspect_home = true;
    MIRVBomber.disablePunchAttackAnimation = true;
    MIRVBomber.has_skin = false;
    MIRVBomber.hideOnMinimap = false;
    MIRVBomber.flying = true;
    MIRVBomber.can_edit_traits = true;
    // MIRVBomber.tech = "MIRVBombercopters";
    MIRVBomber.canReceiveTraits = true;
    MIRVBomber.very_high_flyer = true;
    MIRVBomber.defaultAttack = "bomberino";
    MIRVBomber.isBoat = false;
    MIRVBomber.dieOnBlocks = false;
        MIRVBomber.canFlip = false;
    MIRVBomber.ignoreBlocks = true;
    MIRVBomber.moveFromBlock = false;
    MIRVBomber.inspect_children = false;
    MIRVBomber.inspect_experience = true;
    MIRVBomber.canBeCitizen = true;
    MIRVBomber.inspect_kills = true;
    MIRVBomber.use_items = false;
    MIRVBomber.oceanCreature = true;
    MIRVBomber.take_items = false;
    MIRVBomber.nameLocale = "MIRVBomber";
    MIRVBomber.nameTemplate = "Jet_Names";
    // MIRVBomber.job = "attacker";
    MIRVBomber.job = "jet_job";
    MIRVBomber.icon = "iconMIRVBomber";
    AssetManager.actor_library.CallMethod("addTrait", "Jet");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("loadShadow", MIRVBomber);
    MIRVBomber.animation_idle = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7,idle_8,idle_9,idle_10,idle_11,idle_12,idle_13,idle_14,idle_15,idle_16,idle_17,idle_18,idle_19";
    MIRVBomber.animation_walk = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7,idle_8,idle_9,idle_10,idle_11,idle_12,idle_13,idle_14,idle_15,idle_16,idle_17,idle_18,idle_19";
    MIRVBomber.animation_swim = "walk_0,walk_1,walk_2,walk_3";
    MIRVBomber.texture_path = "MIRVBomber";
    // MIRVBomber.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.addColorSet("heliColor");
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
    MIRVBomber.color = Toolbox.makeColor("#33724D");
    AssetManager.actor_library.add(MIRVBomber);
    Localization.addLocalization(MIRVBomber.nameLocale, MIRVBomber.nameLocale);

           var americanbomberww = AssetManager.actor_library.clone("americanbomberww", "_mob");
    // ActorAsset heli = new ActorAsset();
    // americanbomberww.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    americanbomberww.race = "human";
    americanbomberww.kingdom = "ModernKingdom";
     americanbomberww.base_stats[S.max_age] = 50f;
    americanbomberww.base_stats[S.attack_speed] = 1000f;
    americanbomberww.base_stats[S.accuracy] = 30f;
    americanbomberww.base_stats[S.health] = 500f;
    americanbomberww.base_stats[S.speed] = 40f;
    americanbomberww.base_stats[S.scale] = 0.2f;
    americanbomberww.base_stats[S.damage] = 20f;
    americanbomberww.base_stats[S.range] = 1f;
    americanbomberww.base_stats[S.knockback_reduction] = 300f;
    americanbomberww.immune_to_injuries = true;
    americanbomberww.inspect_stats = true;
    americanbomberww.landCreature = true;
    americanbomberww.inspect_home = true;
    americanbomberww.disablePunchAttackAnimation = true;
    americanbomberww.has_skin = false;
    americanbomberww.hideOnMinimap = false;
    americanbomberww.flying = true;
    americanbomberww.can_edit_traits = true;
    // americanbomberww.tech = "americanbomberwwcopters";
    americanbomberww.canReceiveTraits = true;
    americanbomberww.very_high_flyer = true;
    americanbomberww.defaultAttack = "bomberino";
    americanbomberww.isBoat = false;
    americanbomberww.dieOnBlocks = false;
        americanbomberww.canFlip = false;
    americanbomberww.ignoreBlocks = true;
    americanbomberww.moveFromBlock = false;
    americanbomberww.inspect_children = false;
    americanbomberww.inspect_experience = true;
    americanbomberww.canBeCitizen = true;
    americanbomberww.inspect_kills = true;
    americanbomberww.use_items = false;
    americanbomberww.oceanCreature = true;
    americanbomberww.take_items = false;
    americanbomberww.nameLocale = "americanbomberww";
    americanbomberww.nameTemplate = "Jet_Names";
    // americanbomberww.job = "attacker";
    americanbomberww.job = "jet_job";
    americanbomberww.icon = "iconamericanbomberww";
    AssetManager.actor_library.CallMethod("addTrait", "Jet");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("loadShadow", americanbomberww);
    americanbomberww.animation_idle = "walk_0,walk_1,walk_2,walk_3,walk_4,walk_5,walk_6,walk_7,walk_8,walk_9,walk_10,walk_11,walk_12,walk_13,walk_14,walk_15";
    americanbomberww.animation_walk = "walk_0,walk_1,walk_2,walk_3,walk_4,walk_5,walk_6,walk_7,walk_8,walk_9,walk_10,walk_11,walk_12,walk_13,walk_14,walk_15";
    americanbomberww.texture_path = "americanbomberww";
    // americanbomberww.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.addColorSet("heliColor");
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
    americanbomberww.color = Toolbox.makeColor("#33724D");
    AssetManager.actor_library.add(americanbomberww);
    Localization.addLocalization(americanbomberww.nameLocale, americanbomberww.nameLocale);

      var EliteBomber = AssetManager.actor_library.clone("EliteBomber", "_mob");
    // ActorAsset heli = new ActorAsset();
    // EliteBomber.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    EliteBomber.race = "human";
    EliteBomber.kingdom = "ModernKingdom";
    EliteBomber.base_stats[S.max_age] = 50f;
    EliteBomber.base_stats[S.attack_speed] = 0f;
    EliteBomber.base_stats[S.accuracy] = 100f;
    EliteBomber.base_stats[S.health] = 5000f;
    EliteBomber.base_stats[S.speed] = 50f;
    EliteBomber.base_stats[S.scale] = 0.1f;
    EliteBomber.base_stats[S.damage] = 50f;
    EliteBomber.base_stats[S.range] = 20f;
    EliteBomber.base_stats[S.knockback_reduction] = 300f;
    EliteBomber.immune_to_injuries = true;
    EliteBomber.inspect_stats = true;
    EliteBomber.landCreature = true;
    EliteBomber.inspect_home = true;
    EliteBomber.disablePunchAttackAnimation = true;
    EliteBomber.has_skin = false;
    EliteBomber.hideOnMinimap = false;
    EliteBomber.flying = true;
    EliteBomber.can_edit_traits = true;
    // EliteBomber.tech = "MIRVBombercopters";
    EliteBomber.canReceiveTraits = true;
    EliteBomber.very_high_flyer = true;
    EliteBomber.defaultAttack = "missilelauncherlong";
    EliteBomber.isBoat = false;
    EliteBomber.dieOnBlocks = false;
    EliteBomber.ignoreBlocks = true;
    EliteBomber.moveFromBlock = false;
    EliteBomber.inspect_children = false;
    EliteBomber.inspect_experience = true;
    EliteBomber.canBeCitizen = true;
    EliteBomber.inspect_kills = true;
    EliteBomber.use_items = false;
    EliteBomber.oceanCreature = true;
    EliteBomber.take_items = false;
    EliteBomber.nameLocale = "EliteBomber";
    EliteBomber.nameTemplate = "Jet_Names";
    // EliteBomber.job = "attacker";
    EliteBomber.job = "jet_job";
    EliteBomber.icon = "iconMIRVBomber";
    AssetManager.actor_library.CallMethod("addTrait", "Jet");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
    AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
    AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("loadShadow", EliteBomber);
    EliteBomber.animation_idle = "idle_0,idle_1,idle_2,idle_3";
    EliteBomber.animation_walk = "walk_0,walk_1,walk_2,walk_3";
    EliteBomber.texture_path = "EliteBomber";
    // EliteBomber.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.addColorSet("heliColor");
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
    EliteBomber.color = Toolbox.makeColor("#33724D");
    AssetManager.actor_library.add(EliteBomber);
    Localization.addLocalization(EliteBomber.nameLocale, EliteBomber.nameLocale);

    var FighterJet = AssetManager.actor_library.clone("FighterJet", "_mob");
    // ActorAsset heli = new ActorAsset();
    // FighterJet.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    FighterJet.race = "human";
    FighterJet.kingdom = "ModernKingdom";
    FighterJet.base_stats[S.max_age] = 50f;
    FighterJet.base_stats[S.attack_speed] = 50f;
    FighterJet.base_stats[S.accuracy] = 0f;
    FighterJet.base_stats[S.health] = 600f;
    FighterJet.base_stats[S.speed] = 70f;
    FighterJet.base_stats[S.knockback_reduction] = 300f;
    FighterJet.base_stats[S.scale] = 0.2f;
    FighterJet.base_stats[S.damage] = 20;
    FighterJet.immune_to_injuries = true;
    FighterJet.inspect_stats = true;
    FighterJet.landCreature = true;
    FighterJet.inspect_home = true;
      FighterJet.disablePunchAttackAnimation = true;
    FighterJet.has_skin = false;
    FighterJet.flying = true;
    FighterJet.can_edit_traits = true;
    // FighterJet.tech = "FighterJetcopters";
    FighterJet.canReceiveTraits = true;
    FighterJet.very_high_flyer = true;
    FighterJet.defaultAttack = "JetRocket";
          FighterJet.canFlip = false;
    FighterJet.isBoat = false;
    FighterJet.dieOnBlocks = false;
    FighterJet.ignoreBlocks = true;
    FighterJet.moveFromBlock = false;
    FighterJet.inspect_children = false;
    FighterJet.inspect_experience = true;
    FighterJet.canBeCitizen = true;
    FighterJet.inspect_kills = true;
    FighterJet.hideOnMinimap = false;
    FighterJet.use_items = false;
    FighterJet.oceanCreature = true;
    FighterJet.take_items = false;
    FighterJet.nameLocale = "FighterJet";
    FighterJet.nameTemplate = "Jet_Names";
    // FighterJet.job = "attacker";
    FighterJet.job = "jet_job";
    FighterJet.icon = "iconFighterJet";
    // AssetManager.actor_library.CallMethod("addTrait", "Jet");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("loadShadow", FighterJet);
    FighterJet.animation_idle = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7,idle_8,idle_9";
    FighterJet.animation_walk = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7,idle_8,idle_9";
    FighterJet.animation_swim = "walk_0,walk_1,walk_2,walk_3";
    FighterJet.texture_path = "FighterJet";
    // FighterJet.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(FighterJet);
    AssetManager.actor_library.addColorSet("heliColor");
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
    FighterJet.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(FighterJet.nameLocale, FighterJet.nameLocale);

     var biplane = AssetManager.actor_library.clone("biplane", "_mob");
    // ActorAsset heli = new ActorAsset();
    // biplane.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    biplane.race = "human";
    biplane.kingdom = "ModernKingdom";
    biplane.base_stats[S.max_age] = 50f;
    biplane.base_stats[S.attack_speed] = 500f;
    biplane.base_stats[S.accuracy] = 0f;
    biplane.base_stats[S.health] = 200f;
    biplane.base_stats[S.speed] = 70f;
    biplane.base_stats[S.knockback_reduction] = 300f;
    biplane.base_stats[S.scale] = 0.2f;
    biplane.base_stats[S.damage] = 5;
    biplane.immune_to_injuries = true;
    biplane.inspect_stats = true;
    biplane.landCreature = true;
    biplane.inspect_home = true;
      biplane.disablePunchAttackAnimation = true;
    biplane.has_skin = false;
    biplane.flying = true;
    biplane.can_edit_traits = true;
    // biplane.tech = "biplanecopters";
    biplane.canReceiveTraits = true;
    biplane.very_high_flyer = true;
    biplane.defaultAttack = "machinegunery";
          biplane.canFlip = false;
    biplane.isBoat = false;
    biplane.dieOnBlocks = false;
    biplane.ignoreBlocks = true;
    biplane.moveFromBlock = false;
    biplane.inspect_children = false;
    biplane.inspect_experience = true;
    biplane.canBeCitizen = true;
    biplane.inspect_kills = true;
    biplane.hideOnMinimap = false;
    biplane.use_items = false;
    biplane.oceanCreature = true;
    biplane.take_items = false;
    biplane.nameLocale = "biplane";
    biplane.nameTemplate = "Jet_Names";
    // biplane.job = "attacker";
    biplane.job = "jet_job";
    biplane.icon = "iconbiplane";
    // AssetManager.actor_library.CallMethod("addTrait", "Jet");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("loadShadow", biplane);
    biplane.animation_idle = "walk_0,walk_1,walk_2,walk_3,walk_4,walk_5,walk_6,walk_7";
    biplane.animation_walk = "walk_0,walk_1,walk_2,walk_3,walk_4,walk_5,walk_6,walk_7";
    biplane.animation_swim = "walk_0,walk_1,walk_2,walk_3,walk_4,walk_5,walk_6,walk_7";
    biplane.texture_path = "biplane";
    // biplane.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(biplane);
    AssetManager.actor_library.addColorSet("heliColor");
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
    biplane.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(biplane.nameLocale, biplane.nameLocale);

  var F55FighterJet = AssetManager.actor_library.clone("F55FighterJet", "_mob");
    // ActorAsset heli = new ActorAsset();
    // F55FighterJet.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    F55FighterJet.race = "human";
    F55FighterJet.kingdom = "ModernKingdom";
    F55FighterJet.base_stats[S.max_age] = 50f;
    F55FighterJet.base_stats[S.attack_speed] = 100f;
    F55FighterJet.base_stats[S.accuracy] = 0f;
    F55FighterJet.base_stats[S.health] = 1200f;
    F55FighterJet.base_stats[S.speed] = 70f;
    F55FighterJet.base_stats[S.knockback_reduction] = 300f;
    F55FighterJet.base_stats[S.scale] = 0.2f;
    F55FighterJet.base_stats[S.damage] = 20;
         F55FighterJet.canFlip = false;
    F55FighterJet.immune_to_injuries = true;
    F55FighterJet.inspect_stats = true;
    F55FighterJet.landCreature = true;
    F55FighterJet.inspect_home = true;
      F55FighterJet.disablePunchAttackAnimation = true;
    F55FighterJet.has_skin = false;
    F55FighterJet.flying = true;
    F55FighterJet.can_edit_traits = true;
    // F55FighterJet.tech = "FighterJetcopters";
    F55FighterJet.canReceiveTraits = true;
    F55FighterJet.very_high_flyer = true;
    F55FighterJet.defaultAttack = "JetRocket";
    F55FighterJet.isBoat = false;
    F55FighterJet.dieOnBlocks = false;
    F55FighterJet.ignoreBlocks = true;
    F55FighterJet.moveFromBlock = false;
    F55FighterJet.inspect_children = false;
    F55FighterJet.inspect_experience = true;
    F55FighterJet.canBeCitizen = true;
    F55FighterJet.inspect_kills = true;
    F55FighterJet.hideOnMinimap = false;
    F55FighterJet.use_items = false;
    F55FighterJet.oceanCreature = true;
    F55FighterJet.take_items = false;
    F55FighterJet.nameLocale = "F55FighterJet";
    F55FighterJet.nameTemplate = "Jet_Names";
    // F55FighterJet.job = "attacker";
    F55FighterJet.job = "jet_job";
    F55FighterJet.icon = "iconFighterJet";
    // AssetManager.actor_library.CallMethod("addTrait", "Jet");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
    AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
    AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("loadShadow", F55FighterJet);
    F55FighterJet.animation_idle = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7,idle_8,idle_9";
    F55FighterJet.animation_walk = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7,idle_8,idle_9";
    F55FighterJet.texture_path = "F55FighterJet";
    // F55FighterJet.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(F55FighterJet);
    AssetManager.actor_library.addColorSet("heliColor");
    AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
    F55FighterJet.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(F55FighterJet.nameLocale, F55FighterJet.nameLocale);

        var FighterJet1 = AssetManager.actor_library.clone("FighterJet1", "_mob");
    // ActorAsset heli = new ActorAsset();
    // FighterJet1.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    FighterJet1.race = "human";
    FighterJet1.kingdom = "ModernKingdom";
     FighterJet1.base_stats[S.max_age] = 1f;
    FighterJet1.base_stats[S.attack_speed] = 50f;
    FighterJet1.base_stats[S.accuracy] = 0f;
    FighterJet1.base_stats[S.health] = 50f;
    FighterJet1.base_stats[S.speed] = 70f;
    FighterJet1.base_stats[S.knockback_reduction] = 300f;
    FighterJet1.base_stats[S.scale] = 0.2f;
    FighterJet1.base_stats[S.damage] = 20;
    FighterJet1.immune_to_injuries = true;
    FighterJet1.inspect_stats = true;
    FighterJet1.landCreature = true;
    FighterJet1.inspect_home = true;
      FighterJet1.disablePunchAttackAnimation = true;
    FighterJet1.has_skin = false;
    FighterJet1.flying = true;
    FighterJet1.can_edit_traits = true;
    // FighterJet1.tech = "FighterJet1copters";
    FighterJet1.canReceiveTraits = true;
    FighterJet1.very_high_flyer = true;
    FighterJet1.defaultAttack = "JetRocket";
          FighterJet1.canFlip = false;
    FighterJet1.isBoat = false;
    FighterJet1.dieOnBlocks = false;
    FighterJet1.ignoreBlocks = true;
    FighterJet1.moveFromBlock = false;
    FighterJet1.inspect_children = false;
    FighterJet1.inspect_experience = true;
    FighterJet1.canBeCitizen = true;
    FighterJet1.inspect_kills = true;
    FighterJet1.hideOnMinimap = false;
    FighterJet1.use_items = false;
    FighterJet1.oceanCreature = true;
    FighterJet1.take_items = false;
    FighterJet1.nameLocale = "FighterJet1";
    FighterJet1.nameTemplate = "Jet_Names";
    // FighterJet1.job = "attacker";
    FighterJet1.job = "jet_job";
    FighterJet1.icon = "iconFighterJet1";
    // AssetManager.actor_library.CallMethod("addTrait", "Jet");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
            AssetManager.actor_library.CallMethod("addTrait", "death_mark");
    AssetManager.actor_library.CallMethod("loadShadow", FighterJet1);
    FighterJet1.animation_idle = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7,idle_8,idle_9";
    FighterJet1.animation_walk = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7,idle_8,idle_9";
    FighterJet1.animation_swim = "walk_0,walk_1,walk_2,walk_3";
    FighterJet1.texture_path = "FighterJet";
    // FighterJet1.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(FighterJet1);
    AssetManager.actor_library.addColorSet("heliColor");
    FighterJet1.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(FighterJet1.nameLocale, FighterJet1.nameLocale);


  var F55FighterJet1 = AssetManager.actor_library.clone("F55FighterJet1", "_mob");
    // ActorAsset heli = new ActorAsset();
    // F55FighterJet1.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    F55FighterJet1.race = "human";
    F55FighterJet1.kingdom = "ModernKingdom";
    F55FighterJet1.base_stats[S.max_age] = 1f;
    F55FighterJet1.base_stats[S.attack_speed] = 100f;
    F55FighterJet1.base_stats[S.accuracy] = 0f;
    F55FighterJet1.base_stats[S.health] = 100f;
    F55FighterJet1.base_stats[S.speed] = 70f;
    F55FighterJet1.base_stats[S.knockback_reduction] = 300f;
    F55FighterJet1.base_stats[S.scale] = 0.2f;
    F55FighterJet1.base_stats[S.damage] = 20;
         F55FighterJet1.canFlip = false;
    F55FighterJet1.immune_to_injuries = true;
    F55FighterJet1.inspect_stats = true;
    F55FighterJet1.landCreature = true;
    F55FighterJet1.inspect_home = true;
      F55FighterJet1.disablePunchAttackAnimation = true;
    F55FighterJet1.has_skin = false;
    F55FighterJet1.flying = true;
    F55FighterJet1.can_edit_traits = true;
    // F55FighterJet1.tech = "FighterJet1copters";
    F55FighterJet1.canReceiveTraits = true;
    F55FighterJet1.very_high_flyer = true;
    F55FighterJet1.defaultAttack = "JetRocket";
    F55FighterJet1.isBoat = false;
    F55FighterJet1.dieOnBlocks = false;
    F55FighterJet1.ignoreBlocks = true;
    F55FighterJet1.moveFromBlock = false;
    F55FighterJet1.inspect_children = false;
    F55FighterJet1.inspect_experience = true;
    F55FighterJet1.canBeCitizen = true;
    F55FighterJet1.inspect_kills = true;
    F55FighterJet1.hideOnMinimap = false;
    F55FighterJet1.use_items = false;
    F55FighterJet1.oceanCreature = true;
    F55FighterJet1.take_items = false;
    F55FighterJet1.nameLocale = "F55FighterJet1";
    F55FighterJet1.nameTemplate = "Jet_Names";
    // F55FighterJet1.job = "attacker";
    F55FighterJet1.job = "jet_job";
    F55FighterJet1.icon = "iconFighterJet1";
    // AssetManager.actor_library.CallMethod("addTrait", "Jet");
    AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
    AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
    AssetManager.actor_library.CallMethod("addTrait", "freeze_proof");
    AssetManager.actor_library.CallMethod("addTrait", "death_mark");
    AssetManager.actor_library.CallMethod("loadShadow", F55FighterJet1);
    F55FighterJet1.animation_idle = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7,idle_8,idle_9";
    F55FighterJet1.animation_walk = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7,idle_8,idle_9";
    F55FighterJet1.texture_path = "F55FighterJet";
    // F55FighterJet1.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(F55FighterJet1);
    AssetManager.actor_library.addColorSet("heliColor");
    F55FighterJet1.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(F55FighterJet1.nameLocale, F55FighterJet1.nameLocale);

    var JetRaceKingdom = new KingdomAsset();
    JetRaceKingdom.id = "JetRaceKingdom";
    JetRaceKingdom.nomads = true;
    JetRaceKingdom.mobs = true;
    JetRaceKingdom.civ = true;
    JetRaceKingdom.addTag("JetRaceKingdom");
    JetRaceKingdom.addFriendlyTag("human");
    JetRaceKingdom.addFriendlyTag("dwarf");
    JetRaceKingdom.addFriendlyTag("elf");
    JetRaceKingdom.addFriendlyTag("orc");

    AssetManager.kingdoms.add(JetRaceKingdom);
    World.world.kingdoms.CallMethod("newHiddenKingdom", JetRaceKingdom);
  }
}
}
