//========= MODERNBOX 2.1.0.1 ============//
//
// Made by Tuxxego
//
//=============================================================================//
using System;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using NCMS;
using NCMS.Utils;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using ReflectionUtility;
using HarmonyLib;

namespace M2 {
class Aircraft : MonoBehaviour {

  public static void init() { loadAssets(); }

  private static void loadAssets() {

    var Heli = AssetManager.actor_library.clone("Heli", "_mob");
    // ActorAsset heli = new ActorAsset();
    // Heli.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    Heli.race = "human";
    Heli.kingdom = "ModernKingdom";
    Heli.base_stats[S.attack_speed] = 100f;
    Heli.base_stats[S.accuracy] = 100f;
    Heli.base_stats[S.health] = 200f;
    Heli.base_stats[S.speed] = 200f;
    Heli.base_stats[S.scale] = 0.1f;
    Heli.base_stats[S.damage] = 0f;
    Heli.base_stats[S.knockback_reduction] = 300f;
    Heli.drawBoatMark_big = true;
    Heli.skipFightLogic = false;
    Heli.inspect_stats = true;
    Heli.landCreature = true;
    Heli.inspect_home = true;
    Heli.drawBoatMark = true;
    Heli.flying = true;
    Heli.can_edit_traits = false;
    // Heli.tech = "Helicopters";
    Heli.canReceiveTraits = false;
    Heli.very_high_flyer = true;
    Heli.defaultAttack = "heliRocket";
    Heli.isBoat = false;
    Heli.dieOnBlocks = false;
    Heli.ignoreBlocks = true;
    Heli.disablePunchAttackAnimation = true;
    Heli.moveFromBlock = false;
    Heli.inspect_children = false;
    Heli.inspect_experience = true;
    Heli.canBeCitizen = true;
    Heli.inspect_kills = true;
    Heli.hideOnMinimap = false;
    Heli.use_items = false;
    Heli.oceanCreature = true;
    Heli.take_items = false;
    Heli.nameLocale = "Heli";
    Heli.nameTemplate = "Jet_Names";
    // Heli.job = "attacker";
    Heli.job = "attacker";
    Heli.icon = "iconHeli";
    AssetManager.actor_library.CallMethod("addTrait", "Helicopter");
    AssetManager.actor_library.CallMethod("addTrait", "immortal");
    AssetManager.actor_library.CallMethod("loadShadow", Heli);
    Heli.animation_idle = "walk_0,walk_1,walk_2,walk_3,walk_4,walk_5";
    Heli.animation_walk = "walk_0,walk_1,walk_2,walk_3,walk_4,walk_5";
    Heli.animation_swim = "walk_0,walk_1,walk_2,walk_3,walk_4,walk_5";
    Heli.texture_path = "Heli";
    // Heli.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(Heli);
    AssetManager.actor_library.CallMethod("addTrait", "Vehicle");
    AssetManager.actor_library.addColorSet("heliColor");
    Heli.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(Heli.nameLocale, Heli.nameLocale);

    var Gunship = AssetManager.actor_library.clone("Gunship", "_mob");
    // ActorAsset heli = new ActorAsset();
    // Gunship.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    Gunship.race = "human";
    Gunship.kingdom = "ModernKingdom";
    Gunship.base_stats[S.attack_speed] = 100f;
    Gunship.base_stats[S.accuracy] = 100f;
    Gunship.base_stats[S.health] = 200f;
    Gunship.base_stats[S.speed] = 200f;
    Gunship.base_stats[S.scale] = 0.2f;
    Gunship.base_stats[S.damage] = 93;
    Gunship.base_stats[S.knockback_reduction] = 300f;
    Gunship.drawBoatMark_big = true;
    Gunship.skipFightLogic = false;
    Gunship.inspect_stats = true;
    Gunship.landCreature = true;
    Gunship.inspect_home = true;
    Gunship.drawBoatMark = true;
    Gunship.flying = true;
    Gunship.can_edit_traits = false;
    // Gunship.tech = "Gunshipcopters";
    Gunship.canReceiveTraits = false;
    Gunship.very_high_flyer = true;
    Gunship.defaultAttack = "GunshipCannon";
    Gunship.isBoat = false;
    Gunship.dieOnBlocks = false;
    Gunship.ignoreBlocks = true;
    Gunship.moveFromBlock = false;
    Gunship.inspect_children = false;
    Gunship.inspect_experience = true;
    Gunship.canBeCitizen = true;
    Gunship.inspect_kills = true;
    Gunship.hideOnMinimap = false;
        Gunship.disablePunchAttackAnimation = true;
    Gunship.use_items = false;
    Gunship.oceanCreature = true;
    Gunship.take_items = false;
    Gunship.nameLocale = "Gunship";
    Gunship.nameTemplate = "Jet_Names";
    // Gunship.job = "attacker";
    Gunship.job = "attacker";
    Gunship.icon = "iconGunship";
    // AssetManager.actor_library.CallMethod("addTrait", "Gunshipcopter");
    AssetManager.actor_library.CallMethod("addTrait", "immortal");
    AssetManager.actor_library.CallMethod("loadShadow", Gunship);
    Gunship.animation_idle = "walk_0,walk_1,walk_2,walk_3,walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3";
    Gunship.animation_walk = "walk_0,walk_1,walk_2,walk_3,walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3walk_0,walk_1,walk_2,walk_3";
    Gunship.animation_swim = "walk_1,walk_2";
    Gunship.texture_path = "Gunship";
    // Gunship.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(Gunship);
    AssetManager.actor_library.CallMethod("addTrait", "Vehicle");
    AssetManager.actor_library.addColorSet("heliColor");
    Gunship.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(Gunship.nameLocale, Gunship.nameLocale);

    var Drone = AssetManager.actor_library.clone("Drone", "_mob");
    // ActorAsset heli = new ActorAsset();
    // Drone.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    Drone.race = "human";
    Drone.kingdom = "ModernKingdom";
    Drone.base_stats[S.attack_speed] = 100f;
    Drone.base_stats[S.accuracy] = 100f;
    Drone.base_stats[S.health] = 15f;
    Drone.base_stats[S.speed] = 30f;
    Drone.base_stats[S.damage] = 93;
    Drone.base_stats[S.knockback_reduction] = 300f;
    Drone.drawBoatMark_big = true;
    Drone.skipFightLogic = false;
    Drone.inspect_stats = true;
    Drone.landCreature = true;
    Drone.inspect_home = true;
    Drone.drawBoatMark = true;
    Drone.flying = true;
    Drone.can_edit_traits = false;
    // Drone.tech = "Dronecopters";
    Drone.canReceiveTraits = false;
    Drone.very_high_flyer = true;
    Drone.defaultAttack = "Mp5";
    Drone.isBoat = false;
    // Drone.moveFromBlock = false;
    Drone.inspect_children = false;
    Drone.inspect_experience = true;
    Drone.canBeCitizen = true;
    Drone.inspect_kills = true;
    Drone.hideOnMinimap = false;
    Drone.use_items = false;
    Drone.oceanCreature = true;
    Drone.take_items = false;
    Drone.nameLocale = "Drone";
    Drone.nameTemplate = "Jet_Names";
    // Drone.job = "attacker";
    Drone.job = "attacker";
    Drone.icon = "iconDrone";
    // AssetManager.actor_library.CallMethod("addTrait", "Dronecopter");
    AssetManager.actor_library.CallMethod("addTrait", "immortal");
    AssetManager.actor_library.CallMethod("loadShadow", Drone);
    Drone.animation_idle = "walk_0,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2";
    Drone.animation_walk = "walk_0,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2,walk_1,walk_2";
    Drone.animation_swim = "walk_1,walk_2";
    Drone.texture_path = "Drone";
    // Drone.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(Drone);
    AssetManager.actor_library.addColorSet("heliColor");
    Drone.color = Toolbox.makeColor("#33724D");
    AssetManager.actor_library.CallMethod("addTrait", "Vehicle");
    Localization.addLocalization(Drone.nameLocale, Drone.nameLocale);

    ColorSetAsset heliColor = new ColorSetAsset();
    heliColor.id = "heliColor";
    heliColor.shades_from = "#FFC984";
    heliColor.shades_to = "#543E2C";
    heliColor.is_default = true;
    AssetManager.skin_color_set_library.add(heliColor);

    var Zeppelin = AssetManager.actor_library.clone("Zeppelin", "_mob");
    // ActorAsset heli = new ActorAsset();
    // Zeppelin.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    Zeppelin.race = "human";
    Zeppelin.kingdom = "ModernKingdom";
    Zeppelin.base_stats[S.attack_speed] = 100f;
    Zeppelin.base_stats[S.accuracy] = 100f;
    Zeppelin.base_stats[S.health] = 1000f;
    Zeppelin.base_stats[S.speed] = 50f;
    Zeppelin.base_stats[S.scale] = 0.5f;
    Zeppelin.base_stats[S.damage] = 93;
    Zeppelin.base_stats[S.knockback_reduction] = 300f;
    Zeppelin.drawBoatMark_big = true;
    Zeppelin.skipFightLogic = false;
    Zeppelin.inspect_stats = true;
    Zeppelin.landCreature = true;
    Zeppelin.inspect_home = true;
    Zeppelin.drawBoatMark = true;
    Zeppelin.flying = true;
    Zeppelin.can_edit_traits = false;
    // Zeppelin.tech = "Zeppelincopters";
    Zeppelin.canReceiveTraits = false;
    Zeppelin.very_high_flyer = true;
    Zeppelin.disablePunchAttackAnimation = true;
    Zeppelin.hideOnMinimap = false;
    Zeppelin.defaultAttack = "bomberino";
    Zeppelin.isBoat = false;
    Zeppelin.dieOnBlocks = false;
    Zeppelin.ignoreBlocks = true;
    Zeppelin.moveFromBlock = false;
    Zeppelin.inspect_children = false;
    Zeppelin.inspect_experience = true;
    Zeppelin.canBeCitizen = true;
    Zeppelin.inspect_kills = true;
    Zeppelin.use_items = false;
    Zeppelin.oceanCreature = true;
    Zeppelin.take_items = false;
    Zeppelin.nameLocale = "Zeppelin";
    Zeppelin.nameTemplate = "Jet_Names";
    // Zeppelin.job = "attacker";
    Zeppelin.job = "attacker";
    Zeppelin.icon = "iconZeppelin";
    AssetManager.actor_library.CallMethod("addTrait", "Zeppelin");
    AssetManager.actor_library.CallMethod("addTrait", "immortal");
    AssetManager.actor_library.CallMethod("loadShadow", Zeppelin);
    Zeppelin.animation_idle = "walk_0";
    Zeppelin.animation_walk = "walk_0,walk_1,walk_2";
    Zeppelin.animation_swim = "walk_0,walk_1,walk_2";
    Zeppelin.texture_path = "Zeppelin";
    // Zeppelin.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.addColorSet("heliColor");
    Zeppelin.color = Toolbox.makeColor("#33724D");
    AssetManager.actor_library.add(Zeppelin);
    AssetManager.actor_library.CallMethod("addTrait", "Vehicle");
    Localization.addLocalization(Zeppelin.nameLocale, Zeppelin.nameLocale);

    var MIRVBomber = AssetManager.actor_library.clone("MIRVBomber", "_mob");
    // ActorAsset heli = new ActorAsset();
    // MIRVBomber.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    MIRVBomber.race = "human";
    MIRVBomber.kingdom = "ModernKingdom";
    MIRVBomber.base_stats[S.attack_speed] = 100f;
    MIRVBomber.base_stats[S.accuracy] = 100f;
    MIRVBomber.base_stats[S.health] = 1000f;
    MIRVBomber.base_stats[S.speed] = 500f;
    MIRVBomber.base_stats[S.scale] = 0.4f;
    MIRVBomber.base_stats[S.damage] = 93f;
    MIRVBomber.base_stats[S.range] = 10f;
    MIRVBomber.base_stats[S.knockback_reduction] = 300f;
    MIRVBomber.drawBoatMark_big = true;
    MIRVBomber.skipFightLogic = false;
    MIRVBomber.inspect_stats = true;
    MIRVBomber.landCreature = true;
    MIRVBomber.inspect_home = true;
          MIRVBomber.disablePunchAttackAnimation = true;
    MIRVBomber.drawBoatMark = true;
    MIRVBomber.hideOnMinimap = false;
    MIRVBomber.flying = true;
    MIRVBomber.can_edit_traits = false;
    // MIRVBomber.tech = "MIRVBombercopters";
    MIRVBomber.canReceiveTraits = false;
    MIRVBomber.very_high_flyer = true;
    MIRVBomber.defaultAttack = "MIRVBomb";
    MIRVBomber.isBoat = false;
    MIRVBomber.dieOnBlocks = false;
    MIRVBomber.ignoreBlocks = true;
    MIRVBomber.moveFromBlock = false;
    MIRVBomber.inspect_children = false;
    MIRVBomber.inspect_experience = true;
    MIRVBomber.canBeCitizen = true;
    MIRVBomber.inspect_kills = true;
    MIRVBomber.use_items = false;
    MIRVBomber.oceanCreature = true;
    MIRVBomber.take_items = false;
    MIRVBomber.nameLocale = "MIRVBomber";
    MIRVBomber.nameTemplate = "Jet_Names";
    // MIRVBomber.job = "attacker";
    MIRVBomber.job = "jet_job";
    MIRVBomber.icon = "iconMIRVBomber";
    AssetManager.actor_library.CallMethod("addTrait", "Jet");
    AssetManager.actor_library.CallMethod("addTrait", "immortal");
    AssetManager.actor_library.CallMethod("loadShadow", MIRVBomber);
    MIRVBomber.animation_idle = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7,idle_8,idle_9,idle_10,idle_11,idle_12,idle_13,idle_14,idle_15,idle_16,idle_17,idle_18,idle_19,idle_20,idle_21";
    MIRVBomber.animation_walk = "walk_0,walk_1,walk_2,walk_3";
    MIRVBomber.animation_swim = "walk_0,walk_1,walk_2,walk_3";
    MIRVBomber.texture_path = "MIRVBomber";
    // MIRVBomber.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.addColorSet("heliColor");
    AssetManager.actor_library.CallMethod("addTrait", "Vehicle");
    MIRVBomber.color = Toolbox.makeColor("#33724D");
    AssetManager.actor_library.add(MIRVBomber);
    Localization.addLocalization(MIRVBomber.nameLocale, MIRVBomber.nameLocale);



    var FighterJet = AssetManager.actor_library.clone("FighterJet", "_mob");
    // ActorAsset heli = new ActorAsset();
    // FighterJet.get_override_sprite = AssetManager.actor_library.get("Jet").get_override_sprite;
    FighterJet.race = "human";
    FighterJet.kingdom = "ModernKingdom";
    FighterJet.base_stats[S.attack_speed] = 0f;
    FighterJet.base_stats[S.accuracy] = 0f;
    FighterJet.base_stats[S.health] = 600f;
    FighterJet.base_stats[S.speed] = 800f;
    FighterJet.base_stats[S.knockback_reduction] = 300f;
    FighterJet.base_stats[S.scale] = 0.3f;
    FighterJet.base_stats[S.damage] = 0;
    FighterJet.drawBoatMark_big = true;
    FighterJet.skipFightLogic = false;
    FighterJet.inspect_stats = true;
    FighterJet.landCreature = true;
    FighterJet.inspect_home = true;
      FighterJet.disablePunchAttackAnimation = true;
    FighterJet.drawBoatMark = true;
    FighterJet.flying = true;
    FighterJet.can_edit_traits = false;
    // FighterJet.tech = "FighterJetcopters";
    FighterJet.canReceiveTraits = false;
    FighterJet.very_high_flyer = true;
    FighterJet.defaultAttack = "JetRocket";
    FighterJet.isBoat = false;
    FighterJet.dieOnBlocks = false;
    FighterJet.ignoreBlocks = true;
    FighterJet.moveFromBlock = false;
    FighterJet.inspect_children = false;
    FighterJet.inspect_experience = true;
    FighterJet.canBeCitizen = true;
    FighterJet.inspect_kills = true;
    FighterJet.hideOnMinimap = false;
    FighterJet.use_items = false;
    FighterJet.oceanCreature = true;
    FighterJet.take_items = false;
    FighterJet.nameLocale = "FighterJet";
    FighterJet.nameTemplate = "Jet_Names";
    // FighterJet.job = "attacker";
    FighterJet.job = "jet_job";
    FighterJet.icon = "iconFighterJet";
    // AssetManager.actor_library.CallMethod("addTrait", "Jet");
    AssetManager.actor_library.CallMethod("addTrait", "immortal");
    AssetManager.actor_library.CallMethod("loadShadow", FighterJet);
    FighterJet.animation_idle = "idle_0,idle_1,idle_2,idle_3,idle_4,idle_5,idle_6,idle_7,idle_8,idle_9";
    FighterJet.animation_walk = "walk_0,walk_1,walk_2,walk_3";
    FighterJet.animation_swim = "walk_0,walk_1,walk_2,walk_3";
    FighterJet.texture_path = "FighterJet";
    // FighterJet.actorSize = ActorSize.S17_Dragon;
    AssetManager.actor_library.add(FighterJet);
    AssetManager.actor_library.addColorSet("heliColor");
    AssetManager.actor_library.CallMethod("addTrait", "Vehicle");
    FighterJet.color = Toolbox.makeColor("#33724D");
    Localization.addLocalization(FighterJet.nameLocale, FighterJet.nameLocale);


    var JetRaceKingdom = new KingdomAsset();
    JetRaceKingdom.id = "JetRaceKingdom";
    JetRaceKingdom.nomads = true;
    JetRaceKingdom.mobs = true;
    JetRaceKingdom.civ = true;
    JetRaceKingdom.addTag("JetRaceKingdom");
    JetRaceKingdom.addFriendlyTag("human");
    JetRaceKingdom.addFriendlyTag("dwarf");
    JetRaceKingdom.addFriendlyTag("elf");
    JetRaceKingdom.addFriendlyTag("orc");

    AssetManager.kingdoms.add(JetRaceKingdom);
    World.world.kingdoms.CallMethod("newHiddenKingdom", JetRaceKingdom);
  }
}
}
