//========= MODERNBOX 2.1.0.1 ============//
//
// Made by Tuxxego
//
//=============================================================================//
using System;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using NCMS;
using NCMS.Utils;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using ReflectionUtility;
using HarmonyLib;

namespace M2
{
    class GoliathVehicles : MonoBehaviour
    {
		

        public static void init()
        {
            loadAssets();

        }

        private static void loadAssets()
        {

			var P9000 = AssetManager.actor_library.clone("P9000","_mob");
			//ActorAsset heli = new ActorAsset();
           // P9000.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			P9000.race = "human";
			P9000.kingdom = "ModernKingdom";
		    P9000.action_death = (WorldAction)Delegate.Combine(P9000.action_death, new WorldAction(startDeathexplosionBig));
			P9000.base_stats[S.max_age] = 50f;
            P9000.base_stats[S.health] = 5000f;
            P9000.base_stats[S.speed] = 70f;
            P9000.base_stats[S.armor] = 40f;
            P9000.base_stats[S.damage] = 100f;
            P9000.base_stats[S.scale] = 0.2f;
            P9000.base_stats[S.attack_speed] = 0;
			P9000.disablePunchAttackAnimation = true;
			P9000.base_stats[S.range] = 50f;
			P9000.base_stats[S.knockback_reduction] = 300f;
            P9000.drawBoatMark_big = true;
			P9000.has_skin = false;
			P9000.immune_to_injuries = true;
            P9000.inspect_stats = true;
			P9000.landCreature = true;
			P9000.inspect_home = true;
			P9000.hideOnMinimap = false;
            P9000.drawBoatMark = true;
			P9000.can_edit_traits = true;
			P9000.canReceiveTraits = true;
			P9000.flying = false;
			//P9000.tech = "P9000s";
			P9000.very_high_flyer = false;
			P9000.defaultAttack = "bigplasmabomb";
            P9000.isBoat = false;
			P9000.dieOnBlocks = true;
			P9000.ignoreBlocks = false;
			//P9000.moveFromBlock = false;
			P9000.procreate = false;
		    P9000.inspect_children = false;
            P9000.inspect_experience = true;
			P9000.canBeCitizen = true;
            P9000.inspect_kills = true;
            P9000.use_items = false;
			P9000.oceanCreature = false;
            P9000.take_items = false;
            P9000.nameLocale = "P9000";
            P9000.nameTemplate = "Jet_Names";
			P9000.job = "attacker";
            P9000.icon = "iconP9000";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "P9000");
			AssetManager.actor_library.CallMethod("addTrait", "bubble_defense");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", P9000);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            P9000.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			P9000.animation_idle = "walk_0,walk_1,walk_2,walk_3";
            P9000.animation_swim = "walk_0,walk_1,walk_2,walk_3";
            P9000.texture_path = "P9000";
			AssetManager.actor_library.addColorSet("heliColor");
			P9000.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(P9000);
			Localization.addLocalization(P9000.nameLocale, P9000.nameLocale);

						var MA9000 = AssetManager.actor_library.clone("MA9000","_mob");
			//ActorAsset heli = new ActorAsset();
           // MA9000.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			MA9000.race = "human";
			MA9000.kingdom = "ModernKingdom";
		    MA9000.action_death = (WorldAction)Delegate.Combine(MA9000.action_death, new WorldAction(startDeathexplosionBig));
			MA9000.base_stats[S.max_age] = 50f;
            MA9000.base_stats[S.health] = 10000f;
            MA9000.base_stats[S.speed] = 40f;
            MA9000.base_stats[S.armor] = 40f;
            MA9000.base_stats[S.damage] = 1000f;
            MA9000.base_stats[S.scale] = 0.2f;
            MA9000.base_stats[S.attack_speed] = 0;
			MA9000.disablePunchAttackAnimation = true;
			MA9000.base_stats[S.range] = 200f;
			MA9000.base_stats[S.knockback_reduction] = 300f;
            MA9000.drawBoatMark_big = true;
			MA9000.has_skin = false;
			MA9000.immune_to_injuries = true;
            MA9000.inspect_stats = true;
			MA9000.landCreature = true;
			MA9000.inspect_home = true;
			MA9000.hideOnMinimap = false;
            MA9000.drawBoatMark = true;
			MA9000.can_edit_traits = true;
			MA9000.canReceiveTraits = true;
			MA9000.flying = false;
			//MA9000.tech = "MA9000s";
			MA9000.very_high_flyer = false;
			MA9000.defaultAttack = "thunderartillery";
            MA9000.isBoat = false;
			MA9000.dieOnBlocks = true;
			MA9000.ignoreBlocks = false;
			//MA9000.moveFromBlock = false;
			MA9000.procreate = false;
		    MA9000.inspect_children = false;
            MA9000.inspect_experience = true;
			MA9000.canBeCitizen = true;
            MA9000.inspect_kills = true;
            MA9000.use_items = false;
			MA9000.oceanCreature = false;
            MA9000.take_items = false;
            MA9000.nameLocale = "MA9000";
            MA9000.nameTemplate = "Jet_Names";
			MA9000.job = "attacker";
            MA9000.icon = "iconMA9000";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "MA9000");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", MA9000);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            MA9000.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			MA9000.animation_idle = "idle_0";
            MA9000.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            MA9000.texture_path = "MA9000";
			AssetManager.actor_library.addColorSet("heliColor");
			MA9000.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(MA9000);
			Localization.addLocalization(MA9000.nameLocale, MA9000.nameLocale);

						var AT9000 = AssetManager.actor_library.clone("AT9000","_mob");
			//ActorAsset heli = new ActorAsset();
           // AT9000.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			AT9000.race = "human";
			AT9000.kingdom = "ModernKingdom";
		    AT9000.action_death = (WorldAction)Delegate.Combine(AT9000.action_death, new WorldAction(startDeathexplosionBig));
			AT9000.base_stats[S.max_age] = 50f;
            AT9000.base_stats[S.health] = 10000f;
            AT9000.base_stats[S.speed] = 40f;
            AT9000.base_stats[S.armor] = 70f;
            AT9000.base_stats[S.damage] = 1000f;
            AT9000.base_stats[S.scale] = 0.2f;
            AT9000.base_stats[S.attack_speed] = 0;
			AT9000.disablePunchAttackAnimation = true;
			AT9000.base_stats[S.range] = 200f;
			AT9000.base_stats[S.knockback_reduction] = 300f;
            AT9000.drawBoatMark_big = true;
			AT9000.has_skin = false;
			AT9000.immune_to_injuries = true;
            AT9000.inspect_stats = true;
			AT9000.landCreature = true;
			AT9000.inspect_home = true;
			AT9000.hideOnMinimap = false;
            AT9000.drawBoatMark = true;
			AT9000.can_edit_traits = true;
			AT9000.canReceiveTraits = true;
			AT9000.flying = false;
			//AT9000.tech = "AT9000s";
			AT9000.very_high_flyer = false;
			AT9000.defaultAttack = "bigplasmabomb";
            AT9000.isBoat = false;
			AT9000.dieOnBlocks = true;
			AT9000.ignoreBlocks = false;
			//AT9000.moveFromBlock = false;
			AT9000.procreate = false;
		    AT9000.inspect_children = false;
            AT9000.inspect_experience = true;
			AT9000.canBeCitizen = true;
            AT9000.inspect_kills = true;
            AT9000.use_items = false;
			AT9000.oceanCreature = false;
            AT9000.take_items = false;
            AT9000.nameLocale = "AT9000";
            AT9000.nameTemplate = "Jet_Names";
			AT9000.job = "attacker";
            AT9000.icon = "iconAT9000";
            AT9000.skipFightLogic = true;
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "AT9000");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("addTrait", "SupportRole");
			AssetManager.actor_library.CallMethod("loadShadow", AT9000);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AT9000.animation_walk = "walk_0,walk_1,walk_2,walk_3,walk_4,walk_5,walk_6,walk_7";
			AT9000.animation_idle = "walk_0";
            AT9000.animation_swim = "swim_0,swim_1,swim_2,swim_3,swim_4,swim_5,swim_6,swim_7";
            AT9000.texture_path = "AT9000";
			AssetManager.actor_library.addColorSet("heliColor");
			AT9000.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(AT9000);
			Localization.addLocalization(AT9000.nameLocale, AT9000.nameLocale);

			var EliteP9000 = AssetManager.actor_library.clone("EliteP9000","_mob");
			//ActorAsset heli = new ActorAsset();
           // EliteP9000.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			EliteP9000.race = "human";
			EliteP9000.kingdom = "ModernKingdom";
			EliteP9000.base_stats[S.max_age] = 50f;
            EliteP9000.base_stats[S.health] = 10000f;
            EliteP9000.base_stats[S.speed] = 70f;
            EliteP9000.base_stats[S.armor] = 40f;
            EliteP9000.base_stats[S.damage] = 200f;
            EliteP9000.base_stats[S.scale] = 0.2f;
            EliteP9000.base_stats[S.attack_speed] = 0;
            EliteP9000.disablePunchAttackAnimation = true;
			EliteP9000.base_stats[S.range] = 80f;
			EliteP9000.base_stats[S.knockback_reduction] = 300f;
            EliteP9000.drawBoatMark_big = true;
            EliteP9000.inspect_stats = true;
			EliteP9000.landCreature = true;
			EliteP9000.inspect_home = true;
			EliteP9000.has_skin = false;
			EliteP9000.immune_to_injuries = true;
			EliteP9000.hideOnMinimap = false;
            EliteP9000.drawBoatMark = true;
			EliteP9000.can_edit_traits = true;
			EliteP9000.canReceiveTraits = true;
			EliteP9000.flying = false;
			//EliteP9000.tech = "P9000s";
			EliteP9000.very_high_flyer = false;
			EliteP9000.defaultAttack = "bigplasmabomb";
            EliteP9000.isBoat = false;
			EliteP9000.dieOnBlocks = true;
			EliteP9000.ignoreBlocks = false;
			//EliteP9000.moveFromBlock = false;
			EliteP9000.procreate = false;
		    EliteP9000.inspect_children = false;
            EliteP9000.inspect_experience = true;
			EliteP9000.canBeCitizen = true;
            EliteP9000.inspect_kills = true;
            EliteP9000.use_items = false;
			EliteP9000.oceanCreature = false;
            EliteP9000.take_items = false;
            EliteP9000.nameLocale = "EliteP9000";
            EliteP9000.nameTemplate = "Jet_Names";
			EliteP9000.job = "attacker";
            EliteP9000.icon = "iconP9000";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "EliteP9000");
			AssetManager.actor_library.CallMethod("addTrait", "bubble_defense");
			AssetManager.actor_library.CallMethod("loadShadow", EliteP9000);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            EliteP9000.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			EliteP9000.animation_idle = "walk_0,walk_1,walk_2,walk_3";
            EliteP9000.animation_swim = "walk_0,walk_1,walk_2,walk_3";
            EliteP9000.texture_path = "EliteP9000";
			AssetManager.actor_library.addColorSet("heliColor");
			EliteP9000.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(EliteP9000);
			Localization.addLocalization(EliteP9000.nameLocale, EliteP9000.nameLocale);
			
			var Terran = AssetManager.actor_library.clone("Terran","_mob");
			//ActorAsset heli = new ActorAsset();
           // Terran.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			Terran.race = "human";
			Terran.kingdom = "ModernKingdom";
			Terran.base_stats[S.max_age] = 50f;
            Terran.base_stats[S.health] = 1000f;
            Terran.base_stats[S.speed] = 70f;
            Terran.base_stats[S.armor] = 15f;
            Terran.base_stats[S.damage] = 10f;
            Terran.base_stats[S.scale] = 0.1f;
            Terran.base_stats[S.attack_speed] = 3005;
			Terran.base_stats[S.range] = 30f;
			Terran.base_stats[S.knockback_reduction] = 300f;
            Terran.drawBoatMark_big = true;
            Terran.inspect_stats = true;
			Terran.landCreature = true;
			Terran.has_skin = false;
			Terran.immune_to_injuries = true;
			Terran.inspect_home = true;
			Terran.hideOnMinimap = false;
            Terran.drawBoatMark = true;
			 Terran.disablePunchAttackAnimation = true;
			Terran.can_edit_traits = true;
			Terran.canReceiveTraits = true;
			Terran.flying = false;
			//Terran.tech = "Terrans";
			Terran.very_high_flyer = false;
			Terran.defaultAttack = "machinegunery";
            Terran.isBoat = false;
			Terran.dieOnBlocks = true;
			Terran.ignoreBlocks = false;
			//Terran.moveFromBlock = false;
			Terran.procreate = false;
		    Terran.inspect_children = false;
            Terran.inspect_experience = true;
			Terran.canBeCitizen = true;
            Terran.inspect_kills = true;
            Terran.use_items = false;
			Terran.oceanCreature = false;
            Terran.take_items = false;
            Terran.nameLocale = "Terran";
            Terran.nameTemplate = "Jet_Names";
			Terran.job = "attacker";
            Terran.icon = "iconTerran";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "Terran");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", Terran);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            Terran.animation_walk = "walk_0,walk_1,walk_2,walk_3,walk_4,walk_5";
			Terran.animation_idle = "walk_0";
            Terran.animation_swim = "swim_0,swim_1,swim_2";
            Terran.texture_path = "Terran";
			AssetManager.actor_library.addColorSet("heliColor");
			Terran.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(Terran);
			Localization.addLocalization(Terran.nameLocale, Terran.nameLocale);

			var dreadnaught = AssetManager.actor_library.clone("dreadnaught","_mob");
			//ActorAsset heli = new ActorAsset();
           // dreadnaught.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			dreadnaught.race = "human";
			dreadnaught.kingdom = "ModernKingdom";
			dreadnaught.base_stats[S.max_age] = 5000f;
            dreadnaught.base_stats[S.health] = 2000f;
            dreadnaught.base_stats[S.speed] = 30f;
            dreadnaught.base_stats[S.armor] = 40f;
            dreadnaught.base_stats[S.damage] = 20f;
			dreadnaught.base_stats[S.projectiles] = 2;
            dreadnaught.base_stats[S.scale] = 0.1f;
            dreadnaught.base_stats[S.attack_speed] = 305;
			dreadnaught.base_stats[S.range] = 20f;
			dreadnaught.base_stats[S.knockback_reduction] = 3f;
            dreadnaught.drawBoatMark_big = true;
            dreadnaught.has_skin = false;
			dreadnaught.immune_to_injuries = true;
            dreadnaught.inspect_stats = true;
			dreadnaught.landCreature = true;
			dreadnaught.inspect_home = true;
			dreadnaught.hideOnMinimap = false;
            dreadnaught.drawBoatMark = true;
			 dreadnaught.disablePunchAttackAnimation = true;
			dreadnaught.can_edit_traits = true;
			dreadnaught.canReceiveTraits = true;
			dreadnaught.flying = false;
			//dreadnaught.tech = "Terrans";
			dreadnaught.very_high_flyer = false;
			dreadnaught.defaultAttack = "bigbulletattack";
            dreadnaught.isBoat = false;
			dreadnaught.dieOnBlocks = true;
			dreadnaught.ignoreBlocks = false;
			//dreadnaught.moveFromBlock = false;
			dreadnaught.procreate = false;
		    dreadnaught.inspect_children = false;
            dreadnaught.inspect_experience = true;
			dreadnaught.canBeCitizen = true;
            dreadnaught.inspect_kills = true;
            dreadnaught.use_items = false;
			dreadnaught.oceanCreature = false;
            dreadnaught.take_items = false;
            dreadnaught.nameLocale = "dreadnaught";
            dreadnaught.nameTemplate = "Jet_Names";
			dreadnaught.job = "attacker";
            dreadnaught.icon = "iconTerran";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "dreadnaught");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", dreadnaught);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            dreadnaught.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			dreadnaught.animation_idle = "walk_0";
            dreadnaught.animation_swim = "swim_0,swim_1,swim_2";
            dreadnaught.texture_path = "dreadnaught";
			AssetManager.actor_library.addColorSet("heliColor");
			dreadnaught.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(dreadnaught);
			Localization.addLocalization(dreadnaught.nameLocale, dreadnaught.nameLocale);


	var HumanTitan = AssetManager.actor_library.clone("HumanTitan","_mob");
			//ActorAsset heli = new ActorAsset();
           // HumanTitan.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			HumanTitan.race = "human";
			HumanTitan.kingdom = "ModernKingdom";
			HumanTitan.base_stats[S.max_age] = 10000f;
            HumanTitan.base_stats[S.health] = 5000f;
            HumanTitan.base_stats[S.speed] = 10f;
            HumanTitan.base_stats[S.armor] = 0f;
            HumanTitan.base_stats[S.damage] = 40f;
			HumanTitan.base_stats[S.projectiles] = 1;
            HumanTitan.base_stats[S.scale] = 0.2f;
            HumanTitan.base_stats[S.attack_speed] = 50000f;
			HumanTitan.base_stats[S.range] = 20f;
			HumanTitan.base_stats[S.knockback_reduction] = 300f;
            HumanTitan.drawBoatMark_big = true;
            HumanTitan.inspect_stats = true;
			HumanTitan.landCreature = true;
			HumanTitan.inspect_home = true;
			HumanTitan.has_skin = false;
			HumanTitan.immune_to_injuries = true;
			HumanTitan.hideOnMinimap = false;
            HumanTitan.drawBoatMark = true;
			 HumanTitan.disablePunchAttackAnimation = true;
			HumanTitan.can_edit_traits = true;
			HumanTitan.canReceiveTraits = true;
			HumanTitan.flying = false;
			//HumanTitan.tech = "Terrans";
			HumanTitan.very_high_flyer = false;
			HumanTitan.defaultAttack = "bigbulletattack";
            HumanTitan.isBoat = false;
			HumanTitan.dieOnBlocks = true;
			HumanTitan.ignoreBlocks = false;
			//HumanTitan.moveFromBlock = false;
			HumanTitan.procreate = false;
		    HumanTitan.inspect_children = false;
            HumanTitan.inspect_experience = true;
			HumanTitan.canBeCitizen = true;
            HumanTitan.inspect_kills = true;
            HumanTitan.use_items = false;
			HumanTitan.oceanCreature = false;
            HumanTitan.take_items = false;
            HumanTitan.nameLocale = "HumanTitan";
            HumanTitan.nameTemplate = "Jet_Names";
			HumanTitan.job = "attacker";
            HumanTitan.icon = "iconTerran";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "HumanTitan");
			AssetManager.actor_library.CallMethod("addTrait", "bubble_defense");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", HumanTitan);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            HumanTitan.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			HumanTitan.animation_idle = "idle_0,idle_1,idle_2,idle_3";
            HumanTitan.animation_swim = "swim_0,swim_1,swim_2,swim_3";
			   AssetManager.actor_library.addColorSet("eva00");
      AssetManager.actor_library.addColorSet("eva01");
	     AssetManager.actor_library.addColorSet("eva02");
		    AssetManager.actor_library.addColorSet("eva03");
            HumanTitan.texture_path = "HumanTitan";
			AssetManager.actor_library.addColorSet("heliColor");
			HumanTitan.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(HumanTitan);
			Localization.addLocalization(HumanTitan.nameLocale, HumanTitan.nameLocale);

				var HumanTitanElite = AssetManager.actor_library.clone("HumanTitanElite","_mob");
			//ActorAsset heli = new ActorAsset();
           // HumanTitanElite.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			HumanTitanElite.race = "human";
			HumanTitanElite.kingdom = "ModernKingdom";
			HumanTitanElite.base_stats[S.max_age] = 10000f;
            HumanTitanElite.base_stats[S.health] = 10000f;
            HumanTitanElite.base_stats[S.speed] = 10f;
            HumanTitanElite.base_stats[S.armor] = 0f;
            HumanTitanElite.base_stats[S.damage] = 80f;
			HumanTitanElite.base_stats[S.projectiles] = 1;
            HumanTitanElite.base_stats[S.scale] = 0.4f;
            HumanTitanElite.base_stats[S.attack_speed] = 50000f;
			HumanTitanElite.base_stats[S.range] = 20f;
			HumanTitanElite.base_stats[S.knockback_reduction] = 300f;
            HumanTitanElite.drawBoatMark_big = true;
            HumanTitanElite.inspect_stats = true;
			HumanTitanElite.landCreature = true;
			HumanTitanElite.inspect_home = true;
			HumanTitanElite.hideOnMinimap = false;
            HumanTitanElite.drawBoatMark = true;
			 HumanTitanElite.disablePunchAttackAnimation = true;
			HumanTitanElite.can_edit_traits = true;
			HumanTitanElite.canReceiveTraits = true;
			HumanTitanElite.flying = false;
			HumanTitanElite.has_skin = false;
			HumanTitanElite.immune_to_injuries = true;
			//HumanTitanElite.tech = "Terrans";
			HumanTitanElite.very_high_flyer = false;
			HumanTitanElite.defaultAttack = "tankshellattack";
            HumanTitanElite.isBoat = false;
			HumanTitanElite.dieOnBlocks = true;
			HumanTitanElite.ignoreBlocks = false;
			//HumanTitanElite.moveFromBlock = false;
			HumanTitanElite.procreate = false;
		    HumanTitanElite.inspect_children = false;
            HumanTitanElite.inspect_experience = true;
			HumanTitanElite.canBeCitizen = true;
            HumanTitanElite.inspect_kills = true;
            HumanTitanElite.use_items = false;
			HumanTitanElite.oceanCreature = false;
            HumanTitanElite.take_items = false;
            HumanTitanElite.nameLocale = "HumanTitanElite";
            HumanTitanElite.nameTemplate = "Jet_Names";
			HumanTitanElite.job = "attacker";
            HumanTitanElite.icon = "iconTerran";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "HumanTitanElite");
			AssetManager.actor_library.CallMethod("addTrait", "bubble_defense");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", HumanTitanElite);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            HumanTitanElite.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            HumanTitanElite.animation_swim = "swim_0,swim_1,swim_2,swim_3";
			   AssetManager.actor_library.addColorSet("eva00");
      AssetManager.actor_library.addColorSet("eva01");
	     AssetManager.actor_library.addColorSet("eva02");
		    AssetManager.actor_library.addColorSet("eva03");
            HumanTitanElite.texture_path = "HumanTitanElite";
			AssetManager.actor_library.addColorSet("heliColor");
			HumanTitanElite.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(HumanTitanElite);
			Localization.addLocalization(HumanTitanElite.nameLocale, HumanTitanElite.nameLocale);

			
         EffectAsset explosion = new EffectAsset();
		    explosion.id = "explosion";
		    explosion.use_basic_prefab = true;
		    explosion.sorting_layer_id = "EffectsTop";
		    explosion.sprite_path = $"effects/explosion";
		    explosion.draw_light_area = true;
		    explosion.limit = 80;
		    AssetManager.effects_library.add(explosion);

		}




	public static bool startDeathexplosionBig(BaseSimObject pTarget, WorldTile pTile = null)
	{
		pTarget.a.findCurrentTile();
		EffectsLibrary.spawn("explosion", pTile);
		return true;
	}




	}
}
