//========= MODERNBOX 2.1.0.1 ============//
//
// Made by Tuxxego
//
//=============================================================================//
using System;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using NCMS;
using NCMS.Utils;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using ReflectionUtility;
using HarmonyLib;

namespace M2
{
    class LandVehicles : MonoBehaviour
    {
		
        public static void init()
        {
            loadAssets();

        }

        private static void loadAssets()
        {

			var Tank = AssetManager.actor_library.clone("Tank","_mob");
			//ActorAsset heli = new ActorAsset();
           // Tank.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			Tank.race = "human";
			Tank.kingdom = "ModernKingdom";
            Tank.base_stats[S.health] = 200f;
            Tank.base_stats[S.speed] = 30f;
            Tank.base_stats[S.armor] = 50f;
            Tank.base_stats[S.damage] = 40f;
            Tank.base_stats[S.scale] = 0.1f;
            Tank.base_stats[S.attack_speed] = 0;
			Tank.base_stats[S.range] = 150f;
			Tank.base_stats[S.knockback_reduction] = 300f;
            Tank.drawBoatMark_big = true;
            Tank.skipFightLogic = false;
            Tank.inspect_stats = true;
			Tank.landCreature = true;
			Tank.inspect_home = true;
			Tank.hideOnMinimap = false;
            Tank.drawBoatMark = true;
			Tank.can_edit_traits = true;
             Tank.disablePunchAttackAnimation = true;
			Tank.canReceiveTraits = true;
			Tank.flying = false;
			//Tank.tech = "Tanks";
			Tank.very_high_flyer = false;
			Tank.defaultAttack = "tankshellattack";
            Tank.isBoat = false;
			Tank.dieOnBlocks = true;
			Tank.ignoreBlocks = false;
			//Tank.moveFromBlock = false;
			Tank.procreate = false;
		    Tank.inspect_children = false;
            Tank.inspect_experience = true;
			Tank.canBeCitizen = true;
            Tank.inspect_kills = true;
            Tank.use_items = false;
			Tank.oceanCreature = false;
            Tank.take_items = false;
            Tank.nameLocale = "Tank";
            Tank.nameTemplate = "Jet_Names";
			Tank.job = "attacker";
            Tank.icon = "iconTank";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "Tank");
			AssetManager.actor_library.CallMethod("loadShadow", Tank);
			AssetManager.actor_library.CallMethod("addTrait", "immortal");
            Tank.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            Tank.animation_swim = "swim_0,swim_1";
            Tank.texture_path = "Tank";
			AssetManager.actor_library.addColorSet("heliColor");
			Tank.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(Tank);
			Localization.addLocalization(Tank.nameLocale, Tank.nameLocale);

            var AbramTank = AssetManager.actor_library.clone("AbramTank","_mob");
			//ActorAsset heli = new ActorAsset();
           // AbramTank.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			AbramTank.race = "human";
			AbramTank.kingdom = "ModernKingdom";
            AbramTank.base_stats[S.health] = 400f;
            AbramTank.base_stats[S.speed] = 60f;
            AbramTank.base_stats[S.armor] = 70f;
            AbramTank.base_stats[S.damage] = 40f;
            AbramTank.base_stats[S.scale] = 0.1f;
            AbramTank.base_stats[S.attack_speed] = 0;
			AbramTank.base_stats[S.range] = 150f;
			AbramTank.base_stats[S.knockback_reduction] = 300f;
            AbramTank.drawBoatMark_big = true;
            AbramTank.skipFightLogic = false;
            AbramTank.inspect_stats = true;
			AbramTank.landCreature = true;
			AbramTank.inspect_home = true;
			AbramTank.hideOnMinimap = false;
            AbramTank.drawBoatMark = true;
			AbramTank.can_edit_traits = true;
             AbramTank.disablePunchAttackAnimation = true;
			AbramTank.canReceiveTraits = true;
			AbramTank.flying = false;
			//AbramTank.tech = "Tanks";
			AbramTank.very_high_flyer = false;
			AbramTank.defaultAttack = "tankshellattack";
            AbramTank.isBoat = false;
			AbramTank.dieOnBlocks = true;
			AbramTank.ignoreBlocks = false;
			//AbramTank.moveFromBlock = false;
			AbramTank.procreate = false;
		    AbramTank.inspect_children = false;
            AbramTank.inspect_experience = true;
			AbramTank.canBeCitizen = true;
            AbramTank.inspect_kills = true;
            AbramTank.use_items = false;
			AbramTank.oceanCreature = false;
            AbramTank.take_items = false;
            AbramTank.nameLocale = "AbramTank";
            AbramTank.nameTemplate = "Jet_Names";
			AbramTank.job = "attacker";
            AbramTank.icon = "iconTank";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "Tank");
			AssetManager.actor_library.CallMethod("loadShadow", AbramTank);
			AssetManager.actor_library.CallMethod("addTrait", "immortal");
            AbramTank.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            AbramTank.animation_swim = "swim_0,swim_1,swim_2,swim_4";
            AbramTank.texture_path = "AbramTank";
			AssetManager.actor_library.addColorSet("heliColor");
			AbramTank.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(AbramTank);
			Localization.addLocalization(AbramTank.nameLocale, AbramTank.nameLocale);

			var MissileSystem = AssetManager.actor_library.clone("MissileSystem","_mob");
			//ActorAsset heli = new ActorAsset();
           // MissileSystem.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			MissileSystem.race = "human";
			MissileSystem.kingdom = "MissileLauncherFULLRANGETARGETTING";
            MissileSystem.base_stats[S.health] = 200f;
            MissileSystem.base_stats[S.speed] = 100f;
            MissileSystem.base_stats[S.armor] = 60f;
            MissileSystem.base_stats[S.damage] = 40f;
            MissileSystem.base_stats[S.scale] = 0.1f;
            MissileSystem.base_stats[S.attack_speed] = 0;
			MissileSystem.base_stats[S.range] = 150f;
			MissileSystem.base_stats[S.knockback_reduction] = 300f;
            MissileSystem.drawBoatMark_big = true;
            MissileSystem.skipFightLogic = false;
            MissileSystem.inspect_stats = true;
			MissileSystem.landCreature = true;
			MissileSystem.inspect_home = true;
			MissileSystem.hideOnMinimap = false;
            MissileSystem.drawBoatMark = true;
			MissileSystem.can_edit_traits = true;
                 MissileSystem.disablePunchAttackAnimation = true;
			MissileSystem.canReceiveTraits = true;
			MissileSystem.flying = false;
			//MissileSystem.tech = "MissileSystems";
			MissileSystem.very_high_flyer = false;
			MissileSystem.defaultAttack = "MIRV";
            MissileSystem.isBoat = false;
			MissileSystem.dieOnBlocks = false;
			MissileSystem.ignoreBlocks = true;
			//MissileSystem.moveFromBlock = false;
			MissileSystem.procreate = false;
		    MissileSystem.inspect_children = false;
            MissileSystem.inspect_experience = true;
			MissileSystem.canBeCitizen = true;
            MissileSystem.inspect_kills = true;
            MissileSystem.use_items = false;
			MissileSystem.oceanCreature = false;
            MissileSystem.take_items = false;
            MissileSystem.nameLocale = "MissileSystem";
            MissileSystem.nameTemplate = "Jet_Names";
			MissileSystem.job = "attacker";
            MissileSystem.icon = "iconMissileSystem";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "MissileSystem");
			AssetManager.actor_library.CallMethod("loadShadow", MissileSystem);
			AssetManager.actor_library.CallMethod("addTrait", "immortal");
            MissileSystem.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            MissileSystem.animation_swim = "swim_0,swim_1,swim_2";
            MissileSystem.animation_idle = "idle_0";
            MissileSystem.texture_path = "MissileSystem";
			AssetManager.actor_library.addColorSet("heliColor");
			MissileSystem.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(MissileSystem);
			Localization.addLocalization(MissileSystem.nameLocale, MissileSystem.nameLocale);

            var eliteMissileSystem = AssetManager.actor_library.clone("eliteMissileSystem","_mob");
			//ActorAsset heli = new ActorAsset();
           // eliteMissileSystem.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			eliteMissileSystem.race = "human";
			eliteMissileSystem.kingdom = "MissileLauncherFULLRANGETARGETTING";
            eliteMissileSystem.base_stats[S.health] = 400f;
            eliteMissileSystem.base_stats[S.speed] = 100f;
            eliteMissileSystem.base_stats[S.armor] = 70f;
            eliteMissileSystem.base_stats[S.damage] = 10f;
            eliteMissileSystem.base_stats[S.scale] = 0.1f;
            eliteMissileSystem.base_stats[S.attack_speed] = 10000;
			eliteMissileSystem.base_stats[S.range] = 150f;
			eliteMissileSystem.base_stats[S.knockback_reduction] = 300f;
            eliteMissileSystem.drawBoatMark_big = true;
            eliteMissileSystem.skipFightLogic = false;
            eliteMissileSystem.inspect_stats = true;
			eliteMissileSystem.landCreature = true;
			eliteMissileSystem.inspect_home = true;
			eliteMissileSystem.hideOnMinimap = false;
            eliteMissileSystem.drawBoatMark = true;
			eliteMissileSystem.can_edit_traits = true;
                 eliteMissileSystem.disablePunchAttackAnimation = true;
			eliteMissileSystem.canReceiveTraits = true;
			eliteMissileSystem.flying = false;
			//eliteMissileSystem.tech = "MissileSystems";
			eliteMissileSystem.very_high_flyer = false;
			eliteMissileSystem.defaultAttack = "MIRV";
            eliteMissileSystem.isBoat = false;
			eliteMissileSystem.dieOnBlocks = false;
			eliteMissileSystem.ignoreBlocks = true;
			//eliteMissileSystem.moveFromBlock = false;
			eliteMissileSystem.procreate = false;
		    eliteMissileSystem.inspect_children = false;
            eliteMissileSystem.inspect_experience = true;
			eliteMissileSystem.canBeCitizen = true;
            eliteMissileSystem.inspect_kills = true;
            eliteMissileSystem.use_items = false;
			eliteMissileSystem.oceanCreature = false;
            eliteMissileSystem.take_items = false;
            eliteMissileSystem.nameLocale = "eliteMissileSystem";
            eliteMissileSystem.nameTemplate = "Jet_Names";
			eliteMissileSystem.job = "attacker";
            eliteMissileSystem.icon = "iconMissileSystem";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "MissileSystem");
			AssetManager.actor_library.CallMethod("loadShadow", eliteMissileSystem);
			AssetManager.actor_library.CallMethod("addTrait", "immortal");
            eliteMissileSystem.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            eliteMissileSystem.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            eliteMissileSystem.animation_idle = "walk_0";
            eliteMissileSystem.texture_path = "eliteMissileSystem";
			AssetManager.actor_library.addColorSet("heliColor");
			eliteMissileSystem.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(eliteMissileSystem);
			Localization.addLocalization(eliteMissileSystem.nameLocale, eliteMissileSystem.nameLocale);

            var Railgun = AssetManager.actor_library.clone("Railgun", "_mob");
            //ActorAsset heli = new ActorAsset();
            // Tank.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
            Railgun.race = "human";
            Railgun.kingdom = "ModernKingdom";
            Railgun.base_stats[S.health] = 600f;
            Railgun.base_stats[S.speed] = 80f;
            Railgun.base_stats[S.armor] = 80f;
            Railgun.base_stats[S.damage] = 60f;
            Railgun.base_stats[S.attack_speed] = 0;
            Railgun.base_stats[S.range] = 150f;
            Railgun.base_stats[S.knockback_reduction] = 320f;
            Railgun.drawBoatMark_big = true;
            Railgun.skipFightLogic = false;
            Railgun.inspect_stats = true;
              Railgun.disablePunchAttackAnimation = true;
            Railgun.landCreature = true;
            Railgun.inspect_home = true;
            Railgun.hideOnMinimap = false;
            Railgun.drawBoatMark = true;
            Railgun.can_edit_traits = true;
            Railgun.canReceiveTraits = true;
            Railgun.flying = false;
            //Tank.tech = "Tanks";
            Railgun.very_high_flyer = false;
            Railgun.defaultAttack = "tankshellattack";
            Railgun.isBoat = false;
            Railgun.dieOnBlocks = true;
            Railgun.ignoreBlocks = false;
            //Tank.moveFromBlock = false;
            Railgun.procreate = false;
            Railgun.inspect_children = false;
            Railgun.inspect_experience = true;
            Railgun.canBeCitizen = true;
            Railgun.inspect_kills = true;
            Railgun.use_items = false;
            Railgun.oceanCreature = false;
            Railgun.take_items = false;
            Railgun.nameLocale = "Railgun";
            Railgun.nameTemplate = "Jet_Names";
            Railgun.job = "attacker";
            Railgun.icon = "iconRailgun";
            AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
            AssetManager.actor_library.CallMethod("addTrait", "Railgun");
            AssetManager.actor_library.CallMethod("loadShadow", Railgun);
            AssetManager.actor_library.CallMethod("addTrait", "immortal");
            Railgun.animation_walk = "walk_0,walk_1,walk_2";
            Railgun.animation_idle = "walk_0";
            Railgun.animation_swim = "swim_0,swim_1,swim_2";
            Railgun.texture_path = "Railgun";
            AssetManager.actor_library.addColorSet("heliColor");
            Railgun.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(Railgun);
            Localization.addLocalization(Railgun.nameLocale, Railgun.nameLocale);

            var OmegaRailgun = AssetManager.actor_library.clone("OmegaRailgun", "_mob");
            //ActorAsset heli = new ActorAsset();
            // Tank.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
            OmegaRailgun.race = "human";
            OmegaRailgun.kingdom = "ModernKingdom";
            OmegaRailgun.base_stats[S.health] = 1000f;
            OmegaRailgun.base_stats[S.speed] = 80f;
            OmegaRailgun.base_stats[S.armor] = 90f;
            OmegaRailgun.base_stats[S.damage] = 100f;
            OmegaRailgun.base_stats[S.attack_speed] = 0;
            OmegaRailgun.base_stats[S.range] = 150f;
            OmegaRailgun.base_stats[S.knockback_reduction] = 320f;
            OmegaRailgun.drawBoatMark_big = true;
            OmegaRailgun.skipFightLogic = false;
            OmegaRailgun.inspect_stats = true;
              OmegaRailgun.disablePunchAttackAnimation = true;
            OmegaRailgun.landCreature = true;
            OmegaRailgun.inspect_home = true;
            OmegaRailgun.hideOnMinimap = false;
            OmegaRailgun.drawBoatMark = true;
            OmegaRailgun.can_edit_traits = true;
            OmegaRailgun.canReceiveTraits = true;
            OmegaRailgun.flying = false;
            //Tank.tech = "Tanks";
            OmegaRailgun.very_high_flyer = false;
            OmegaRailgun.defaultAttack = "tankshellattack";
            OmegaRailgun.isBoat = false;
            OmegaRailgun.dieOnBlocks = true;
            OmegaRailgun.ignoreBlocks = false;
            //Tank.moveFromBlock = false;
            OmegaRailgun.procreate = false;
            OmegaRailgun.inspect_children = false;
            OmegaRailgun.inspect_experience = true;
            OmegaRailgun.canBeCitizen = true;
            OmegaRailgun.inspect_kills = true;
            OmegaRailgun.use_items = false;
            OmegaRailgun.oceanCreature = false;
            OmegaRailgun.take_items = false;
            OmegaRailgun.nameLocale = "OmegaRailgun";
            OmegaRailgun.nameTemplate = "Jet_Names";
            OmegaRailgun.job = "attacker";
            OmegaRailgun.icon = "iconRailgun";
            AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
            AssetManager.actor_library.CallMethod("addTrait", "Railgun");
            AssetManager.actor_library.CallMethod("loadShadow", OmegaRailgun);
            AssetManager.actor_library.CallMethod("addTrait", "immortal");
            OmegaRailgun.animation_walk = "walk_0,walk_1,walk_2";
            OmegaRailgun.animation_idle = "walk_0";
            OmegaRailgun.animation_swim = "swim_0,swim_1,swim_2";
            OmegaRailgun.texture_path = "OmegaRailgun";
            AssetManager.actor_library.addColorSet("heliColor");
            OmegaRailgun.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(OmegaRailgun);
            Localization.addLocalization(OmegaRailgun.nameLocale, OmegaRailgun.nameLocale);

            var Humvee = AssetManager.actor_library.clone("Humvee","_mob");
			//ActorAsset heli = new ActorAsset();
           // Humvee.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			Humvee.race = "human";
			Humvee.kingdom = "ModernKingdom";
            Humvee.base_stats[S.health] = 200f;
            Humvee.base_stats[S.speed] = 100f;
            Humvee.base_stats[S.armor] = 40f;
            Humvee.base_stats[S.damage] = 40f;
            Humvee.base_stats[S.scale] = 0.1f;
            Humvee.base_stats[S.attack_speed] = 0;
			Humvee.base_stats[S.range] = 150f;
			Humvee.base_stats[S.knockback_reduction] = 300f;
            Humvee.drawBoatMark_big = true;
            Humvee.skipFightLogic = false;
            Humvee.inspect_stats = true;
			Humvee.landCreature = true;
			Humvee.inspect_home = true;
			Humvee.hideOnMinimap = false;
            Humvee.drawBoatMark = true;
			Humvee.can_edit_traits = true;
			Humvee.canReceiveTraits = true;
			Humvee.flying = false;
			//Humvee.tech = "Humvees";
			Humvee.very_high_flyer = false;
            Humvee.isBoat = false;
			Humvee.dieOnBlocks = false;
			Humvee.ignoreBlocks = false;
			Humvee.moveFromBlock = true;
			Humvee.procreate = false;
		    Humvee.inspect_children = false;
            Humvee.inspect_experience = true;
              Humvee.disablePunchAttackAnimation = true;
			Humvee.defaultAttack = "Minigun";
			Humvee.canBeCitizen = true;
            Humvee.inspect_kills = true;
            Humvee.use_items = false;
			Humvee.oceanCreature = false;
            Humvee.take_items = false;
            Humvee.nameLocale = "Humvee";
            Humvee.nameTemplate = "Humvee_Names";
			Humvee.job = "attacker";
            Humvee.icon = "iconHumvee";
			AssetManager.actor_library.CallMethod("addTrait", "Humvee");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("loadShadow", Humvee);
			AssetManager.actor_library.CallMethod("addTrait", "immortal");
            Humvee.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			Humvee.animation_idle = "walk_0";
            Humvee.animation_swim = "swim_0,swim_1,swim_2,swim_4";
            Humvee.texture_path = "Humvee";
			AssetManager.actor_library.addColorSet("heliColor");
			Humvee.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(Humvee);
			Localization.addLocalization(Humvee.nameLocale, Humvee.nameLocale);
		  

            			  var wheeledtank = AssetManager.actor_library.clone("wheeledtank","_mob");
			//ActorAsset heli = new ActorAsset();
           // wheeledtank.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			wheeledtank.race = "human";
			wheeledtank.kingdom = "ModernKingdom";
            wheeledtank.base_stats[S.health] = 600f;
            wheeledtank.base_stats[S.speed] = 100f;
            wheeledtank.base_stats[S.armor] = 80f;
            wheeledtank.base_stats[S.damage] = 20f;
            wheeledtank.base_stats[S.scale] = 0.1f;
            wheeledtank.base_stats[S.attack_speed] = 0;
			wheeledtank.base_stats[S.range] = 150f;
			wheeledtank.base_stats[S.knockback_reduction] = 300f;
            wheeledtank.drawBoatMark_big = true;
            wheeledtank.skipFightLogic = false;
            wheeledtank.inspect_stats = true;
			wheeledtank.landCreature = true;
			wheeledtank.inspect_home = true;
			wheeledtank.hideOnMinimap = false;
            wheeledtank.drawBoatMark = true;
			wheeledtank.can_edit_traits = true;
			wheeledtank.canReceiveTraits = true;
			wheeledtank.flying = false;
			//wheeledtank.tech = "Humvees";
			wheeledtank.very_high_flyer = false;
            wheeledtank.isBoat = false;
			wheeledtank.dieOnBlocks = false;
			wheeledtank.ignoreBlocks = false;
			wheeledtank.moveFromBlock = true;
			wheeledtank.procreate = false;
		    wheeledtank.inspect_children = false;
            wheeledtank.inspect_experience = true;
              wheeledtank.disablePunchAttackAnimation = true;
			wheeledtank.defaultAttack = "tankshellattack";
			wheeledtank.canBeCitizen = true;
            wheeledtank.inspect_kills = true;
            wheeledtank.use_items = false;
			wheeledtank.oceanCreature = false;
            wheeledtank.take_items = false;
            wheeledtank.nameLocale = "wheeledtank";
            wheeledtank.nameTemplate = "Humvee_Names";
			wheeledtank.job = "attacker";
            wheeledtank.icon = "iconHumvee";
			AssetManager.actor_library.CallMethod("addTrait", "Humvee");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("loadShadow", wheeledtank);
			AssetManager.actor_library.CallMethod("addTrait", "immortal");
            wheeledtank.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			wheeledtank.animation_idle = "walk_0";
            wheeledtank.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            wheeledtank.texture_path = "wheeledtank";
			AssetManager.actor_library.addColorSet("heliColor");
			wheeledtank.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(wheeledtank);
			Localization.addLocalization(wheeledtank.nameLocale, wheeledtank.nameLocale);

		  


		}
		}
}
