//========= MODERNBOX 2.1.0.1 ============//
//
// Made by Tuxxego
//
//=============================================================================//
using System;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using NCMS;
using NCMS.Utils;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using ReflectionUtility;
using HarmonyLib;

namespace M2
{
    class LandVehicles : MonoBehaviour
    {
		
        public static void init()
        {
            loadAssets();

        }

        private static void loadAssets()
        {

            var Tank = AssetManager.actor_library.clone("Tank","_mob");
			//ActorAsset heli = new ActorAsset();
           // Tank.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			Tank.race = "human";
			Tank.kingdom = "ModernKingdom";
			Tank.base_stats[S.max_age] = 50f;
            Tank.base_stats[S.health] = 800f;
            Tank.base_stats[S.speed] = 50f;
            Tank.base_stats[S.armor] = 50f;
            Tank.base_stats[S.damage] = 60f;
            Tank.base_stats[S.scale] = 0.2f;
            Tank.base_stats[S.attack_speed] = 0;
			Tank.base_stats[S.range] = 40f;
			Tank.base_stats[S.knockback_reduction] = 300f;
            Tank.immune_to_injuries = true;
            Tank.inspect_stats = true;
            Tank.has_skin = false;
			Tank.landCreature = true;
			Tank.inspect_home = true;
			Tank.hideOnMinimap = false;
            Tank.drawBoatMark = true;
			Tank.can_edit_traits = true;
             Tank.disablePunchAttackAnimation = true;
			Tank.canReceiveTraits = true;
			Tank.flying = false;
			//Tank.tech = "Tanks";
			Tank.very_high_flyer = false;
			Tank.defaultAttack = "tankshellattack";
			Tank.dieOnBlocks = true;
			Tank.ignoreBlocks = false;
			//Tank.moveFromBlock = false;
			Tank.procreate = false;
		    Tank.inspect_children = false;
            Tank.inspect_experience = true;
			Tank.canBeCitizen = true;
            Tank.inspect_kills = true;
            Tank.use_items = false;
			Tank.oceanCreature = false;
            Tank.take_items = false;
            Tank.nameLocale = "Tank";
            Tank.nameTemplate = "Jet_Names";
			Tank.job = "attacker";
            Tank.icon = "iconTank";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "Tank");
             AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", Tank);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            Tank.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            Tank.animation_idle = "idle_0,idle_1,idle_2";
            Tank.animation_swim = "swim_0,swim_1,swim_2";
            Tank.texture_path = "Tank";
			AssetManager.actor_library.addColorSet("heliColor");
			Tank.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(Tank);
			Localization.addLocalization(Tank.nameLocale, Tank.nameLocale);

            var AbramTank = AssetManager.actor_library.clone("AbramTank","_mob");
			//ActorAsset heli = new ActorAsset();
           // AbramTank.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			AbramTank.race = "human";
			AbramTank.kingdom = "ModernKingdom";
			AbramTank.base_stats[S.max_age] = 50f;
            AbramTank.base_stats[S.health] = 800f;
            AbramTank.base_stats[S.speed] = 20f;
            AbramTank.base_stats[S.armor] = 70f;
            AbramTank.base_stats[S.damage] = 40f;
            AbramTank.base_stats[S.scale] = 0.2f;
            AbramTank.base_stats[S.attack_speed] = 0;
			AbramTank.base_stats[S.range] = 60f;
			AbramTank.base_stats[S.knockback_reduction] = 300f;
			AbramTank.immune_to_injuries = true;
            AbramTank.inspect_stats = true;
			AbramTank.landCreature = true;
			AbramTank.inspect_home = true;
			AbramTank.hideOnMinimap = false;
            AbramTank.drawBoatMark = true;
			AbramTank.can_edit_traits = true;
             AbramTank.disablePunchAttackAnimation = true;
			AbramTank.canReceiveTraits = true;
			AbramTank.flying = false;
			//AbramTank.tech = "Tanks";
			AbramTank.very_high_flyer = false;
			AbramTank.defaultAttack = "tankshellattack";
            AbramTank.has_skin = false;
			AbramTank.dieOnBlocks = true;
			AbramTank.ignoreBlocks = false;
			//AbramTank.moveFromBlock = false;
			AbramTank.procreate = false;
		    AbramTank.inspect_children = false;
            AbramTank.inspect_experience = true;
			AbramTank.canBeCitizen = true;
            AbramTank.inspect_kills = true;
            AbramTank.use_items = false;
			AbramTank.oceanCreature = false;
            AbramTank.take_items = false;
            AbramTank.nameLocale = "AbramTank";
            AbramTank.nameTemplate = "Jet_Names";
			AbramTank.job = "attacker";
            AbramTank.icon = "iconTank";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "Tank");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", AbramTank);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AbramTank.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            AbramTank.animation_swim = "swim_0,swim_1,swim_2,swim_4";
            AbramTank.texture_path = "AbramTank";
			AssetManager.actor_library.addColorSet("heliColor");
			AbramTank.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(AbramTank);
			Localization.addLocalization(AbramTank.nameLocale, AbramTank.nameLocale);

             var tankie = AssetManager.actor_library.clone("tankie","_mob");
			//ActorAsset heli = new ActorAsset();
           // tankie.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			tankie.race = "human";
			tankie.kingdom = "ModernKingdom";
			tankie.base_stats[S.max_age] = 50f;
            tankie.base_stats[S.health] = 450f;
            tankie.base_stats[S.speed] = 50f;
            tankie.base_stats[S.armor] = 40f;
            tankie.base_stats[S.damage] = 40f;
            tankie.base_stats[S.scale] = 0.2f;
            tankie.base_stats[S.attack_speed] = 0;
			tankie.base_stats[S.range] = 40f;
			tankie.base_stats[S.knockback_reduction] = 300f;
            tankie.immune_to_injuries = true;
            tankie.has_skin = false;
            tankie.inspect_stats = true;
			tankie.landCreature = true;
			tankie.inspect_home = true;
			tankie.hideOnMinimap = false;
            tankie.drawBoatMark = true;
			tankie.can_edit_traits = true;
             tankie.disablePunchAttackAnimation = true;
			tankie.canReceiveTraits = true;
			tankie.flying = false;
			//tankie.tech = "tankies";
			tankie.very_high_flyer = false;
			tankie.defaultAttack = "tankshellattack";
			tankie.dieOnBlocks = true;
			tankie.ignoreBlocks = false;
			//tankie.moveFromBlock = false;
			tankie.procreate = false;
		    tankie.inspect_children = false;
            tankie.inspect_experience = true;
			tankie.canBeCitizen = true;
            tankie.inspect_kills = true;
            tankie.use_items = false;
			tankie.oceanCreature = false;
            tankie.take_items = false;
            tankie.nameLocale = "tankie";
            tankie.nameTemplate = "Jet_Names";
			tankie.job = "attacker";
            tankie.icon = "icontankie";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "tankie");
             AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", tankie);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            tankie.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            tankie.animation_idle = "walk_0";
            tankie.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            tankie.texture_path = "tankie";
			AssetManager.actor_library.addColorSet("heliColor");
			tankie.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(tankie);
			Localization.addLocalization(tankie.nameLocale, tankie.nameLocale);

                         var wwartillery = AssetManager.actor_library.clone("wwartillery","_mob");
			//ActorAsset heli = new ActorAsset();
           // wwartillery.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			wwartillery.race = "human";
			wwartillery.kingdom = "ModernKingdom";
			wwartillery.base_stats[S.max_age] = 50f;
            wwartillery.base_stats[S.health] = 50f;
            wwartillery.base_stats[S.speed] = 20f;
            wwartillery.base_stats[S.armor] = 20f;
            wwartillery.base_stats[S.damage] = 400f;
            wwartillery.base_stats[S.scale] = 0.2f;
            wwartillery.base_stats[S.attack_speed] = 0;
			wwartillery.base_stats[S.range] = 100f;
			wwartillery.base_stats[S.knockback_reduction] = 300f;
            wwartillery.immune_to_injuries = true;
            wwartillery.has_skin = false;
            wwartillery.inspect_stats = true;
			wwartillery.landCreature = true;
			wwartillery.inspect_home = true;
			wwartillery.hideOnMinimap = false;
            wwartillery.drawBoatMark = true;
			wwartillery.can_edit_traits = true;
             wwartillery.disablePunchAttackAnimation = true;
			wwartillery.canReceiveTraits = true;
			wwartillery.flying = false;
			//wwartillery.tech = "wwartillerys";
			wwartillery.very_high_flyer = false;
			wwartillery.defaultAttack = "artillerystriker";
			wwartillery.dieOnBlocks = true;
			wwartillery.ignoreBlocks = false;
			//wwartillery.moveFromBlock = false;
			wwartillery.procreate = false;
		    wwartillery.inspect_children = false;
            wwartillery.inspect_experience = true;
			wwartillery.canBeCitizen = true;
            wwartillery.inspect_kills = true;
            wwartillery.use_items = false;
			wwartillery.oceanCreature = false;
            wwartillery.take_items = false;
            wwartillery.nameLocale = "wwartillery";
            wwartillery.nameTemplate = "Jet_Names";
			wwartillery.job = "attacker";
            wwartillery.icon = "iconwwartillery";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "wwartillery");
             AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", wwartillery);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            wwartillery.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            wwartillery.animation_idle = "walk_0";
            wwartillery.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            wwartillery.texture_path = "wwartillery";
			AssetManager.actor_library.addColorSet("heliColor");
			wwartillery.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(wwartillery);
			Localization.addLocalization(wwartillery.nameLocale, wwartillery.nameLocale);

              var genericwwtank = AssetManager.actor_library.clone("genericwwtank","_mob");
			//ActorAsset heli = new ActorAsset();
           // genericwwtank.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			genericwwtank.race = "human";
			genericwwtank.kingdom = "ModernKingdom";
			genericwwtank.base_stats[S.max_age] = 50f;
            genericwwtank.base_stats[S.health] = 550f;
            genericwwtank.base_stats[S.speed] = 50f;
            genericwwtank.base_stats[S.armor] = 40f;
            genericwwtank.base_stats[S.damage] = 40f;
            genericwwtank.base_stats[S.scale] = 0.2f;
            genericwwtank.base_stats[S.attack_speed] = 0;
			genericwwtank.base_stats[S.range] = 40f;
			genericwwtank.base_stats[S.knockback_reduction] = 300f;
            genericwwtank.immune_to_injuries = true;
            genericwwtank.inspect_stats = true;
			genericwwtank.landCreature = true;
			genericwwtank.inspect_home = true;
			genericwwtank.hideOnMinimap = false;
            genericwwtank.drawBoatMark = true;
			genericwwtank.can_edit_traits = true;
             genericwwtank.disablePunchAttackAnimation = true;
			genericwwtank.canReceiveTraits = true;
			genericwwtank.flying = false;
			//genericwwtank.tech = "genericwwtanks";
			genericwwtank.very_high_flyer = false;
			genericwwtank.defaultAttack = "tankshellattack";
            genericwwtank.has_skin = false;
			genericwwtank.dieOnBlocks = true;
			genericwwtank.ignoreBlocks = false;
			//genericwwtank.moveFromBlock = false;
			genericwwtank.procreate = false;
		    genericwwtank.inspect_children = false;
            genericwwtank.inspect_experience = true;
			genericwwtank.canBeCitizen = true;
            genericwwtank.inspect_kills = true;
            genericwwtank.use_items = false;
			genericwwtank.oceanCreature = false;
            genericwwtank.take_items = false;
            genericwwtank.nameLocale = "genericwwtank";
            genericwwtank.nameTemplate = "Jet_Names";
			genericwwtank.job = "attacker";
            genericwwtank.icon = "icongenericwwtank";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "genericwwtank");
             AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", genericwwtank);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            genericwwtank.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            genericwwtank.animation_idle = "walk_0";
            genericwwtank.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            genericwwtank.texture_path = "genericwwtank";
			AssetManager.actor_library.addColorSet("heliColor");
			genericwwtank.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(genericwwtank);
			Localization.addLocalization(genericwwtank.nameLocale, genericwwtank.nameLocale);

                        var landship = AssetManager.actor_library.clone("landship","_mob");
			//ActorAsset heli = new ActorAsset();
           // landship.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			landship.race = "human";
			landship.kingdom = "ModernKingdom";
			landship.base_stats[S.max_age] = 50f;
            landship.base_stats[S.health] = 350f;
            landship.base_stats[S.speed] = 50f;
            landship.base_stats[S.armor] = 30f;
            landship.base_stats[S.damage] = 10f;
            landship.base_stats[S.scale] = 0.2f;
            landship.base_stats[S.attack_speed] = 200;
			landship.base_stats[S.range] = 40f;
			landship.base_stats[S.knockback_reduction] = 300f;
            landship.immune_to_injuries = true;
            landship.inspect_stats = true;
			landship.landCreature = true;
			landship.inspect_home = true;
			landship.hideOnMinimap = false;
            landship.drawBoatMark = true;
			landship.can_edit_traits = true;
             landship.disablePunchAttackAnimation = true;
			landship.canReceiveTraits = true;
			landship.flying = false;
			//landship.tech = "landships";
			landship.very_high_flyer = false;
			landship.defaultAttack = "singleshot";
            landship.has_skin = false;
			landship.dieOnBlocks = true;
			landship.ignoreBlocks = false;
			//landship.moveFromBlock = false;
			landship.procreate = false;
		    landship.inspect_children = false;
            landship.inspect_experience = true;
			landship.canBeCitizen = true;
            landship.inspect_kills = true;
            landship.use_items = false;
			landship.oceanCreature = false;
            landship.take_items = false;
            landship.nameLocale = "landship";
            landship.nameTemplate = "Jet_Names";
			landship.job = "attacker";
            landship.icon = "iconlandship";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "landship");
             AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", landship);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            landship.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            landship.animation_idle = "walk_0";
            landship.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            landship.texture_path = "landship";
			AssetManager.actor_library.addColorSet("heliColor");
			landship.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(landship);
			Localization.addLocalization(landship.nameLocale, landship.nameLocale);

            var bigtankww = AssetManager.actor_library.clone("bigtankww","_mob");
			//ActorAsset heli = new ActorAsset();
           // bigtankww.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			bigtankww.race = "human";
			bigtankww.kingdom = "ModernKingdom";
			bigtankww.base_stats[S.max_age] = 50f;
            bigtankww.base_stats[S.health] = 650f;
            bigtankww.base_stats[S.speed] = 20f;
            bigtankww.base_stats[S.armor] = 30f;
            bigtankww.base_stats[S.damage] = 55f;
            bigtankww.base_stats[S.scale] = 0.2f;
            bigtankww.base_stats[S.attack_speed] = 0;
			bigtankww.base_stats[S.range] = 40f;
			bigtankww.base_stats[S.knockback_reduction] = 300f;
            bigtankww.immune_to_injuries = true;
            bigtankww.inspect_stats = true;
			bigtankww.landCreature = true;
			bigtankww.inspect_home = true;
			bigtankww.hideOnMinimap = false;
            bigtankww.drawBoatMark = true;
			bigtankww.can_edit_traits = true;
             bigtankww.disablePunchAttackAnimation = true;
			bigtankww.canReceiveTraits = true;
			bigtankww.flying = false;
			//bigtankww.tech = "bigtankwws";
			bigtankww.very_high_flyer = false;
			bigtankww.defaultAttack = "tankshellattack";
            bigtankww.has_skin = false;
			bigtankww.dieOnBlocks = true;
			bigtankww.ignoreBlocks = false;
			//bigtankww.moveFromBlock = false;
			bigtankww.procreate = false;
		    bigtankww.inspect_children = false;
            bigtankww.inspect_experience = true;
			bigtankww.canBeCitizen = true;
            bigtankww.inspect_kills = true;
            bigtankww.use_items = false;
			bigtankww.oceanCreature = false;
            bigtankww.take_items = false;
            bigtankww.nameLocale = "bigtankww";
            bigtankww.nameTemplate = "Jet_Names";
			bigtankww.job = "attacker";
            bigtankww.icon = "iconbigtankww";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "bigtankww");
             AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", bigtankww);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            bigtankww.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            bigtankww.animation_idle = "walk_0";
            bigtankww.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            bigtankww.texture_path = "bigtankww";
			AssetManager.actor_library.addColorSet("heliColor");
			bigtankww.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(bigtankww);
			Localization.addLocalization(bigtankww.nameLocale, bigtankww.nameLocale);

                        var davincitank = AssetManager.actor_library.clone("davincitank","_mob");
			//ActorAsset heli = new ActorAsset();
           // davincitank.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			davincitank.race = "human";
			davincitank.kingdom = "ModernKingdom";
			davincitank.base_stats[S.max_age] = 50f;
            davincitank.base_stats[S.health] = 300f;
            davincitank.base_stats[S.speed] = 20f;
            davincitank.base_stats[S.armor] = 20f;
            davincitank.base_stats[S.damage] = 20f;
            davincitank.base_stats[S.scale] = 0.2f;
            davincitank.base_stats[S.attack_speed] = 20;
			davincitank.base_stats[S.range] = 20f;
			davincitank.base_stats[S.knockback_reduction] = 3f;
            davincitank.immune_to_injuries = true;
            davincitank.inspect_stats = true;
			davincitank.landCreature = true;
			davincitank.inspect_home = true;
			davincitank.hideOnMinimap = false;
            davincitank.drawBoatMark = true;
			davincitank.can_edit_traits = true;
             davincitank.disablePunchAttackAnimation = true;
			davincitank.canReceiveTraits = true;
			davincitank.flying = false;
			//davincitank.tech = "davincitanks";
			davincitank.very_high_flyer = false;
			davincitank.defaultAttack = "cannonstriker";
            davincitank.has_skin = false;
			davincitank.dieOnBlocks = true;
			davincitank.ignoreBlocks = false;
			//davincitank.moveFromBlock = false;
			davincitank.procreate = false;
		    davincitank.inspect_children = false;
            davincitank.inspect_experience = true;
			davincitank.canBeCitizen = true;
            davincitank.inspect_kills = true;
            davincitank.use_items = false;
			davincitank.oceanCreature = false;
            davincitank.take_items = false;
            davincitank.nameLocale = "davincitank";
            davincitank.nameTemplate = "Jet_Names";
			davincitank.job = "attacker";
            davincitank.icon = "icondavincitank";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "davincitank");
             AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", davincitank);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            davincitank.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            davincitank.animation_idle = "walk_0,walk_1,walk_2,walk_3";
            davincitank.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            davincitank.texture_path = "davincitank";
			AssetManager.actor_library.addColorSet("heliColor");
			davincitank.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(davincitank);
			Localization.addLocalization(davincitank.nameLocale, davincitank.nameLocale);

			var MissileSystem = AssetManager.actor_library.clone("MissileSystem","_mob");
			//ActorAsset heli = new ActorAsset();
           // MissileSystem.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			MissileSystem.race = "human";
			MissileSystem.kingdom = "MissileLauncherFULLRANGETARGETTING";
			MissileSystem.base_stats[S.max_age] = 50f;
            MissileSystem.base_stats[S.health] = 800f;
            MissileSystem.base_stats[S.speed] = 20f;
            MissileSystem.base_stats[S.armor] = 30f;
            MissileSystem.base_stats[S.damage] = 40f;
            MissileSystem.base_stats[S.scale] = 0.2f;
            MissileSystem.base_stats[S.attack_speed] = 0;
			MissileSystem.base_stats[S.range] = 150f;
			MissileSystem.base_stats[S.knockback_reduction] = 300f;
            MissileSystem.immune_to_injuries = true;
            MissileSystem.inspect_stats = true;
			MissileSystem.landCreature = true;
			MissileSystem.inspect_home = true;
			MissileSystem.hideOnMinimap = false;
            MissileSystem.drawBoatMark = true;
			MissileSystem.can_edit_traits = true;
            MissileSystem.disablePunchAttackAnimation = true;
			MissileSystem.canReceiveTraits = true;
			MissileSystem.flying = false;
			//MissileSystem.tech = "MissileSystems";
			MissileSystem.very_high_flyer = false;
			MissileSystem.defaultAttack = "missilelauncherlong";
            MissileSystem.has_skin = false;
			MissileSystem.dieOnBlocks = false;
			MissileSystem.ignoreBlocks = true;
			//MissileSystem.moveFromBlock = false;
			MissileSystem.procreate = false;
		    MissileSystem.inspect_children = false;
            MissileSystem.inspect_experience = true;
			MissileSystem.canBeCitizen = true;
            MissileSystem.inspect_kills = true;
            MissileSystem.use_items = false;
			MissileSystem.oceanCreature = false;
            MissileSystem.take_items = false;
            MissileSystem.nameLocale = "MissileSystem";
            MissileSystem.nameTemplate = "Jet_Names";
			MissileSystem.job = "attacker";
            MissileSystem.icon = "iconMissileSystem";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "MissileSystem");
			AssetManager.actor_library.CallMethod("loadShadow", MissileSystem);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            MissileSystem.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            MissileSystem.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            MissileSystem.animation_idle = "idle_0";
            MissileSystem.texture_path = "MissileSystem";
			AssetManager.actor_library.addColorSet("heliColor");
			MissileSystem.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(MissileSystem);
			Localization.addLocalization(MissileSystem.nameLocale, MissileSystem.nameLocale);

            var shermanww = AssetManager.actor_library.clone("shermanww","_mob");
			//ActorAsset heli = new ActorAsset();
           // shermanww.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			shermanww.race = "human";
			shermanww.kingdom = "MissileLauncherFULLRANGETARGETTING";
			shermanww.base_stats[S.max_age] = 50f;
            shermanww.base_stats[S.health] = 400f;
            shermanww.base_stats[S.speed] = 30f;
            shermanww.base_stats[S.armor] = 40f;
            shermanww.base_stats[S.damage] = 10f;
            shermanww.base_stats[S.scale] = 0.2f;
            shermanww.base_stats[S.projectiles] = 5f;
            shermanww.base_stats[S.attack_speed] = 500;
			shermanww.base_stats[S.range] = 100f;
			shermanww.base_stats[S.knockback_reduction] = 300f;
            shermanww.immune_to_injuries = true;
            shermanww.inspect_stats = true;
			shermanww.landCreature = true;
			shermanww.inspect_home = true;
			shermanww.hideOnMinimap = false;
            shermanww.drawBoatMark = true;
			shermanww.can_edit_traits = true;
                 shermanww.disablePunchAttackAnimation = true;
			shermanww.canReceiveTraits = true;
			shermanww.flying = false;
			//shermanww.tech = "MissileSystems";
			shermanww.very_high_flyer = false;
			shermanww.defaultAttack = "missilelaunchershort";
            shermanww.has_skin = false;
			shermanww.dieOnBlocks = false;
			shermanww.ignoreBlocks = true;
			//shermanww.moveFromBlock = false;
			shermanww.procreate = false;
		    shermanww.inspect_children = false;
            shermanww.inspect_experience = true;
			shermanww.canBeCitizen = true;
            shermanww.inspect_kills = true;
            shermanww.use_items = false;
			shermanww.oceanCreature = false;
            shermanww.take_items = false;
            shermanww.nameLocale = "shermanww";
            shermanww.nameTemplate = "Jet_Names";
			shermanww.job = "attacker";
            shermanww.icon = "iconMissileSystem";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "MissileSystem");
			AssetManager.actor_library.CallMethod("loadShadow", shermanww);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            shermanww.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            shermanww.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            shermanww.animation_idle = "walk_0";
            shermanww.texture_path = "shermanww";
			AssetManager.actor_library.addColorSet("heliColor");
			shermanww.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(shermanww);
			Localization.addLocalization(shermanww.nameLocale, shermanww.nameLocale);

            var Railgun = AssetManager.actor_library.clone("Railgun", "_mob");
            //ActorAsset heli = new ActorAsset();
            // Tank.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
            Railgun.race = "human";
            Railgun.kingdom = "ModernKingdom";
            Railgun.base_stats[S.max_age] = 50f;
            Railgun.base_stats[S.health] = 1000f;
            Railgun.base_stats[S.speed] = 30f;
            Railgun.base_stats[S.armor] = 60f;
            Railgun.base_stats[S.damage] = 60f;
            Railgun.base_stats[S.attack_speed] = 0;
            Railgun.base_stats[S.scale] = 0.2f;
            Railgun.base_stats[S.range] = 150f;
            Railgun.base_stats[S.knockback_reduction] = 320f;
            Railgun.immune_to_injuries = true;
            Railgun.inspect_stats = true;
              Railgun.disablePunchAttackAnimation = true;
            Railgun.landCreature = true;
            Railgun.inspect_home = true;
            Railgun.hideOnMinimap = false;
            Railgun.drawBoatMark = true;
            Railgun.can_edit_traits = true;
            Railgun.canReceiveTraits = true;
            Railgun.flying = false;
            //Tank.tech = "Tanks";
            Railgun.very_high_flyer = false;
            Railgun.defaultAttack = "tankshellattack";
            Railgun.has_skin = false;
            Railgun.dieOnBlocks = true;
            Railgun.ignoreBlocks = false;
            //Tank.moveFromBlock = false;
            Railgun.procreate = false;
            Railgun.inspect_children = false;
            Railgun.inspect_experience = true;
            Railgun.canBeCitizen = true;
            Railgun.inspect_kills = true;
            Railgun.use_items = false;
            Railgun.oceanCreature = false;
            Railgun.take_items = false;
            Railgun.nameLocale = "Railgun";
            Railgun.nameTemplate = "Jet_Names";
            Railgun.job = "attacker";
            Railgun.icon = "iconRailgun";
            AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
            AssetManager.actor_library.CallMethod("addTrait", "Railgun");
            AssetManager.actor_library.CallMethod("loadShadow", Railgun);
            AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
             AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            Railgun.animation_walk = "walk_0,walk_1,walk_2";
            Railgun.animation_idle = "walk_0";
            Railgun.animation_swim = "swim_0,swim_1,swim_2";
            Railgun.texture_path = "Railgun";
            AssetManager.actor_library.addColorSet("heliColor");
            Railgun.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(Railgun);
            Localization.addLocalization(Railgun.nameLocale, Railgun.nameLocale);

            var OmegaRailgun = AssetManager.actor_library.clone("OmegaRailgun", "_mob");
            //ActorAsset heli = new ActorAsset();
            // Tank.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
            OmegaRailgun.race = "human";
            OmegaRailgun.kingdom = "ModernKingdom";
            OmegaRailgun.base_stats[S.max_age] = 50f;
            OmegaRailgun.base_stats[S.health] = 1200f;
            OmegaRailgun.base_stats[S.speed] = 20f;
            OmegaRailgun.base_stats[S.armor] = 70f;
            OmegaRailgun.base_stats[S.damage] = 100f;
            OmegaRailgun.base_stats[S.scale] = 0.2f;
            OmegaRailgun.base_stats[S.attack_speed] = 0;
            OmegaRailgun.base_stats[S.range] = 200f;
            OmegaRailgun.base_stats[S.knockback_reduction] = 320f;
            OmegaRailgun.immune_to_injuries = true;
            OmegaRailgun.inspect_stats = true;
              OmegaRailgun.disablePunchAttackAnimation = true;
            OmegaRailgun.landCreature = true;
            OmegaRailgun.inspect_home = true;
            OmegaRailgun.hideOnMinimap = false;
            OmegaRailgun.drawBoatMark = true;
            OmegaRailgun.can_edit_traits = true;
            OmegaRailgun.canReceiveTraits = true;
            OmegaRailgun.flying = false;
            //Tank.tech = "Tanks";
            OmegaRailgun.very_high_flyer = false;
            OmegaRailgun.defaultAttack = "tankshellattack";
            OmegaRailgun.has_skin = false;
            OmegaRailgun.dieOnBlocks = true;
            OmegaRailgun.ignoreBlocks = false;
            //Tank.moveFromBlock = false;
            OmegaRailgun.procreate = false;
            OmegaRailgun.inspect_children = false;
            OmegaRailgun.inspect_experience = true;
            OmegaRailgun.canBeCitizen = true;
            OmegaRailgun.inspect_kills = true;
            OmegaRailgun.use_items = false;
            OmegaRailgun.oceanCreature = false;
            OmegaRailgun.take_items = false;
            OmegaRailgun.nameLocale = "OmegaRailgun";
            OmegaRailgun.nameTemplate = "Jet_Names";
            OmegaRailgun.job = "attacker";
            OmegaRailgun.icon = "iconRailgun";
            AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
            AssetManager.actor_library.CallMethod("addTrait", "Railgun");
             AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            AssetManager.actor_library.CallMethod("loadShadow", OmegaRailgun);
            AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            OmegaRailgun.animation_walk = "walk_0,walk_1,walk_2";
            OmegaRailgun.animation_idle = "walk_0";
            OmegaRailgun.animation_swim = "swim_0,swim_1,swim_2";
            OmegaRailgun.texture_path = "OmegaRailgun";
            AssetManager.actor_library.addColorSet("heliColor");
            OmegaRailgun.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(OmegaRailgun);
            Localization.addLocalization(OmegaRailgun.nameLocale, OmegaRailgun.nameLocale);

            var Humvee = AssetManager.actor_library.clone("Humvee","_mob");
			//ActorAsset heli = new ActorAsset();
           // Humvee.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			Humvee.race = "human";
			Humvee.kingdom = "ModernKingdom";
			Humvee.base_stats[S.max_age] = 50f;
            Humvee.base_stats[S.health] = 250f;
            Humvee.base_stats[S.speed] = 100f;
            Humvee.base_stats[S.armor] = 20f;
            Humvee.base_stats[S.damage] = 10f;
            Humvee.base_stats[S.scale] = 0.1f;
            Humvee.base_stats[S.attack_speed] = 0;
			Humvee.base_stats[S.range] = 20f;
			Humvee.base_stats[S.knockback_reduction] = 300f;
            Humvee.immune_to_injuries = true;
            Humvee.inspect_stats = true;
			Humvee.landCreature = true;
			Humvee.inspect_home = true;
			Humvee.hideOnMinimap = false;
            Humvee.drawBoatMark = true;
			Humvee.can_edit_traits = true;
			Humvee.canReceiveTraits = true;
			Humvee.flying = false;
			//Humvee.tech = "Humvees";
			Humvee.very_high_flyer = false;
            Humvee.has_skin = false;
			Humvee.dieOnBlocks = false;
			Humvee.ignoreBlocks = false;
			Humvee.moveFromBlock = true;
			Humvee.procreate = false;
		    Humvee.inspect_children = false;
            Humvee.inspect_experience = true;
              Humvee.disablePunchAttackAnimation = true;
			Humvee.defaultAttack = "Minigun";
			Humvee.canBeCitizen = true;
            Humvee.inspect_kills = true;
            Humvee.use_items = false;
			Humvee.oceanCreature = false;
            Humvee.take_items = false;
            Humvee.nameLocale = "Humvee";
            Humvee.nameTemplate = "Humvee_Names";
			Humvee.job = "attacker";
            Humvee.icon = "iconHumvee";
			AssetManager.actor_library.CallMethod("addTrait", "Humvee");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", Humvee);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            Humvee.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			Humvee.animation_idle = "walk_0";
            Humvee.animation_swim = "swim_0,swim_1,swim_2,swim_4";
            Humvee.texture_path = "Humvee";
			AssetManager.actor_library.addColorSet("heliColor");
			Humvee.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(Humvee);
			Localization.addLocalization(Humvee.nameLocale, Humvee.nameLocale);

                        var wwsupporttruck = AssetManager.actor_library.clone("wwsupporttruck","_mob");
			//ActorAsset heli = new ActorAsset();
           // wwsupporttruck.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			wwsupporttruck.race = "human";
			wwsupporttruck.kingdom = "ModernKingdom";
			wwsupporttruck.base_stats[S.max_age] = 50f;
            wwsupporttruck.base_stats[S.health] = 400f;
            wwsupporttruck.base_stats[S.speed] = 50f;
            wwsupporttruck.base_stats[S.armor] = 20f;
            wwsupporttruck.base_stats[S.damage] = 10f;
            wwsupporttruck.base_stats[S.scale] = 0.2f;
            wwsupporttruck.base_stats[S.attack_speed] = 0;
			wwsupporttruck.base_stats[S.range] = 20f;
			wwsupporttruck.base_stats[S.knockback_reduction] = 300f;
            wwsupporttruck.immune_to_injuries = true;
            wwsupporttruck.skipFightLogic = true;
            wwsupporttruck.inspect_stats = true;
			wwsupporttruck.landCreature = true;
			wwsupporttruck.inspect_home = true;
			wwsupporttruck.hideOnMinimap = false;
            wwsupporttruck.drawBoatMark = true;
			wwsupporttruck.can_edit_traits = true;
			wwsupporttruck.canReceiveTraits = true;
			wwsupporttruck.flying = false;
			//wwsupporttruck.tech = "wwsupporttrucks";
			wwsupporttruck.very_high_flyer = false;
            wwsupporttruck.has_skin = false;
			wwsupporttruck.dieOnBlocks = false;
			wwsupporttruck.ignoreBlocks = false;
			wwsupporttruck.moveFromBlock = true;
			wwsupporttruck.procreate = false;
		    wwsupporttruck.inspect_children = false;
            wwsupporttruck.inspect_experience = true;
              wwsupporttruck.disablePunchAttackAnimation = true;
			wwsupporttruck.canBeCitizen = true;
            wwsupporttruck.inspect_kills = true;
            wwsupporttruck.use_items = false;
			wwsupporttruck.oceanCreature = false;
            wwsupporttruck.take_items = false;
            wwsupporttruck.nameLocale = "wwsupporttruck";
            wwsupporttruck.nameTemplate = "Humvee_Names";
			wwsupporttruck.job = "attacker";
            wwsupporttruck.icon = "iconwwsupporttruck";
			AssetManager.actor_library.CallMethod("addTrait", "wwsupporttruck");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
            AssetManager.actor_library.CallMethod("addTrait", "SupportRole");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", wwsupporttruck);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            wwsupporttruck.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			wwsupporttruck.animation_idle = "walk_0";
            wwsupporttruck.animation_swim = "swim_0,swim_1,swim_2,swim_4";
            wwsupporttruck.texture_path = "wwsupporttruck";
			AssetManager.actor_library.addColorSet("heliColor");
			wwsupporttruck.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(wwsupporttruck);
			Localization.addLocalization(wwsupporttruck.nameLocale, wwsupporttruck.nameLocale);

              var modernsupporttruck = AssetManager.actor_library.clone("modernsupporttruck","_mob");
			//ActorAsset heli = new ActorAsset();
           // modernsupporttruck.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			modernsupporttruck.race = "human";
			modernsupporttruck.kingdom = "ModernKingdom";
			modernsupporttruck.base_stats[S.max_age] = 50f;
            modernsupporttruck.base_stats[S.health] = 500f;
            modernsupporttruck.base_stats[S.speed] = 70f;
            modernsupporttruck.base_stats[S.armor] = 20f;
            modernsupporttruck.base_stats[S.damage] = 10f;
            modernsupporttruck.base_stats[S.scale] = 0.2f;
            modernsupporttruck.base_stats[S.attack_speed] = 0;
			modernsupporttruck.base_stats[S.range] = 20f;
			modernsupporttruck.base_stats[S.knockback_reduction] = 300f;
            modernsupporttruck.immune_to_injuries = true;
            modernsupporttruck.skipFightLogic = true;
            modernsupporttruck.inspect_stats = true;
			modernsupporttruck.landCreature = true;
			modernsupporttruck.inspect_home = true;
			modernsupporttruck.hideOnMinimap = false;
            modernsupporttruck.drawBoatMark = true;
			modernsupporttruck.can_edit_traits = true;
			modernsupporttruck.canReceiveTraits = true;
			modernsupporttruck.flying = false;
			//modernsupporttruck.tech = "modernsupporttrucks";
			modernsupporttruck.very_high_flyer = false;
            modernsupporttruck.has_skin = false;
			modernsupporttruck.dieOnBlocks = false;
			modernsupporttruck.ignoreBlocks = false;
			modernsupporttruck.moveFromBlock = true;
			modernsupporttruck.procreate = false;
		    modernsupporttruck.inspect_children = false;
            modernsupporttruck.inspect_experience = true;
              modernsupporttruck.disablePunchAttackAnimation = true;
			modernsupporttruck.canBeCitizen = true;
            modernsupporttruck.inspect_kills = true;
            modernsupporttruck.use_items = false;
			modernsupporttruck.oceanCreature = false;
            modernsupporttruck.take_items = false;
            modernsupporttruck.nameLocale = "modernsupporttruck";
            modernsupporttruck.nameTemplate = "Humvee_Names";
			modernsupporttruck.job = "attacker";
            modernsupporttruck.icon = "iconmodernsupporttruck";
			AssetManager.actor_library.CallMethod("addTrait", "modernsupporttruck");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
            AssetManager.actor_library.CallMethod("addTrait", "SupportRole");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", modernsupporttruck);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            modernsupporttruck.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			modernsupporttruck.animation_idle = "walk_0";
            modernsupporttruck.animation_swim = "swim_0,swim_1,swim_2,swim_4";
            modernsupporttruck.texture_path = "modernsupporttruck";
			AssetManager.actor_library.addColorSet("heliColor");
			modernsupporttruck.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(modernsupporttruck);
			Localization.addLocalization(modernsupporttruck.nameLocale, modernsupporttruck.nameLocale);

             var modernhumvee = AssetManager.actor_library.clone("modernhumvee","_mob");
			//ActorAsset heli = new ActorAsset();
           // modernhumvee.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			modernhumvee.race = "human";
			modernhumvee.kingdom = "ModernKingdom";
			modernhumvee.base_stats[S.max_age] = 50f;
            modernhumvee.base_stats[S.health] = 400f;
            modernhumvee.base_stats[S.speed] = 100f;
            modernhumvee.base_stats[S.armor] = 20f;
            modernhumvee.base_stats[S.damage] = 15f;
            modernhumvee.base_stats[S.scale] = 0.1f;
            modernhumvee.base_stats[S.attack_speed] = 0;
			modernhumvee.base_stats[S.range] = 20f;
			modernhumvee.base_stats[S.knockback_reduction] = 300f;
            modernhumvee.immune_to_injuries = true;
            modernhumvee.inspect_stats = true;
			modernhumvee.landCreature = true;
			modernhumvee.inspect_home = true;
			modernhumvee.hideOnMinimap = false;
            modernhumvee.drawBoatMark = true;
			modernhumvee.can_edit_traits = true;
			modernhumvee.canReceiveTraits = true;
			modernhumvee.flying = false;
			//modernhumvee.tech = "modernhumvees";
			modernhumvee.very_high_flyer = false;
            modernhumvee.has_skin = false;
			modernhumvee.dieOnBlocks = false;
			modernhumvee.ignoreBlocks = false;
			modernhumvee.moveFromBlock = true;
			modernhumvee.procreate = false;
		    modernhumvee.inspect_children = false;
            modernhumvee.inspect_experience = true;
              modernhumvee.disablePunchAttackAnimation = true;
			modernhumvee.defaultAttack = "Minigun";
			modernhumvee.canBeCitizen = true;
            modernhumvee.inspect_kills = true;
            modernhumvee.use_items = false;
			modernhumvee.oceanCreature = false;
            modernhumvee.take_items = false;
            modernhumvee.nameLocale = "modernhumvee";
            modernhumvee.nameTemplate = "Humvee_Names";
			modernhumvee.job = "attacker";
            modernhumvee.icon = "iconmodernhumvee";
			AssetManager.actor_library.CallMethod("addTrait", "modernhumvee");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", modernhumvee);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            modernhumvee.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			modernhumvee.animation_idle = "walk_0";
            modernhumvee.animation_swim = "swim_0,swim_1,swim_2,swim_4";
            modernhumvee.texture_path = "modernhumvee";
			AssetManager.actor_library.addColorSet("heliColor");
			modernhumvee.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(modernhumvee);
			Localization.addLocalization(modernhumvee.nameLocale, modernhumvee.nameLocale);

                var teslatruckgun = AssetManager.actor_library.clone("teslatruckgun","_mob");
			//ActorAsset heli = new ActorAsset();
           // teslatruckgun.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			teslatruckgun.race = "human";
			teslatruckgun.kingdom = "ModernKingdom";
			teslatruckgun.base_stats[S.max_age] = 50f;
            teslatruckgun.base_stats[S.health] = 500f;
            teslatruckgun.base_stats[S.speed] = 100f;
            teslatruckgun.base_stats[S.armor] = 35f;
            teslatruckgun.base_stats[S.damage] = 25f;
            teslatruckgun.base_stats[S.scale] = 0.1f;
            teslatruckgun.base_stats[S.attack_speed] = 0;
			teslatruckgun.base_stats[S.range] = 20f;
			teslatruckgun.base_stats[S.knockback_reduction] = 300f;
            teslatruckgun.immune_to_injuries = true;
            teslatruckgun.inspect_stats = true;
			teslatruckgun.landCreature = true;
			teslatruckgun.inspect_home = true;
			teslatruckgun.hideOnMinimap = false;
            teslatruckgun.drawBoatMark = true;
			teslatruckgun.can_edit_traits = true;
			teslatruckgun.canReceiveTraits = true;
			teslatruckgun.flying = false;
			//teslatruckgun.tech = "teslatruckguns";
			teslatruckgun.very_high_flyer = false;
            teslatruckgun.has_skin = false;
			teslatruckgun.dieOnBlocks = false;
			teslatruckgun.ignoreBlocks = false;
			teslatruckgun.moveFromBlock = true;
			teslatruckgun.procreate = false;
		    teslatruckgun.inspect_children = false;
            teslatruckgun.inspect_experience = true;
              teslatruckgun.disablePunchAttackAnimation = true;
			teslatruckgun.defaultAttack = "Minigun";
			teslatruckgun.canBeCitizen = true;
            teslatruckgun.inspect_kills = true;
            teslatruckgun.use_items = false;
			teslatruckgun.oceanCreature = false;
            teslatruckgun.take_items = false;
            teslatruckgun.nameLocale = "teslatruckgun";
            teslatruckgun.nameTemplate = "Humvee_Names";
			teslatruckgun.job = "attacker";
            teslatruckgun.icon = "iconteslatruckgun";
			AssetManager.actor_library.CallMethod("addTrait", "teslatruckgun");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			 AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
			AssetManager.actor_library.CallMethod("loadShadow", teslatruckgun);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            teslatruckgun.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			teslatruckgun.animation_idle = "walk_0";
            teslatruckgun.animation_swim = "swim_0,swim_1,swim_2,swim_4";
            teslatruckgun.texture_path = "teslatruckgun";
			AssetManager.actor_library.addColorSet("heliColor");
			teslatruckgun.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(teslatruckgun);
			Localization.addLocalization(teslatruckgun.nameLocale, teslatruckgun.nameLocale);
		  

            			  var wheeledtank = AssetManager.actor_library.clone("wheeledtank","_mob");
			//ActorAsset heli = new ActorAsset();
           // wheeledtank.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			wheeledtank.race = "human";
			wheeledtank.kingdom = "ModernKingdom";
			wheeledtank.base_stats[S.max_age] = 50f;
            wheeledtank.base_stats[S.health] = 800f;
            wheeledtank.base_stats[S.speed] = 70f;
            wheeledtank.base_stats[S.armor] = 30f;
            wheeledtank.base_stats[S.damage] = 30f;
            wheeledtank.base_stats[S.scale] = 0.2f;
            wheeledtank.base_stats[S.attack_speed] = 0;
			wheeledtank.base_stats[S.range] = 30f;
			wheeledtank.base_stats[S.knockback_reduction] = 300f;
            wheeledtank.immune_to_injuries = true;
            wheeledtank.inspect_stats = true;
			wheeledtank.landCreature = true;
			wheeledtank.inspect_home = true;
			wheeledtank.hideOnMinimap = false;
            wheeledtank.drawBoatMark = true;
			wheeledtank.can_edit_traits = true;
			wheeledtank.canReceiveTraits = true;
			wheeledtank.flying = false;
			//wheeledtank.tech = "Humvees";
			wheeledtank.very_high_flyer = false;
            wheeledtank.has_skin = false;
			wheeledtank.dieOnBlocks = false;
			wheeledtank.ignoreBlocks = false;
			wheeledtank.moveFromBlock = true;
			wheeledtank.procreate = false;
		    wheeledtank.inspect_children = false;
            wheeledtank.inspect_experience = true;
              wheeledtank.disablePunchAttackAnimation = true;
			wheeledtank.defaultAttack = "tankshellattack";
			wheeledtank.canBeCitizen = true;
            wheeledtank.inspect_kills = true;
            wheeledtank.use_items = false;
			wheeledtank.oceanCreature = false;
            wheeledtank.take_items = false;
            wheeledtank.nameLocale = "wheeledtank";
            wheeledtank.nameTemplate = "Humvee_Names";
			wheeledtank.job = "attacker";
            wheeledtank.icon = "iconHumvee";
			AssetManager.actor_library.CallMethod("addTrait", "Humvee");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("loadShadow", wheeledtank);
			AssetManager.actor_library.CallMethod("addTrait", "light_lamp");
            AssetManager.actor_library.CallMethod("addTrait", "fire_proof");
            wheeledtank.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			wheeledtank.animation_idle = "walk_0";
            wheeledtank.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            wheeledtank.texture_path = "wheeledtank";
			AssetManager.actor_library.addColorSet("heliColor");
			wheeledtank.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(wheeledtank);
			Localization.addLocalization(wheeledtank.nameLocale, wheeledtank.nameLocale);

		  


		}
		}
}
