//========= MODERNBOX 2.1.0.1 ============//
//
// Made by Tuxxego
//
//=============================================================================//
using System;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using NCMS;
using NCMS.Utils;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using ReflectionUtility;
using HarmonyLib;

namespace M2
{
    class MedievalUnits : MonoBehaviour
    {

        public static void init()
        {
            loadAssets();

        }

        private static void loadAssets()
        {

// BASE UNITS
//
//=============================================================================//

            var baseoffensiveunit = AssetManager.actor_library.clone("baseoffensiveunit","_mob");
			//ActorAsset heli = new ActorAsset();
           // baseoffensiveunit.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			baseoffensiveunit.race = "human";
			baseoffensiveunit.kingdom = "ModernKingdom";
            baseoffensiveunit.base_stats[S.health] = 200000f;
            baseoffensiveunit.base_stats[S.speed] = 0f;
            baseoffensiveunit.base_stats[S.armor] = 0f;
            baseoffensiveunit.base_stats[S.damage] = 0f;
            baseoffensiveunit.base_stats[S.scale] = 0.1f;
            baseoffensiveunit.base_stats[S.attack_speed] = 0;
			baseoffensiveunit.base_stats[S.range] = 1f;
			baseoffensiveunit.base_stats[S.knockback_reduction] = 300f;
            baseoffensiveunit.drawBoatMark_big = true;
            baseoffensiveunit.has_ai_system = false;
            baseoffensiveunit.skipFightLogic = true;
            baseoffensiveunit.inspect_stats = true;
			baseoffensiveunit.landCreature = true;
			baseoffensiveunit.inspect_home = true;
			baseoffensiveunit.hideOnMinimap = false;
            baseoffensiveunit.drawBoatMark = true;
			baseoffensiveunit.can_edit_traits = true;
             baseoffensiveunit.disablePunchAttackAnimation = true;
			baseoffensiveunit.canReceiveTraits = true;
			baseoffensiveunit.flying = false;
			//baseoffensiveunit.tech = "baseoffensiveunits";
			baseoffensiveunit.very_high_flyer = false;
			baseoffensiveunit.defaultAttack = "base";
            baseoffensiveunit.isBoat = false;
			baseoffensiveunit.dieOnBlocks = true;
			baseoffensiveunit.ignoreBlocks = false;
			//baseoffensiveunit.moveFromBlock = false;
			baseoffensiveunit.procreate = false;
		    baseoffensiveunit.inspect_children = false;
            baseoffensiveunit.inspect_experience = true;
			baseoffensiveunit.canBeCitizen = true;
            baseoffensiveunit.inspect_kills = true;
            baseoffensiveunit.use_items = false;
			baseoffensiveunit.oceanCreature = false;
            baseoffensiveunit.take_items = false;
            baseoffensiveunit.nameLocale = "baseoffensiveunit";
            baseoffensiveunit.nameTemplate = "Jet_Names";
			baseoffensiveunit.job = "attacker";
            baseoffensiveunit.icon = "";
            baseoffensiveunit.texture_path = "cartbaseunit";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("loadShadow", baseoffensiveunit);
            baseoffensiveunit.animation_walk = "walk_0,walk_1,walk_2";
            baseoffensiveunit.animation_swim = "swim_0,swim_1,swim_2";
			AssetManager.actor_library.addColorSet("heliColor");
			baseoffensiveunit.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(baseoffensiveunit);
			Localization.addLocalization(baseoffensiveunit.nameLocale, baseoffensiveunit.nameLocale);

            			var basesupportunit = AssetManager.actor_library.clone("basesupportunit","_mob");
			//ActorAsset heli = new ActorAsset();
           // basesupportunit.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			basesupportunit.race = "human";
			basesupportunit.kingdom = "ModernKingdom";
            basesupportunit.base_stats[S.health] = 200000f;
            basesupportunit.base_stats[S.speed] = 0f;
            basesupportunit.base_stats[S.armor] = 0f;
            basesupportunit.base_stats[S.damage] = 0f;
            basesupportunit.base_stats[S.scale] = 0.1f;
            basesupportunit.base_stats[S.attack_speed] = 0;
			basesupportunit.base_stats[S.range] = 1f;
			basesupportunit.base_stats[S.knockback_reduction] = 300f;
            basesupportunit.drawBoatMark_big = true;
            basesupportunit.inspect_stats = true;
			basesupportunit.landCreature = true;
			basesupportunit.inspect_home = true;
			basesupportunit.hideOnMinimap = false;
            basesupportunit.drawBoatMark = true;
			basesupportunit.can_edit_traits = true;
             basesupportunit.disablePunchAttackAnimation = true;
			basesupportunit.canReceiveTraits = true;
			basesupportunit.flying = false;
			//basesupportunit.tech = "basesupportunits";
			basesupportunit.very_high_flyer = false;
			basesupportunit.defaultAttack = "base";
            basesupportunit.isBoat = false;
			basesupportunit.dieOnBlocks = true;
			basesupportunit.ignoreBlocks = false;
			//basesupportunit.moveFromBlock = false;
			basesupportunit.procreate = false;
		    basesupportunit.inspect_children = false;
            basesupportunit.inspect_experience = true;
			basesupportunit.canBeCitizen = true;
            basesupportunit.inspect_kills = true;
            basesupportunit.use_items = false;
			basesupportunit.oceanCreature = false;
            basesupportunit.take_items = false;
            basesupportunit.nameLocale = "basesupportunit";
            basesupportunit.nameTemplate = "Jet_Names";
			basesupportunit.job = "attacker";
            basesupportunit.icon = "";
            basesupportunit.texture_path = "cartbaseunit";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("loadShadow", basesupportunit);
            basesupportunit.animation_walk = "walk_0,walk_1,walk_2";
            basesupportunit.animation_swim = "swim_0,swim_1,swim_2";
			AssetManager.actor_library.addColorSet("heliColor");
			basesupportunit.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(basesupportunit);
			Localization.addLocalization(basesupportunit.nameLocale, basesupportunit.nameLocale);


// LONG RANGE/SIEGE
//
//=============================================================================//

        ProjectileAsset Stone = new ProjectileAsset();
          Stone.id = "Stone";
          Stone.texture = "Stone";
          Stone.trailEffect_enabled = false;
	      Stone.look_at_target = false;
          Stone.draw_light_area = false;
	      Stone.draw_light_size = 0.1f;
        Stone.endEffect = "groundshake";
          Stone.startScale = 0.075f;
          Stone.targetScale = 0.2f;
          Stone.parabolic = true;
         Stone.rotate = true;
          Stone.speed = 4f;
          AssetManager.projectiles.add(Stone);

            ItemAsset rockthrow = AssetManager.items.clone("rockthrow", "_range");
            rockthrow.id = "rockthrow";
            rockthrow.projectile = "Stone";
            rockthrow.materials = List.Of<string>(new string[] { "base" });
            rockthrow.base_stats[S.targets] = 1;
            rockthrow.base_stats[S.range] = 16f;
            rockthrow.base_stats[S.projectiles] = 1;
            rockthrow.path_slash_animation = "effects/slashes/slash_punch";

			var catapulta = AssetManager.actor_library.clone("catapulta","_mob");
			//ActorAsset heli = new ActorAsset();
           // catapulta.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			catapulta.race = "human";
			catapulta.kingdom = "MissileLauncherFULLRANGETARGETTING";
            catapulta.texture_path = "catapulta";
			catapulta.base_stats[S.max_age] = 50f;
            catapulta.base_stats[S.health] = 400f;
            catapulta.base_stats[S.speed] = 20f;
            catapulta.base_stats[S.armor] = 30f;
            catapulta.base_stats[S.damage] = 40f;
            catapulta.base_stats[S.scale] = 0.2f;
            catapulta.base_stats[S.attack_speed] = -300;
			catapulta.base_stats[S.range] = 34f;
			catapulta.base_stats[S.knockback_reduction] = 10f;
            catapulta.drawBoatMark_big = true;
            catapulta.inspect_stats = true;
			catapulta.landCreature = true;
			catapulta.has_skin = false;
			catapulta.immune_to_injuries = true;
			catapulta.inspect_home = true;
			catapulta.hideOnMinimap = false;
            catapulta.drawBoatMark = true;
			catapulta.can_edit_traits = true;
            catapulta.disablePunchAttackAnimation = true;
			catapulta.canReceiveTraits = true;
			catapulta.flying = false;
			//catapulta.tech = "catapultas";
			catapulta.very_high_flyer = false;
			catapulta.defaultAttack = "rockthrow";
            catapulta.isBoat = false;
			catapulta.dieOnBlocks = false;
			catapulta.ignoreBlocks = true;
			//catapulta.moveFromBlock = false;
			catapulta.procreate = false;
		    catapulta.inspect_children = false;
            catapulta.inspect_experience = true;
			catapulta.canBeCitizen = true;
            catapulta.inspect_kills = true;
            catapulta.use_items = false;
			catapulta.oceanCreature = false;
            catapulta.take_items = false;
            catapulta.nameLocale = "catapulta";
            catapulta.nameTemplate = "Jet_Names";
			catapulta.job = "attacker";
            catapulta.icon = "iconcatapulta";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "catapulta");
			AssetManager.actor_library.CallMethod("loadShadow", catapulta);
            catapulta.animation_walk = "walk_0,walk_1,walk_2";
            catapulta.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            catapulta.animation_idle = "idle_0,idle_1,idle_2,idle_1";
			AssetManager.actor_library.addColorSet("heliColor");
			catapulta.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(catapulta);
			Localization.addLocalization(catapulta.nameLocale, catapulta.nameLocale);

            	var orcatapulta = AssetManager.actor_library.clone("orcatapulta","_mob");
			//ActorAsset heli = new ActorAsset();
           // orcatapulta.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			orcatapulta.race = "orc";
			orcatapulta.kingdom = "MissileLauncherFULLRANGETARGETTING";
            orcatapulta.texture_path = "orcatapulta";
            orcatapulta.base_stats[S.max_age] = 50f;
            orcatapulta.base_stats[S.health] = 400f;
            orcatapulta.base_stats[S.speed] = 20f;
            orcatapulta.base_stats[S.armor] = 30f;
            orcatapulta.base_stats[S.damage] = 40f;
            orcatapulta.base_stats[S.scale] = 0.2f;
            orcatapulta.base_stats[S.attack_speed] = -300;
			orcatapulta.base_stats[S.range] = 34f;
			orcatapulta.base_stats[S.knockback_reduction] = 10f;
            orcatapulta.drawBoatMark_big = true;
            orcatapulta.inspect_stats = true;
			orcatapulta.landCreature = true;
			orcatapulta.inspect_home = true;
			orcatapulta.hideOnMinimap = false;
            orcatapulta.drawBoatMark = true;
			orcatapulta.can_edit_traits = true;
            orcatapulta.disablePunchAttackAnimation = true;
			orcatapulta.canReceiveTraits = true;
			orcatapulta.flying = false;
			//orcatapulta.tech = "orcatapultas";
			orcatapulta.very_high_flyer = false;
			orcatapulta.defaultAttack = "rockthrow";
            orcatapulta.isBoat = false;
			orcatapulta.dieOnBlocks = false;
			orcatapulta.ignoreBlocks = true;
			orcatapulta.has_skin = false;
			orcatapulta.immune_to_injuries = true;
			//orcatapulta.moveFromBlock = false;
			orcatapulta.procreate = false;
		    orcatapulta.inspect_children = false;
            orcatapulta.inspect_experience = true;
			orcatapulta.canBeCitizen = true;
            orcatapulta.inspect_kills = true;
            orcatapulta.use_items = false;
			orcatapulta.oceanCreature = false;
            orcatapulta.take_items = false;
            orcatapulta.nameLocale = "orcatapulta";
            orcatapulta.nameTemplate = "Jet_Names";
			orcatapulta.job = "attacker";
            orcatapulta.icon = "iconorcatapulta";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "orcatapulta");
			AssetManager.actor_library.CallMethod("loadShadow", orcatapulta);
            orcatapulta.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            orcatapulta.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            orcatapulta.animation_idle = "idle_0,idle_1,idle_2,idle_1";
			AssetManager.actor_library.addColorSet("heliColor");
			orcatapulta.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(orcatapulta);
			Localization.addLocalization(orcatapulta.nameLocale, orcatapulta.nameLocale);



         ProjectileAsset yugesnowball = new ProjectileAsset();
          yugesnowball.id = "yugesnowball";
          yugesnowball.texture = "snowball";
          yugesnowball.trailEffect_enabled = false;
	      yugesnowball.look_at_target = true;
          yugesnowball.draw_light_area = false;
	      yugesnowball.draw_light_size = 0.1f;
          yugesnowball.hitFreeze = true;
          yugesnowball.startScale = 0.25f;
          yugesnowball.targetScale = 0.5f;
          yugesnowball.parabolic = true;
          yugesnowball.rotate = true;
          yugesnowball.speed = 4f;
          AssetManager.projectiles.add(yugesnowball);

             ItemAsset snowballindaface = AssetManager.items.clone("snowballindaface", "_range");
            snowballindaface.id = "snowballindaface";
            snowballindaface.projectile = "yugesnowball";
            snowballindaface.materials = List.Of<string>(new string[] { "base" });
            snowballindaface.base_stats[S.targets] = 10;
            snowballindaface.base_stats[S.range] = 16f;
            snowballindaface.base_stats[S.projectiles] = 1;
            snowballindaface.base_stats[S.critical_chance] = 0.3f;
		    snowballindaface.base_stats[S.critical_damage_multiplier] = 0.8f;
            snowballindaface.item_modifiers = List.Of<string>("ice");
            snowballindaface.path_slash_animation = "effects/slashes/slash_punch";

            var santaguin = AssetManager.actor_library.clone("santaguin","_mob");
			//ActorAsset heli = new ActorAsset();
           // santaguin.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			santaguin.race = "dwarf";
			santaguin.kingdom = "MissileLauncherFULLRANGETARGETTING";
            santaguin.texture_path = "santaguin";
            santaguin.base_stats[S.max_age] = 50f;
            santaguin.base_stats[S.health] = 400f;
            santaguin.base_stats[S.speed] = 20f;
            santaguin.base_stats[S.armor] = 30f;
            santaguin.base_stats[S.damage] = 40f;
            santaguin.base_stats[S.scale] = 0.2f;
            santaguin.base_stats[S.attack_speed] = -300;
			santaguin.base_stats[S.range] = 34f;
			santaguin.base_stats[S.knockback_reduction] = 10f;
            santaguin.drawBoatMark_big = true;
            santaguin.inspect_stats = true;
			santaguin.landCreature = true;
			santaguin.inspect_home = true;
			santaguin.hideOnMinimap = false;
            santaguin.drawBoatMark = true;
			santaguin.can_edit_traits = true;
            santaguin.disablePunchAttackAnimation = true;
			santaguin.canReceiveTraits = true;
			santaguin.flying = false;
			//santaguin.tech = "santaguins";
			santaguin.very_high_flyer = false;
			santaguin.defaultAttack = "snowballindaface";
            santaguin.isBoat = false;
			santaguin.dieOnBlocks = false;
			santaguin.ignoreBlocks = true;
			//santaguin.moveFromBlock = false;
			santaguin.procreate = false;
		    santaguin.inspect_children = false;
            santaguin.inspect_experience = true;
			santaguin.canBeCitizen = true;
            santaguin.inspect_kills = true;
            santaguin.use_items = false;
			santaguin.oceanCreature = false;
            santaguin.take_items = false;
            santaguin.nameLocale = "santaguin";
            santaguin.nameTemplate = "Jet_Names";
			santaguin.job = "attacker";
            santaguin.icon = "iconsantaguin";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "santaguin");
			AssetManager.actor_library.CallMethod("loadShadow", santaguin);
            santaguin.animation_walk = "walk_0,walk_1,walk_2";
            santaguin.animation_swim = "swim_0,swim_1,swim_2";
			AssetManager.actor_library.addColorSet("heliColor");
			santaguin.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(santaguin);
			Localization.addLocalization(santaguin.nameLocale, santaguin.nameLocale);

            var woolyrhino = AssetManager.actor_library.clone("woolyrhino","_mob");
			//ActorAsset heli = new ActorAsset();
           // woolyrhino.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			woolyrhino.race = "elf";
			woolyrhino.kingdom = "MissileLauncherFULLRANGETARGETTING";
            woolyrhino.texture_path = "woolyrhino";
            woolyrhino.base_stats[S.max_age] = 50f;
            woolyrhino.base_stats[S.health] = 400f;
            woolyrhino.base_stats[S.speed] = 60f;
            woolyrhino.base_stats[S.armor] = 30f;
            woolyrhino.base_stats[S.targets] = 6f;
            woolyrhino.base_stats[S.damage] = 60f;
            woolyrhino.base_stats[S.scale] = 0.2f;
            woolyrhino.base_stats[S.attack_speed] = -300;
			woolyrhino.base_stats[S.knockback] = 3f;
			woolyrhino.base_stats[S.knockback_reduction] = 10f;
            woolyrhino.drawBoatMark_big = true;
            woolyrhino.inspect_stats = true;
			woolyrhino.landCreature = true;
			woolyrhino.inspect_home = true;
			woolyrhino.hideOnMinimap = false;
            woolyrhino.drawBoatMark = true;
			woolyrhino.can_edit_traits = true;
            woolyrhino.disablePunchAttackAnimation = true;
			woolyrhino.canReceiveTraits = true;
			woolyrhino.flying = false;
			//woolyrhino.tech = "woolyrhinos";
			woolyrhino.very_high_flyer = false;
			woolyrhino.defaultAttack = "base";
            woolyrhino.isBoat = false;
			woolyrhino.dieOnBlocks = false;
			woolyrhino.ignoreBlocks = true;
			//woolyrhino.moveFromBlock = false;
			woolyrhino.procreate = false;
		    woolyrhino.inspect_children = false;
            woolyrhino.inspect_experience = true;
			woolyrhino.canBeCitizen = true;
            woolyrhino.inspect_kills = true;
            woolyrhino.use_items = false;
			woolyrhino.oceanCreature = false;
            woolyrhino.take_items = false;
            woolyrhino.nameLocale = "woolyrhino";
            woolyrhino.nameTemplate = "Jet_Names";
			woolyrhino.job = "attacker";
            woolyrhino.icon = "iconwoolyrhino";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "woolyrhino");
			AssetManager.actor_library.CallMethod("loadShadow", woolyrhino);
            woolyrhino.animation_walk = "walk_0,walk_1,walk_2";
            woolyrhino.animation_swim = "swim_0,swim_1,swim_2";
			AssetManager.actor_library.addColorSet("heliColor");
			woolyrhino.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(woolyrhino);
			Localization.addLocalization(woolyrhino.nameLocale, woolyrhino.nameLocale);

            var batteringram = AssetManager.actor_library.clone("batteringram","_mob");
			//ActorAsset heli = new ActorAsset();
           // batteringram.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			batteringram.race = "human";
			batteringram.kingdom = "MissileLauncherFULLRANGETARGETTING";
            batteringram.texture_path = "batteringram";
            batteringram.base_stats[S.max_age] = 50f;
            batteringram.base_stats[S.health] = 400f;
            batteringram.base_stats[S.speed] = 60f;
            batteringram.base_stats[S.armor] = 30f;
            batteringram.base_stats[S.targets] = 6f;
            batteringram.base_stats[S.damage] = 60f;
            batteringram.base_stats[S.scale] = 0.2f;
            batteringram.base_stats[S.attack_speed] = -300;
			batteringram.base_stats[S.knockback] = 3f;
			batteringram.base_stats[S.knockback_reduction] = 10f;
            batteringram.drawBoatMark_big = true;
            batteringram.inspect_stats = true;
			batteringram.landCreature = true;
			batteringram.inspect_home = true;
			batteringram.hideOnMinimap = false;
            batteringram.drawBoatMark = true;
			batteringram.can_edit_traits = true;
            batteringram.disablePunchAttackAnimation = true;
			batteringram.canReceiveTraits = true;
			batteringram.flying = false;
			//batteringram.tech = "batteringrams";
			batteringram.very_high_flyer = false;
			batteringram.defaultAttack = "base";
            batteringram.isBoat = false;
			batteringram.dieOnBlocks = false;
			batteringram.has_skin = false;
			batteringram.immune_to_injuries = true;
			batteringram.ignoreBlocks = true;
			//batteringram.moveFromBlock = false;
			batteringram.procreate = false;
		    batteringram.inspect_children = false;
            batteringram.inspect_experience = true;
			batteringram.canBeCitizen = true;
            batteringram.inspect_kills = true;
            batteringram.use_items = false;
			batteringram.oceanCreature = false;
            batteringram.take_items = false;
            batteringram.nameLocale = "batteringram";
            batteringram.nameTemplate = "Jet_Names";
			batteringram.job = "attacker";
            batteringram.icon = "iconbatteringram";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "batteringram");
			AssetManager.actor_library.CallMethod("loadShadow", batteringram);
            batteringram.animation_walk = "walk_0,walk_1,walk_2";
            batteringram.animation_swim = "swim_0";
            batteringram.animation_idle = "idle_0,idle_1,idle_2";
			AssetManager.actor_library.addColorSet("heliColor");
			batteringram.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(batteringram);
			Localization.addLocalization(batteringram.nameLocale, batteringram.nameLocale);

// TROOPS
//
//=============================================================================//

		var humancavalry = AssetManager.actor_library.clone("humancavalry","_mob");
			//ActorAsset heli = new ActorAsset();
           // humancavalry.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			humancavalry.race = "human";
			humancavalry.kingdom = "ModernKingdom";
			humancavalry.base_stats[S.max_age] = 50f;
            humancavalry.base_stats[S.health] = 200f;
            humancavalry.base_stats[S.speed] = 80f;
            humancavalry.base_stats[S.armor] = 15f;
            humancavalry.base_stats[S.damage] = 30f;
            humancavalry.base_stats[S.scale] = 0.1f;
            humancavalry.base_stats[S.attack_speed] = 30;
			humancavalry.base_stats[S.targets] = 2f;
            humancavalry.defaultAttack = "base";
            humancavalry.drawBoatMark_big = true;
            humancavalry.inspect_stats = true;
			humancavalry.landCreature = true;
			humancavalry.inspect_home = true;
			humancavalry.hideOnMinimap = false;
            humancavalry.drawBoatMark = true;
			humancavalry.can_edit_traits = true;
			humancavalry.canReceiveTraits = true;
			humancavalry.flying = false;
			//humancavalry.tech = "humancavalrys";
			humancavalry.very_high_flyer = false;
            humancavalry.isBoat = false;
			humancavalry.dieOnBlocks = false;
			humancavalry.ignoreBlocks = false;
			humancavalry.moveFromBlock = true;
			humancavalry.procreate = false;
		    humancavalry.inspect_children = false;
            humancavalry.inspect_experience = true;
			humancavalry.canBeCitizen = true;
            humancavalry.inspect_kills = true;
            humancavalry.use_items = false;
			humancavalry.oceanCreature = false;
            humancavalry.take_items = false;
            humancavalry.nameLocale = "humancavalry";
            humancavalry.nameTemplate = "Modern_Names";
			humancavalry.job = "attacker";
            humancavalry.icon = "iconhumancavalry";
			//AssetManager.actor_library.CallMethod("addTrait", "humancavalry");
			AssetManager.actor_library.CallMethod("loadShadow", humancavalry);
            humancavalry.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			humancavalry.animation_idle = "walk_0";
            humancavalry.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            humancavalry.texture_path = "humancavalry";
			AssetManager.actor_library.addColorSet("heliColor");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			humancavalry.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(humancavalry);
			Localization.addLocalization(humancavalry.nameLocale, humancavalry.nameLocale);

		var ogreunit = AssetManager.actor_library.clone("ogreunit","_mob");
			//ActorAsset heli = new ActorAsset();
           // ogreunit.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			ogreunit.race = "orc";
			ogreunit.kingdom = "ModernKingdom";
			ogreunit.base_stats[S.max_age] = 50f;
            ogreunit.base_stats[S.health] = 250f;
            ogreunit.base_stats[S.speed] = 30f;
            ogreunit.base_stats[S.armor] = 0f;
            ogreunit.base_stats[S.damage] = 20f;
            ogreunit.base_stats[S.scale] = 0.2f;
            ogreunit.base_stats[S.attack_speed] = 300;
			ogreunit.base_stats[S.targets] = 4f;
            ogreunit.drawBoatMark_big = true;
            ogreunit.inspect_stats = true;
			ogreunit.landCreature = true;
			ogreunit.inspect_home = true;
			ogreunit.hideOnMinimap = false;
            ogreunit.drawBoatMark = true;
			ogreunit.can_edit_traits = true;
			ogreunit.canReceiveTraits = true;
			ogreunit.flying = false;
			//ogreunit.tech = "ogreunits";
			ogreunit.very_high_flyer = false;
            ogreunit.isBoat = false;
			ogreunit.dieOnBlocks = false;
			ogreunit.ignoreBlocks = false;
			ogreunit.moveFromBlock = true;
			ogreunit.procreate = false;
		    ogreunit.inspect_children = false;
            ogreunit.inspect_experience = true;
			ogreunit.defaultWeapons = List.Of<string>(new string[]
				{
			 "spear",
			 "axe"
				});
			ogreunit.defaultWeaponsMaterial = List.Of<string>(new string[]
				{
				 "stone"
				});
			ogreunit.canBeCitizen = true;
            ogreunit.inspect_kills = true;
            ogreunit.use_items = true;
			ogreunit.oceanCreature = false;
            ogreunit.take_items = true;
            ogreunit.nameLocale = "ogreunit";
            ogreunit.nameTemplate = "Modern_Names";
			ogreunit.job = "attacker";
            ogreunit.icon = "iconogreunit";
			//AssetManager.actor_library.CallMethod("addTrait", "ogreunit");
			AssetManager.actor_library.CallMethod("loadShadow", ogreunit);
            ogreunit.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			ogreunit.animation_idle = "walk_0";
            ogreunit.animation_swim = "swim_0,swim_1,swim_0,swim_1";
            ogreunit.texture_path = "ogreunit";
			AssetManager.actor_library.addColorSet("heliColor");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			ogreunit.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(ogreunit);
			Localization.addLocalization(ogreunit.nameLocale, ogreunit.nameLocale);

var golemgem = AssetManager.actor_library.clone("golemgem","_mob");
			//ActorAsset heli = new ActorAsset();
           // golemgem.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			golemgem.race = "dwarf";
			golemgem.kingdom = "ModernKingdom";
			golemgem.base_stats[S.max_age] = 50f;
            golemgem.base_stats[S.health] = 200f;
            golemgem.base_stats[S.speed] = 40f;
            golemgem.base_stats[S.armor] = 35f;
            golemgem.base_stats[S.damage] = 20f;
            golemgem.base_stats[S.scale] = 0.1f;
            golemgem.base_stats[S.attack_speed] = 30;
			golemgem.base_stats[S.targets] = 4f;
            golemgem.defaultAttack = "base";
            golemgem.drawBoatMark_big = true;
            golemgem.inspect_stats = true;
			golemgem.landCreature = true;
			golemgem.inspect_home = true;
			golemgem.hideOnMinimap = false;
            golemgem.drawBoatMark = true;
			golemgem.can_edit_traits = true;
			golemgem.canReceiveTraits = true;
			golemgem.flying = false;
			//golemgem.tech = "golemgems";
			golemgem.very_high_flyer = false;
            golemgem.isBoat = false;
            golemgem.has_skin = false;
			golemgem.immune_to_injuries = true;
			golemgem.dieOnBlocks = false;
			golemgem.ignoreBlocks = false;
			golemgem.moveFromBlock = true;
			golemgem.procreate = false;
		    golemgem.inspect_children = false;
            golemgem.inspect_experience = true;
			golemgem.canBeCitizen = true;
            golemgem.inspect_kills = true;
            golemgem.use_items = false;
			golemgem.oceanCreature = false;
            golemgem.take_items = false;
            golemgem.nameLocale = "golemgem";
            golemgem.nameTemplate = "Modern_Names";
			golemgem.job = "attacker";
            golemgem.icon = "icongolemgem";
			//AssetManager.actor_library.CallMethod("addTrait", "golemgem");
			AssetManager.actor_library.CallMethod("loadShadow", golemgem);
            golemgem.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			golemgem.animation_idle = "walk_0";
            golemgem.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            golemgem.texture_path = "golemgem";
			AssetManager.actor_library.addColorSet("heliColor");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			golemgem.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(golemgem);
			Localization.addLocalization(golemgem.nameLocale, golemgem.nameLocale);

            var treant = AssetManager.actor_library.clone("treant","_mob");
			//ActorAsset heli = new ActorAsset();
           // treant.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			treant.race = "elf";
			treant.kingdom = "ModernKingdom";
			treant.base_stats[S.max_age] = 50f;
            treant.base_stats[S.health] = 200f;
            treant.base_stats[S.speed] = 40f;
            treant.base_stats[S.armor] = 35f;
            treant.base_stats[S.damage] = 35f;
            treant.base_stats[S.scale] = 0.2f;
            treant.base_stats[S.attack_speed] = 300;
			treant.base_stats[S.targets] = 1f;
            treant.defaultAttack = "base";
            treant.drawBoatMark_big = true;
            treant.inspect_stats = true;
			treant.landCreature = true;
			treant.inspect_home = true;
			treant.hideOnMinimap = false;
            treant.drawBoatMark = true;
			treant.can_edit_traits = true;
			treant.canReceiveTraits = true;
			treant.flying = false;
			//treant.tech = "treants";
			treant.very_high_flyer = false;
            treant.isBoat = false;
			treant.dieOnBlocks = false;
			treant.ignoreBlocks = false;
			treant.moveFromBlock = true;
			treant.procreate = false;
		    treant.inspect_children = false;
            treant.inspect_experience = true;
			treant.canBeCitizen = true;
			treant.immune_to_injuries = true;
            treant.inspect_kills = true;
            treant.use_items = false;
			treant.oceanCreature = false;
            treant.take_items = false;
            treant.nameLocale = "treant";
            treant.nameTemplate = "Modern_Names";
			treant.job = "attacker";
            treant.icon = "icontreant";
			//AssetManager.actor_library.CallMethod("addTrait", "treant");
			AssetManager.actor_library.CallMethod("loadShadow", treant);
            treant.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			treant.animation_idle = "walk_0";
            treant.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            treant.texture_path = "treant";
			AssetManager.actor_library.addColorSet("heliColor");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			treant.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(treant);
			Localization.addLocalization(treant.nameLocale, treant.nameLocale);

            var armoredwolf = AssetManager.actor_library.clone("armoredwolf","_mob");
			//ActorAsset heli = new ActorAsset();
           // armoredwolf.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			armoredwolf.race = "orc";
			armoredwolf.kingdom = "ModernKingdom";
			armoredwolf.base_stats[S.max_age] = 50f;
			armoredwolf.base_stats[S.health] = 300f;
          armoredwolf.base_stats[S.speed] = 75f;
		armoredwolf.canAttackBuildings = true;
		armoredwolf.base_stats[S.attack_speed] = 200f;
		armoredwolf.base_stats[S.damage] = 30f;
		armoredwolf.base_stats[S.knockback] = 0.8f;
        armoredwolf.base_stats[S.scale] = 0.2f;
		armoredwolf.procreate = false;
		armoredwolf.canTurnIntoZombie = true;
		armoredwolf.zombieID = SA.zombie_wolf;
            armoredwolf.defaultAttack = "jaws";
            armoredwolf.drawBoatMark_big = true;
            armoredwolf.inspect_stats = true;
			armoredwolf.landCreature = true;
			armoredwolf.inspect_home = true;
			armoredwolf.hideOnMinimap = false;
            armoredwolf.drawBoatMark = true;
			armoredwolf.can_edit_traits = true;
			armoredwolf.canReceiveTraits = true;
			armoredwolf.flying = false;
			//armoredwolf.tech = "armoredwolfs";
			armoredwolf.very_high_flyer = false;
            armoredwolf.isBoat = false;
			armoredwolf.dieOnBlocks = false;
			armoredwolf.ignoreBlocks = false;
			armoredwolf.moveFromBlock = true;
			armoredwolf.procreate = false;
		    armoredwolf.inspect_children = false;
            armoredwolf.inspect_experience = true;
			armoredwolf.canBeCitizen = true;
            armoredwolf.inspect_kills = true;
            armoredwolf.use_items = false;
			armoredwolf.oceanCreature = false;
            armoredwolf.take_items = false;
            armoredwolf.nameLocale = "armoredwolf";
            armoredwolf.nameTemplate = "wolf_name";
			armoredwolf.job = "attacker";
            armoredwolf.icon = "iconarmoredwolf";
            	armoredwolf.fmod_spawn = "event:/SFX/UNITS/Wolf/WolfSpawn";
		armoredwolf.fmod_attack = "event:/SFX/UNITS/Wolf/WolfAttack";
		armoredwolf.fmod_idle = "event:/SFX/UNITS/Wolf/WolfIdle";
		armoredwolf.fmod_death = "event:/SFX/UNITS/Wolf/WolfDeath";
		armoredwolf.fmod_theme = "Units_Wolf";
			//AssetManager.actor_library.CallMethod("addTrait", "armoredwolf");
			AssetManager.actor_library.CallMethod("loadShadow", armoredwolf);
            armoredwolf.animation_walk = "walk_0,walk_1,walk_2";
			armoredwolf.animation_idle = "idle_0,idle_1";
            armoredwolf.animation_swim = "swim_0,swim_1,swim_2";
            armoredwolf.texture_path = "armoredwolf";
			AssetManager.actor_library.addColorSet("generic_dark");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "nightchild");
			AssetManager.actor_library.CallMethod("addTrait", "savage");
            AssetManager.actor_library.CallMethod("addTrait", "tough");
            AssetManager.actor_library.CallMethod("addTrait", "flesh_eater");
			armoredwolf.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(armoredwolf);
			Localization.addLocalization(armoredwolf.nameLocale, armoredwolf.nameLocale);


// SUPPORT
//
//=============================================================================//

            var humanpaladin = AssetManager.actor_library.clone("humanpaladin","_mob");
			//ActorAsset heli = new ActorAsset();
           // humanpaladin.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			humanpaladin.race = "human";
			humanpaladin.kingdom = "ModernKingdom";
			humanpaladin.base_stats[S.max_age] = 50f;
            humanpaladin.base_stats[S.health] = 100f;
            humanpaladin.base_stats[S.speed] = 60f;
            humanpaladin.base_stats[S.armor] = 30f;
            humanpaladin.base_stats[S.damage] = 10f;
            humanpaladin.base_stats[S.scale] = 0.1f;
            humanpaladin.base_stats[S.attack_speed] = 10;
			humanpaladin.base_stats[S.targets] = 1f;
            humanpaladin.defaultAttack = "base";
            humanpaladin.drawBoatMark_big = true;
            humanpaladin.inspect_stats = true;
			humanpaladin.landCreature = true;
			humanpaladin.inspect_home = true;
			humanpaladin.hideOnMinimap = false;
            humanpaladin.drawBoatMark = true;
			humanpaladin.can_edit_traits = true;
			humanpaladin.canReceiveTraits = true;
			humanpaladin.flying = false;
			//humanpaladin.tech = "humanpaladins";
			humanpaladin.very_high_flyer = false;
            humanpaladin.isBoat = false;
			humanpaladin.dieOnBlocks = false;
			humanpaladin.ignoreBlocks = false;
			humanpaladin.moveFromBlock = true;
			humanpaladin.procreate = false;
		    humanpaladin.inspect_children = false;
            humanpaladin.inspect_experience = true;
			humanpaladin.canBeCitizen = true;
            humanpaladin.inspect_kills = true;
            humanpaladin.use_items = false;
			humanpaladin.oceanCreature = false;
            humanpaladin.take_items = false;
            humanpaladin.nameLocale = "humanpaladin";
            humanpaladin.nameTemplate = "Modern_Names";
			humanpaladin.job = "attacker";
            humanpaladin.icon = "iconhumanpaladin";
			//AssetManager.actor_library.CallMethod("addTrait", "humanpaladin");
			AssetManager.actor_library.CallMethod("loadShadow", humanpaladin);
            humanpaladin.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			humanpaladin.animation_idle = "walk_0";
            humanpaladin.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            humanpaladin.texture_path = "humanpaladin";
			AssetManager.actor_library.addColorSet("heliColor");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "bubble_defense");
            AssetManager.actor_library.CallMethod("addTrait", "SupportRole");
			humanpaladin.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(humanpaladin);
			Localization.addLocalization(humanpaladin.nameLocale, humanpaladin.nameLocale);

            var orcwarlock = AssetManager.actor_library.clone("orcwarlock","_mob");
			//ActorAsset heli = new ActorAsset();
           // orcwarlock.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			orcwarlock.race = "orc";
			orcwarlock.kingdom = "ModernKingdom";
			orcwarlock.base_stats[S.max_age] = 50f;
            orcwarlock.base_stats[S.health] = 100f;
            orcwarlock.base_stats[S.speed] = 60f;
            orcwarlock.base_stats[S.armor] = 30f;
            orcwarlock.base_stats[S.damage] = 10f;
            orcwarlock.base_stats[S.scale] = 0.1f;
            orcwarlock.base_stats[S.attack_speed] = 10;
			orcwarlock.base_stats[S.targets] = 1f;
            orcwarlock.defaultAttack = "base";
            orcwarlock.drawBoatMark_big = true;
            orcwarlock.inspect_stats = true;
			orcwarlock.landCreature = true;
			orcwarlock.inspect_home = true;
			orcwarlock.hideOnMinimap = false;
            orcwarlock.drawBoatMark = true;
			orcwarlock.can_edit_traits = true;
			orcwarlock.canReceiveTraits = true;
			orcwarlock.flying = false;
			//orcwarlock.tech = "orcwarlocks";
			orcwarlock.very_high_flyer = false;
            orcwarlock.isBoat = false;
			orcwarlock.dieOnBlocks = false;
			orcwarlock.ignoreBlocks = false;
			orcwarlock.moveFromBlock = true;
			orcwarlock.procreate = false;
		    orcwarlock.inspect_children = false;
            orcwarlock.inspect_experience = true;
			orcwarlock.canBeCitizen = true;
            orcwarlock.inspect_kills = true;
            orcwarlock.use_items = false;
			orcwarlock.oceanCreature = false;
            orcwarlock.take_items = false;
            orcwarlock.nameLocale = "orcwarlock";
            orcwarlock.nameTemplate = "Modern_Names";
			orcwarlock.job = "attacker";
            orcwarlock.icon = "iconorcwarlock";
			//AssetManager.actor_library.CallMethod("addTrait", "orcwarlock");
			AssetManager.actor_library.CallMethod("loadShadow", orcwarlock);
            orcwarlock.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			orcwarlock.animation_idle = "walk_0";
            orcwarlock.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            orcwarlock.texture_path = "orcwarlock";
			AssetManager.actor_library.addColorSet("heliColor");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "bubble_defense");
            AssetManager.actor_library.CallMethod("addTrait", "SupportRole");
			orcwarlock.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(orcwarlock);
			Localization.addLocalization(orcwarlock.nameLocale, orcwarlock.nameLocale);

                        var dwarfdoctor = AssetManager.actor_library.clone("dwarfdoctor","_mob");
			//ActorAsset heli = new ActorAsset();
           // dwarfdoctor.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			dwarfdoctor.race = "dwarf";
			dwarfdoctor.kingdom = "ModernKingdom";
			dwarfdoctor.base_stats[S.max_age] = 50f;
            dwarfdoctor.base_stats[S.health] = 100f;
            dwarfdoctor.base_stats[S.speed] = 60f;
            dwarfdoctor.base_stats[S.armor] = 30f;
            dwarfdoctor.base_stats[S.damage] = 10f;
            dwarfdoctor.base_stats[S.scale] = 0.1f;
            dwarfdoctor.base_stats[S.attack_speed] = 10;
			dwarfdoctor.base_stats[S.targets] = 1f;
            dwarfdoctor.defaultAttack = "base";
            dwarfdoctor.drawBoatMark_big = true;
            dwarfdoctor.inspect_stats = true;
			dwarfdoctor.landCreature = true;
			dwarfdoctor.inspect_home = true;
			dwarfdoctor.hideOnMinimap = false;
            dwarfdoctor.drawBoatMark = true;
			dwarfdoctor.can_edit_traits = true;
			dwarfdoctor.canReceiveTraits = true;
			dwarfdoctor.flying = false;
			//dwarfdoctor.tech = "dwarfdoctors";
			dwarfdoctor.very_high_flyer = false;
            dwarfdoctor.isBoat = false;
			dwarfdoctor.dieOnBlocks = false;
			dwarfdoctor.ignoreBlocks = false;
			dwarfdoctor.moveFromBlock = true;
			dwarfdoctor.procreate = false;
		    dwarfdoctor.inspect_children = false;
            dwarfdoctor.inspect_experience = true;
			dwarfdoctor.canBeCitizen = true;
            dwarfdoctor.inspect_kills = true;
            dwarfdoctor.use_items = false;
			dwarfdoctor.oceanCreature = false;
            dwarfdoctor.take_items = false;
            dwarfdoctor.nameLocale = "dwarfdoctor";
            dwarfdoctor.nameTemplate = "Modern_Names";
			dwarfdoctor.job = "attacker";
            dwarfdoctor.icon = "icondwarfdoctor";
			//AssetManager.actor_library.CallMethod("addTrait", "dwarfdoctor");
			AssetManager.actor_library.CallMethod("loadShadow", dwarfdoctor);
            dwarfdoctor.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			dwarfdoctor.animation_idle = "walk_0";
            dwarfdoctor.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            dwarfdoctor.texture_path = "dwarfdoctor";
			AssetManager.actor_library.addColorSet("heliColor");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "bubble_defense");
            AssetManager.actor_library.CallMethod("addTrait", "SupportRole");
			dwarfdoctor.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(dwarfdoctor);
			Localization.addLocalization(dwarfdoctor.nameLocale, dwarfdoctor.nameLocale);

                        var fairydragon = AssetManager.actor_library.clone("fairydragon","_mob");
			//ActorAsset heli = new ActorAsset();
           // fairydragon.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			fairydragon.race = "elf";
			fairydragon.kingdom = "ModernKingdom";
			fairydragon.base_stats[S.max_age] = 50f;
            fairydragon.base_stats[S.health] = 100f;
            fairydragon.base_stats[S.speed] = 60f;
            fairydragon.base_stats[S.armor] = 30f;
            fairydragon.base_stats[S.damage] = 10f;
            fairydragon.base_stats[S.scale] = 0.1f;
            fairydragon.base_stats[S.attack_speed] = 10;
			fairydragon.base_stats[S.targets] = 1f;
            fairydragon.defaultAttack = "base";
            fairydragon.drawBoatMark_big = true;
            fairydragon.inspect_stats = true;
			fairydragon.landCreature = true;
			fairydragon.inspect_home = true;
			fairydragon.hideOnMinimap = false;
            fairydragon.drawBoatMark = true;
			fairydragon.can_edit_traits = true;
			fairydragon.canReceiveTraits = true;
			fairydragon.flying = false;
			//fairydragon.tech = "fairydragons";
			fairydragon.very_high_flyer = false;
            fairydragon.isBoat = false;
			fairydragon.dieOnBlocks = false;
			fairydragon.ignoreBlocks = false;
			fairydragon.moveFromBlock = true;
			fairydragon.procreate = false;
		    fairydragon.inspect_children = false;
            fairydragon.inspect_experience = true;
			fairydragon.canBeCitizen = true;
            fairydragon.inspect_kills = true;
            fairydragon.use_items = false;
			fairydragon.oceanCreature = false;
            fairydragon.take_items = false;
            fairydragon.nameLocale = "fairydragon";
            fairydragon.nameTemplate = "Modern_Names";
			fairydragon.job = "attacker";
            fairydragon.icon = "iconfairydragon";
			//AssetManager.actor_library.CallMethod("addTrait", "fairydragon");
			AssetManager.actor_library.CallMethod("loadShadow", fairydragon);
            fairydragon.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			fairydragon.animation_idle = "walk_0,walk_1,walk_2,walk_3";
            fairydragon.animation_swim = "walk_0,walk_1,walk_2,walk_3";
            fairydragon.texture_path = "fairydragon";
			AssetManager.actor_library.addColorSet("heliColor");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "bubble_defense");
            AssetManager.actor_library.CallMethod("addTrait", "SupportRole");
			fairydragon.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(fairydragon);
			Localization.addLocalization(fairydragon.nameLocale, fairydragon.nameLocale);

                        var fairelf = AssetManager.actor_library.clone("fairelf","_mob");
			//ActorAsset heli = new ActorAsset();
           // fairelf.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			fairelf.race = "elf";
			fairelf.kingdom = "ModernKingdom";
			fairelf.base_stats[S.max_age] = 50f;
            fairelf.base_stats[S.health] = 100f;
            fairelf.base_stats[S.speed] = 60f;
            fairelf.base_stats[S.armor] = 30f;
            fairelf.base_stats[S.damage] = 10f;
            fairelf.base_stats[S.scale] = 0.1f;
            fairelf.base_stats[S.attack_speed] = 10;
			fairelf.base_stats[S.targets] = 1f;
            fairelf.defaultAttack = "base";
            fairelf.drawBoatMark_big = true;
            fairelf.inspect_stats = true;
			fairelf.landCreature = true;
			fairelf.inspect_home = true;
			fairelf.hideOnMinimap = false;
            fairelf.drawBoatMark = true;
			fairelf.can_edit_traits = true;
			fairelf.canReceiveTraits = true;
			fairelf.flying = false;
			//fairelf.tech = "fairelfs";
			fairelf.very_high_flyer = false;
            fairelf.isBoat = false;
			fairelf.dieOnBlocks = false;
			fairelf.ignoreBlocks = false;
			fairelf.moveFromBlock = true;
			fairelf.procreate = false;
		    fairelf.inspect_children = false;
            fairelf.inspect_experience = true;
			fairelf.canBeCitizen = true;
            fairelf.inspect_kills = true;
            fairelf.use_items = false;
			fairelf.oceanCreature = false;
            fairelf.take_items = false;
            fairelf.nameLocale = "fairelf";
            fairelf.nameTemplate = "Modern_Names";
			fairelf.job = "attacker";
            fairelf.icon = "iconfairelf";
			//AssetManager.actor_library.CallMethod("addTrait", "fairelf");
			AssetManager.actor_library.CallMethod("loadShadow", fairelf);
            fairelf.animation_walk = "walk_0,walk_1,walk_2,walk_3";
			fairelf.animation_idle = "walk_0,walk_1,walk_2,walk_3";
            fairelf.animation_swim = "walk_0,walk_1,walk_2,walk_3";
            fairelf.texture_path = "fairelf";
			AssetManager.actor_library.addColorSet("heliColor");
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			AssetManager.actor_library.CallMethod("addTrait", "bubble_defense");
            AssetManager.actor_library.CallMethod("addTrait", "SupportRole");
			fairelf.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(fairelf);
			Localization.addLocalization(fairelf.nameLocale, fairelf.nameLocale);


						var humancannon = AssetManager.actor_library.clone("humancannon","_mob");
			//ActorAsset heli = new ActorAsset();
           // humancannon.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			humancannon.race = "human";
			humancannon.kingdom = "MissileLauncherFULLRANGETARGETTING";
            humancannon.texture_path = "humancannon";
			humancannon.base_stats[S.max_age] = 50f;
            humancannon.base_stats[S.health] = 200f;
            humancannon.base_stats[S.speed] = 20f;
            humancannon.base_stats[S.armor] = 30f;
            humancannon.base_stats[S.damage] = 80f;
            humancannon.base_stats[S.scale] = 0.2f;
            humancannon.base_stats[S.attack_speed] = -300;
			humancannon.base_stats[S.range] = 34f;
			humancannon.base_stats[S.knockback_reduction] = 1f;
            humancannon.drawBoatMark_big = true;
            humancannon.inspect_stats = true;
			humancannon.landCreature = true;
			humancannon.inspect_home = true;
			humancannon.hideOnMinimap = false;
			  humancannon.has_skin = false;
			humancannon.immune_to_injuries = true;
            humancannon.drawBoatMark = true;
			humancannon.can_edit_traits = true;
            humancannon.disablePunchAttackAnimation = true;
			humancannon.canReceiveTraits = true;
			humancannon.flying = false;
			//humancannon.tech = "humancannons";
			humancannon.very_high_flyer = false;
			humancannon.defaultAttack = "cannonstriker";
            humancannon.isBoat = false;
			humancannon.dieOnBlocks = false;
			humancannon.ignoreBlocks = true;
			//humancannon.moveFromBlock = false;
			humancannon.procreate = false;
		    humancannon.inspect_children = false;
            humancannon.inspect_experience = true;
			humancannon.canBeCitizen = true;
            humancannon.inspect_kills = true;
            humancannon.use_items = false;
			humancannon.oceanCreature = false;
            humancannon.take_items = false;
            humancannon.nameLocale = "humancannon";
            humancannon.nameTemplate = "Jet_Names";
			humancannon.job = "attacker";
            humancannon.icon = "iconhumancannon";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "humancannon");
			AssetManager.actor_library.CallMethod("loadShadow", humancannon);
            humancannon.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            humancannon.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            humancannon.animation_idle = "walk_0";
			AssetManager.actor_library.addColorSet("heliColor");
			humancannon.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(humancannon);
			Localization.addLocalization(humancannon.nameLocale, humancannon.nameLocale);

						var orccannon = AssetManager.actor_library.clone("orccannon","_mob");
			//ActorAsset heli = new ActorAsset();
           // orccannon.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			orccannon.race = "orc";
			orccannon.kingdom = "MissileLauncherFULLRANGETARGETTING";
            orccannon.texture_path = "orccannon";
			orccannon.base_stats[S.max_age] = 50f;
            orccannon.base_stats[S.health] = 200f;
            orccannon.base_stats[S.speed] = 20f;
            orccannon.base_stats[S.armor] = 30f;
            orccannon.base_stats[S.damage] = 80f;
            orccannon.base_stats[S.scale] = 0.2f;
            orccannon.base_stats[S.attack_speed] = -300;
			orccannon.base_stats[S.range] = 34f;
			orccannon.base_stats[S.knockback_reduction] = 1f;
            orccannon.drawBoatMark_big = true;
            orccannon.inspect_stats = true;
			orccannon.landCreature = true;
			orccannon.inspect_home = true;
			orccannon.hideOnMinimap = false;
            orccannon.drawBoatMark = true;
			orccannon.can_edit_traits = true;
			 orccannon.has_skin = false;
			orccannon.immune_to_injuries = true;
            orccannon.disablePunchAttackAnimation = true;
			orccannon.canReceiveTraits = true;
			orccannon.flying = false;
			//orccannon.tech = "orccannons";
			orccannon.very_high_flyer = false;
			orccannon.defaultAttack = "cannonstriker";
            orccannon.isBoat = false;
			orccannon.dieOnBlocks = false;
			orccannon.ignoreBlocks = true;
			//orccannon.moveFromBlock = false;
			orccannon.procreate = false;
		    orccannon.inspect_children = false;
            orccannon.inspect_experience = true;
			orccannon.canBeCitizen = true;
            orccannon.inspect_kills = true;
            orccannon.use_items = false;
			orccannon.oceanCreature = false;
            orccannon.take_items = false;
            orccannon.nameLocale = "orccannon";
            orccannon.nameTemplate = "Jet_Names";
			orccannon.job = "attacker";
            orccannon.icon = "iconorccannon";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "orccannon");
			AssetManager.actor_library.CallMethod("loadShadow", orccannon);
            orccannon.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            orccannon.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            orccannon.animation_idle = "walk_0";
			AssetManager.actor_library.addColorSet("heliColor");
			orccannon.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(orccannon);
			Localization.addLocalization(orccannon.nameLocale, orccannon.nameLocale);

						var elfcannon = AssetManager.actor_library.clone("elfcannon","_mob");
			//ActorAsset heli = new ActorAsset();
           // elfcannon.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			elfcannon.race = "elf";
			elfcannon.kingdom = "MissileLauncherFULLRANGETARGETTING";
            elfcannon.texture_path = "elfcannon";
			elfcannon.base_stats[S.max_age] = 50f;
            elfcannon.base_stats[S.health] = 200f;
            elfcannon.base_stats[S.speed] = 20f;
            elfcannon.base_stats[S.armor] = 30f;
            elfcannon.base_stats[S.damage] = 80f;
            elfcannon.base_stats[S.scale] = 0.2f;
            elfcannon.base_stats[S.attack_speed] = -300;
			elfcannon.base_stats[S.range] = 34f;
			elfcannon.base_stats[S.knockback_reduction] = 1f;
            elfcannon.drawBoatMark_big = true;
			elfcannon.has_skin = false;
			elfcannon.immune_to_injuries = true;
            elfcannon.inspect_stats = true;
			elfcannon.landCreature = true;
			elfcannon.inspect_home = true;
			elfcannon.hideOnMinimap = false;
            elfcannon.drawBoatMark = true;
			elfcannon.can_edit_traits = true;
            elfcannon.disablePunchAttackAnimation = true;
			elfcannon.canReceiveTraits = true;
			elfcannon.flying = false;
			//elfcannon.tech = "elfcannons";
			elfcannon.very_high_flyer = false;
			elfcannon.defaultAttack = "cannonstriker";
            elfcannon.isBoat = false;
			elfcannon.dieOnBlocks = false;
			elfcannon.ignoreBlocks = true;
			//elfcannon.moveFromBlock = false;
			elfcannon.procreate = false;
		    elfcannon.inspect_children = false;
            elfcannon.inspect_experience = true;
			elfcannon.canBeCitizen = true;
            elfcannon.inspect_kills = true;
            elfcannon.use_items = false;
			elfcannon.oceanCreature = false;
            elfcannon.take_items = false;
            elfcannon.nameLocale = "elfcannon";
            elfcannon.nameTemplate = "Jet_Names";
			elfcannon.job = "attacker";
            elfcannon.icon = "iconelfcannon";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "elfcannon");
			AssetManager.actor_library.CallMethod("loadShadow", elfcannon);
            elfcannon.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            elfcannon.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            elfcannon.animation_idle = "walk_0";
			AssetManager.actor_library.addColorSet("heliColor");
			elfcannon.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(elfcannon);
			Localization.addLocalization(elfcannon.nameLocale, elfcannon.nameLocale);

	var dwarfcannon = AssetManager.actor_library.clone("dwarfcannon","_mob");
			//ActorAsset heli = new ActorAsset();
           // dwarfcannon.get_override_sprite = AssetManager.actor_library.get("_boat").get_override_sprite;
			dwarfcannon.race = "dwarf";
			dwarfcannon.kingdom = "MissileLauncherFULLRANGETARGETTING";
            dwarfcannon.texture_path = "dwarfcannon";
			dwarfcannon.base_stats[S.max_age] = 50f;
            dwarfcannon.base_stats[S.health] = 200f;
            dwarfcannon.base_stats[S.speed] = 20f;
            dwarfcannon.base_stats[S.armor] = 30f;
            dwarfcannon.base_stats[S.damage] = 80f;
            dwarfcannon.base_stats[S.scale] = 0.2f;
            dwarfcannon.base_stats[S.attack_speed] = -300;
			dwarfcannon.base_stats[S.range] = 34f;
			dwarfcannon.base_stats[S.knockback_reduction] = 1f;
            dwarfcannon.drawBoatMark_big = true;
            dwarfcannon.inspect_stats = true;
			dwarfcannon.landCreature = true;
			dwarfcannon.inspect_home = true;
			dwarfcannon.has_skin = false;
			dwarfcannon.immune_to_injuries = true;
			dwarfcannon.hideOnMinimap = false;
            dwarfcannon.drawBoatMark = true;
			dwarfcannon.can_edit_traits = true;
            dwarfcannon.disablePunchAttackAnimation = true;
			dwarfcannon.canReceiveTraits = true;
			dwarfcannon.flying = false;
			//dwarfcannon.tech = "dwarfcannons";
			dwarfcannon.very_high_flyer = false;
			dwarfcannon.defaultAttack = "cannonstriker";
            dwarfcannon.isBoat = false;
			dwarfcannon.dieOnBlocks = false;
			dwarfcannon.ignoreBlocks = true;
			//dwarfcannon.moveFromBlock = false;
			dwarfcannon.procreate = false;
		    dwarfcannon.inspect_children = false;
            dwarfcannon.inspect_experience = true;
			dwarfcannon.canBeCitizen = true;
            dwarfcannon.inspect_kills = true;
            dwarfcannon.use_items = false;
			dwarfcannon.oceanCreature = false;
            dwarfcannon.take_items = false;
            dwarfcannon.nameLocale = "dwarfcannon";
            dwarfcannon.nameTemplate = "Jet_Names";
			dwarfcannon.job = "attacker";
            dwarfcannon.icon = "icondwarfcannon";
			AssetManager.actor_library.CallMethod("addTrait", "Unitpotential");
			//AssetManager.actor_library.CallMethod("addTrait", "dwarfcannon");
			AssetManager.actor_library.CallMethod("loadShadow", dwarfcannon);
            dwarfcannon.animation_walk = "walk_0,walk_1,walk_2,walk_3";
            dwarfcannon.animation_swim = "swim_0,swim_1,swim_2,swim_3";
            dwarfcannon.animation_idle = "walk_0";
			AssetManager.actor_library.addColorSet("heliColor");
			dwarfcannon.color = Toolbox.makeColor("#33724D");
            AssetManager.actor_library.add(dwarfcannon);
			Localization.addLocalization(dwarfcannon.nameLocale, dwarfcannon.nameLocale);

		}
		}
}

